function WebVideoAiNovelPanel(){
 const R=reactExports,h=R.createElement,P=WebVideoProject,[source,setSource]=R.useState(''),[config,setConfig]=R.useState(null),[busy,setBusy]=R.useState(false),[elapsed,setElapsed]=R.useState(0),[message,setMessage]=R.useState(''),[draft,setDraft]=R.useState(null),[allowTwo,setAllowTwo]=R.useState(false),job=R.useRef(null),live=R.useRef(true),started=R.useRef(0),file=R.useRef(null);
 R.useEffect(()=>{WebVideoAiApi('config').then(setConfig).catch(e=>setMessage(e.message));return()=>{live.current=false;if(job.current)WebVideoAiApi('novel/cancel',{id:job.current}).catch(()=>{});};},[]);
 R.useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-started.current)/1000)),1000);return()=>clearInterval(timer);},[busy]);
 R.useEffect(()=>WebVideoTools.registerCloseGuard('novelImport',()=>!busy),[busy]);
 async function generate(){if(busy)return;setBusy(true);started.current=Date.now();setElapsed(0);setDraft(null);setMessage('正在准备原文…');try{const model=WebVideoPlus.state().model;if(!model)throw Error('请先打开故事文本。');const mapping=await WebVideoCharacterMap.load();if(mapping?.fatal)throw Error('角色对应表不可用，请先修正配置。');const prepared=WebVideoNovel.prepare(source,mapping);const task=await WebVideoAiApi('novel/start',{...prepared,project:P.state().scope?.game,allowTwo});job.current=task.id;if(!live.current){await WebVideoAiApi('novel/cancel',{id:task.id});return;}setMessage('正在识别对白、旁白和说话人…');while(live.current){await new Promise(resolve=>setTimeout(resolve,1500));const state=await WebVideoAiApi('novel/status',{id:task.id});if(!live.current)return;if(state.state==='running'){setMessage(state.totalBatches?(state.phase||'处理原文')+'：第 '+Math.min(state.completedBatches+1,state.totalBatches)+' / '+state.totalBatches+' 批'+(state.retrying?'（中断后重试 1/1）':'')+'…':state.phase||'正在识别对白、旁白和说话人…');continue;}if(state.state==='cancelled')throw Error('已取消，剧本未改动。');if(state.state!=='complete')throw Error(state.error||'生成未完成。');const result=WebVideoNovel.resolve(prepared,state.result);result.staging=state.result.staging;const plan=WebVideoNovel.plan(model,prepared,result);setDraft({model,prepared,result,plan});setMessage('已生成 '+plan.changed+' 条可编辑语句；尚未写入故事。');break;}}catch(e){if(live.current)setMessage(e.message);}finally{job.current=null;if(live.current)setBusy(false);}}
 async function cancel(){if(job.current){setMessage('正在取消…');try{await WebVideoAiApi('novel/cancel',{id:job.current});}catch(e){setMessage(e.message);}}}
 async function apply(){if(!draft||busy)return;setBusy(true);started.current=Date.now();try{const current=WebVideoPlus.state().model;if(current?.path!==draft.model.path||current?.source!==draft.model.source)throw Error('当前故事已修改或切换，请重新生成后再应用。');await P.commit(draft.plan,'AI小说转剧本骨架');setMessage('已追加 '+draft.plan.changed+' 条语句，全部标记为待核对；原故事已备份。');setDraft(null);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const stageByRow=new Map((draft?.result.staging?.changes||[]).map(c=>[c.at,c]));const stageActors=new Map((draft?.result.staging?.assets.actors||[]).map(a=>[a.key,a]));
 const active=config?.profiles?.[config.selected],providerName=config?.catalog?.providers?.find(p=>p.id===config.selected)?.name||config?.selected||'';
 return h('div',{className:'wvp-novel-panel'},h('p',{className:'wvp-help'},active?.hasKey?'使用 '+providerName+' · '+active.model:'请先在配置栏填写 API Key 并选择模型。'),h('label',{className:'wvp-novel-mode'},h('input',{type:'checkbox',checked:allowTwo,disabled:busy,onChange:e=>{setAllowTwo(e.target.checked);setDraft(null);}}),'允许双人同屏'),h('p',{className:'wvp-help'},allowTwo?'最多两人：单人居中，双人分列左右。':'最多一人居中，也可无人出镜。'),h('label',null,'小说原文',h('textarea',{value:source,disabled:busy,rows:draft?5:12,placeholder:'粘贴小说原文，长文会自动分批处理。仅做分段、分类与说话人识别，第二轮安排基础背景和人物，不填写表情动作。',onChange:e=>{setSource(e.target.value);setDraft(null);}})),h('div',{className:'wvp-novel-actions'},h('input',{type:'file',accept:'.txt,text/plain',ref:file,hidden:true,onChange:async e=>{const selected=e.target.files?.[0];if(!selected)return;try{if(selected.size>8000000)throw Error('文件过大，请按卷分次处理。');setSource(await selected.text());setDraft(null);}catch(error){setMessage(error.message);}finally{e.target.value='';}}}),h('button',{type:'button',disabled:busy,onClick:()=>file.current.click()},'读取 TXT'),h('span',null,[...source].length+' 字'),h('button',{type:'button',className:'primary',disabled:busy||!source.trim()||!active?.hasKey,onClick:generate},'生成骨架'),busy&&job.current&&h('button',{type:'button',onClick:cancel},'取消')),h('p',{className:'wvp-novel-status',role:'status'},message,busy?'（'+elapsed+' 秒）':''),draft&&h('p',{className:'wvp-help'},'已生成基础舞台安排。背景 '+draft.result.staging.assets.backgrounds.length+' 个；角色立绘：'+draft.result.staging.assets.actors.map(a=>a.name+' '+a.figures.length+' 个'+(!a.figures.length?'（未找到，将按画外音处理）':'')).join('、')),draft&&h('div',{className:'wvp-novel-preview'},...draft.result.rows.map((row,i)=>h('div',{key:i},stageByRow.has(i)&&h('small',{className:'wvp-stage-preview'},'背景：'+(stageByRow.get(i).background??'保持')+'；人物：'+(stageByRow.get(i).cast.map(p=>(stageActors.get(p.actor)?.name||p.actor)+' · '+p.figure).join('、')||'无')),h('small',null,(row.kind==='dialogue'?(row.speaker||'说话人待核对'):'旁白')+(row.sceneBreak?' · 场景变化':'')+(row.uncertain?' · 待核对':'')),h('p',null,row.text)))),draft&&draft.result.omitted.length>0&&h('details',null,h('summary',null,'版式与引导语处理 · '+draft.result.omitted.length+' 项'),h('p',null,draft.result.omitted.filter(x=>x.reason!=='版式').map(x=>x.text+'（'+x.reason+'）').join('；')||'仅整理空白及引号。')),h('footer',null,h('span',null,'生成会调用所配置的模型，可能产生费用。'),draft&&h('button',{type:'button',className:'primary',disabled:busy,onClick:apply},'追加到当前故事')));
}
WebVideoTools.register('novelImport','小说转剧本骨架',WebVideoAiNovelPanel);
