function WebVideoBackupPanel(){
 const R=reactExports,F=WebVideoForm,h=R.createElement,P=WebVideoProject,[entries,setEntries]=R.useState([]),[message,setMessage]=R.useState(''),[busy,setBusy]=R.useState(false),[loading,setLoading]=R.useState(true);const project=P.state().scope?.root;
 async function reload(){setLoading(true);try{setEntries(await P.listBackups());}catch(e){setMessage(e.message);}finally{setLoading(false);}}
 R.useEffect(()=>{let active=true;setEntries([]);setLoading(true);P.listBackups().then(rows=>{if(active)setEntries(rows);}).catch(e=>{if(active)setMessage(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[project]);
 async function openScene(backup){const current=WebVideoPlus.state().model;if(current?.path===backup.path)return;await WebVideoPlus.flushEditor?.();const scene=backup.path.split('/game/scene/')[1];WebVideoTools.state().context.openScene(scene);for(let n=0;n<100;n++){if(P.state().scope?.root!==project)throw Error('项目已切换，恢复已取消');if(WebVideoPlus.state().model?.path===backup.path)return;await new Promise(resolve=>setTimeout(resolve,100));}throw Error('场景尚未载入，请稍后重新选择备份');}
 async function restore(item){if(busy||!window.confirm('确定回滚到 '+date(item.createdAt)+' 的“'+item.label+'”吗？\n'+(item.scene||'')+'\n当前内容会自动备份。'))return;setBusy(true);setMessage('正在回滚…');try{const backup=await P.readBackup(item);if(P.state().scope?.root!==project)throw Error('项目已切换，回滚已取消');if(backup.kind==='storySet'){if(backup.createdAt!==item.createdAt)throw Error('自动备份已更新，请刷新列表后重新选择。');await P.restoreStories(item);}else if(backup.kind==='music')await P.saveMusic(JSON.parse(backup.before));else{await openScene(backup);const plan=P.restorePlan(backup);if(plan.after===plan.before){setMessage('当前内容与该备份一致，无需回滚。');return;}await P.commit(plan,'回滚：'+item.label);}await reload();setMessage('已回滚，回滚前的内容也已自动备份。');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const date=value=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'时间未知';
 return h('div',{className:'wvp-backup-panel'},h('div',{className:'wvp-backup-heading'},h('p',{className:'wvp-help'},'当前项目的全部历史备份。批量修改和回滚前均自动保存原文。'),F.button('刷新列表',reload,{disabled:busy||loading})),loading?h('p',null,'正在读取历史备份…'):h('div',{className:'wvp-backup-list'},entries.length?entries.map(item=>h('div',{key:item.file,className:'wvp-backup-item'},h('div',{className:'wvp-backup-copy'},h('strong',null,item.label),h('time',null,date(item.createdAt)),h('span',null,item.scene||item.error)),F.button('回滚',()=>restore(item),{disabled:busy||!!item.error}))):h('p',null,'当前项目还没有历史备份。')),F.notice(message));
}
WebVideoTools.register('backups','备份与恢复',WebVideoBackupPanel);
