function WebVideoBatchPanel({initialMode='insert',fixedMode=false,templateOnly=false}={}){
 const R=reactExports,F=WebVideoForm,h=F.h,P=WebVideoProject,T=WebVideoTools;
 const [selection,setSelection]=R.useState(null),[mode,setMode]=R.useState(initialMode),[position,setPosition]=R.useState('before'),[script,setScript]=R.useState(''),[find,setFind]=R.useState(''),[replacement,setReplacement]=R.useState(''),[parameter,setParameter]=R.useState('motion'),[value,setValue]=R.useState(''),[remove,setRemove]=R.useState(false),[plan,setPlan]=R.useState(null),[name,setName]=R.useState(''),[message,setMessage]=R.useState(''),[busy,setBusy]=R.useState(false);
 const templates=P.state().project.templates;
 const change=(setter)=>e=>{setter(e.target.type==='checkbox'?e.target.checked:e.target.value);setPlan(null);};
 async function select(){try{const s=await T.select('set');if(s){setSelection(s);setPlan(null);}}catch(e){setMessage(e.message);}}
 function preview(){try{setPlan(P.plan(selection,{type:mode,position,script,find,replace:replacement,key:parameter,value,remove}));setMessage('核对修改后，再应用到剧本。');requestAnimationFrame(()=>document.querySelector('.wvp-tool-content .wvp-change-preview')?.scrollIntoView({block:'start'}));}catch(e){setMessage(e.message);setPlan(null);}}
 async function apply(){setBusy(true);try{const result=await P.commit(plan,'批量'+({insert:'插入',statement:'替换语句',text:'替换正文',parameter:'修改参数'}[mode]));setSelection(null);setPlan(null);setMessage(result.warning||`已应用 ${result.changed} 处修改，并保存操作前备份。`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function saveTemplate(){try{if(!name.trim()||!script.trim())throw Error('请填写模板名称和内容');P.parse(script.replace(/\{\{\w+\}\}/g,'example'));await P.update(p=>{const existing=p.templates.find(t=>t.name===name.trim());if(existing)throw Error('模板名称已存在，请使用新名称');p.templates.push({id:crypto.randomUUID(),name:name.trim(),script,createdAt:new Date().toISOString()});});setMessage('模板已保存到当前项目。');}catch(e){setMessage(e.message);}}
 function copySelection(){try{if(!selection||!WebVideoPlus.validateSelection(selection))throw Error('请重新选择剧情');const text=selection.mode==='range'?selection.ranges.map(r=>selection.source.slice(r.startOffset,r.endOffset)).join('\n'):selection.statements.map(s=>s.source).join('\n');setScript(text.trim());setPlan(null);setMessage('已将所选标准剧本复制到模板编辑区。');}catch(e){setMessage(e.message);}}
 return h('div',null,F.selection(selection,select),h('div',{className:'wvp-tool-grid'},!fixedMode&&F.field('修改方式',h('select',{value:mode,onChange:change(setMode)},...[['insert','插入语句'],['statement','替换整条语句'],['text','替换正文'],['parameter','修改参数']].map(([v,t])=>h('option',{key:v,value:v},t)))),mode==='insert'&&F.field('插入位置',h('select',{value:position,onChange:change(setPosition)},h('option',{value:'before'},'每个选中事件之前'),h('option',{value:'after'},'每个选中事件之后')))),
  ['insert','statement'].includes(mode)&&h(R.Fragment,null,F.field(templateOnly?'模板内容':'要插入或替换的语句',h('textarea',{rows:5,value:script,onChange:change(setScript),placeholder:'填写标准 WebGAL 语句。可使用 {{speaker}}、{{figureId}}、{{content}}。'})),h('p',{className:'wvp-help'},'插入按可见的剧情事件进行；范围中间的技术语句不会被隐式替换。'),h('details',{open:templateOnly||undefined},h('summary',null,'使用或保存模板'),h('div',{className:'wvp-tool-row'},h('select',{'aria-label':'项目模板',defaultValue:'',onChange:e=>{const t=templates.find(t=>t.id===e.target.value);if(t){setScript(t.script);setName(t.name);setPlan(null);}}},h('option',{value:''},'载入项目模板'),...templates.map(t=>h('option',{key:t.id,value:t.id},t.name))),F.button('复制所选剧情',copySelection),h('input',{'aria-label':'模板名称',placeholder:'新模板名称',value:name,onChange:change(setName)}),F.button('保存为模板',saveTemplate)))),
  mode==='text'&&h('div',{className:'wvp-tool-grid'},F.field('查找正文',h('input',{value:find,onChange:change(setFind)})),F.field('替换为',h('input',{value:replacement,onChange:change(setReplacement)}))),
  mode==='parameter'&&h('div',{className:'wvp-tool-grid'},F.field('参数名',h('input',{value:parameter,onChange:change(setParameter),placeholder:'motion / expression / figureId'})),F.field('参数值',h('input',{value,onChange:change(setValue),disabled:remove})),h('label',null,h('input',{type:'checkbox',checked:remove,onChange:change(setRemove)}),' 删除该参数')),
  F.preview(plan),F.notice(message),h('div',{className:'wvp-tool-actions'},F.button('预览修改',preview,{disabled:busy||!selection}),F.button('应用并备份',apply,{className:'primary',disabled:busy||!plan?.changed||WebVideoPlus.state().model?.source!==plan.before})),
  templates.length>0&&h('details',null,h('summary',null,'管理项目模板'),...templates.map(t=>h('div',{key:t.id,className:'wvp-tool-row'},h('span',null,t.name),F.button('删除模板',async()=>{await P.update(p=>{p.templates=p.templates.filter(x=>x.id!==t.id);});setMessage('模板已删除；剧本不受影响。');})))));
}
WebVideoTools.register('batchTools','批量编辑与模板',WebVideoBatchPanel);
