/* Only numerical effect payloads survive extraction; commands and targets never enter the library. */
const WebVideoFilters=(()=>{
 const M=window.WebVideoNavigationMetadata,extras={shockwaveFilter:'冲击波滤镜',radiusAlphaFilter:'径向透明度滤镜'},fields={...M.fields,...Object.fromEntries(Object.entries(extras).map(([key,label])=>[key,{path:key,label}]))};
 const get=(value,path)=>path.split('.').reduce((v,key)=>v?.[key],value),set=(o,path,value)=>{const parts=path.split('.');if(parts.length===1)o[parts[0]]=value;else(o[parts[0]]??={})[parts[1]]=value;};
 function clean(effect){if(!effect||Array.isArray(effect)||typeof effect!=='object')throw Error('效果片段必须是 JSON 对象。');const output={};for(const [key,meta]of Object.entries(fields)){const value=get(effect,meta.path);if(value===undefined)continue;if(typeof value!=='number'||!Number.isFinite(value))throw Error(meta.label+'必须是有效数字。');set(output,meta.path,value);}if(!Object.keys(output).length)throw Error('没有找到可保存的效果参数。');return output;}
 function sanitize(effects){if(!Array.isArray(effects)||!effects.length||effects.length>100)throw Error('请输入 1 到 100 段效果。');return effects.map(clean);}
 function extract(code){const text=code.trim();if(!text)throw Error('请填写滤镜代码。');if(text.startsWith('{')||text.startsWith('[')){const value=JSON.parse(text);return sanitize(Array.isArray(value)?value:[value]);}const parsed=WebVideoProject.parse(text),effects=[];for(const statement of parsed.sentenceList||[]){if(statement.isLineBreakHolder)continue;const command=commandType[statement.command]||statement.commandRaw,args=Object.fromEntries((statement.args||[]).map(a=>[a.key,a.value]));if(command==='comment')continue;let value;if(command==='setTransform'||command==='setTempAnimation')value=JSON.parse(statement.content);else if(args.transform!==undefined)value=typeof args.transform==='object'?args.transform:JSON.parse(args.transform);else throw Error('第 '+(statement.startLine+1)+' 行没有明确的效果片段，请使用 setTransform 或带 transform 的语句。');effects.push(...(Array.isArray(value)?value:[value]));}return sanitize(effects);}
 function nameFor(effects){return effects.map(effect=>Object.entries(fields).filter(([,meta])=>get(effect,meta.path)!==undefined).map(([key,meta])=>{const prefix=key.startsWith('bloom')?'泛光':key.startsWith('bevel')?'倒角':'';return prefix+meta.label+'：'+get(effect,meta.path);}).join('、')).join('；');}
 function rows(model,allowAnimations=false){
  const animations=new Set(['setAnimation','setComplexAnimation','setTransform','setTempAnimation','setTransition']),all=model?.rows||[],statements=model?.statements||[],byId=new Map(all.map(row=>[row.id,row]));
  return all.filter(row=>row.command==='changeBg'||row.command==='changeFigure'&&row.main||animations.has(row.command)&&!row.parentId).map(row=>{
   const target=row.command==='changeBg'?'bg-main':row.target,parts=[...(row.embeddedEffects||[])],related=new Map();if(animations.has(row.command))related.set(row.id,row);
   for(const child of all)if(child.parentId===row.id&&animations.has(child.command))related.set(child.id,child);
   for(let i=statements.findIndex(item=>item.id===row.id)+1;i>0&&i<statements.length;i++){const next=statements[i];if(next.command==='comment')continue;if(!animations.has(next.command)||String(next.args.target??'')!==target)break;related.set(next.id,byId.get(next.id)||next);}
   for(const effect of related.values())parts.push(...(effect.parts?.length?effect.parts:[{title:effect.title||'效果',items:[]} ]));
   if(!parts.length&&row.args.transform){try{const value=typeof row.args.transform==='object'?row.args.transform:JSON.parse(row.args.transform);if(Object.keys(value).length)parts.push({title:'已有变换效果',items:[]});}catch{parts.push({title:'效果参数无法解析',items:[]});}}
   const names=[...new Set(parts.map(part=>part.filterName).filter(Boolean))],labels=[...new Set(parts.filter(part=>!part.filterName).map(part=>part.title).filter(Boolean))],existing=parts.length>0,summary=names.length?'滤镜：'+names.join(' · '):existing?'效果：'+labels.join(' · '):'',details=parts.map(part=>[part.title,...(part.items||[]),part.footer].filter(Boolean).join('，')).join('；');
   const departure=row.command==='changeFigure'&&(!row.content||row.content==='none'||row.args.clear===true);return {row,target,departure,isAnimation:animations.has(row.command),background:target==='bg-main',eligible:!departure&&(allowAnimations||!animations.has(row.command))&&typeof target==='string'&&!!target&&!/[\s;|]/.test(target),reason:departure?'不适用，仅作提示':!allowAnimations&&animations.has(row.command)?'需允许选择动画':target?'目标参数无效':'未指定目标',existing,summary,details};
  });
 }
 function plan(model,items,selected,background,figure){const eol=model.source.includes('\r\n')?'\r\n':'\n',patches=[];let appended=0;for(const item of items){if(!item.eligible||!selected.has(item.row.id))continue;const effects=item.background?background:figure;if(!effects?.length)continue;const lines=effects.map(effect=>'setTransform:'+JSON.stringify(effect)+' -target='+item.target+' -duration=0 -next;');const at=item.row.endOffset,prefix=at>0&&!/[\r\n]$/.test(model.source.slice(0,at))?eol:'';patches.push({startOffset:at,endOffset:at,before:'',after:prefix+lines.join(eol)+eol,line:item.row.startLine});appended+=lines.length;}let after=model.source;for(const patch of [...patches].reverse())after=after.slice(0,patch.startOffset)+patch.after+after.slice(patch.endOffset);WebVideoProject.parse(after);return {path:model.path,before:model.source,after,patches,changed:patches.length,appended,operation:{type:'batchFilter'}};}
 return {extract,sanitize,nameFor,rows,plan};
})();
function WebVideoBatchFilterPanel(){
 const R=reactExports,h=R.createElement,P=WebVideoProject,F=WebVideoFilters,model=WebVideoPlus.state().model,[allowAnimations,setAllowAnimations]=R.useState(false),items=R.useMemo(()=>F.rows(model,allowAnimations),[model,allowAnimations]),[library,setLibrary]=R.useState({presets:[],saved:[]}),[background,setBackground]=R.useState({choice:'none',name:'',code:''}),[figure,setFigure]=R.useState({choice:'none',name:'',code:''}),[saveTogether,setSaveTogether]=R.useState(true),[busy,setBusy]=R.useState(false),[message,setMessage]=R.useState('');
 const selection=useWebVideoInlineSelection(items,(model?.path||'')+'\n'+(model?.source||''),busy),manual=background.choice==='manual'||figure.choice==='manual';
 R.useEffect(()=>{let live=true;P.service('/api/filters').then(data=>{if(live){setLibrary(data);window.WebVideoFilterLibrary?.accept(data);}}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;};},[]);
 function resolve(config){if(config.choice==='none')return null;if(config.choice==='manual'){const effects=F.extract(config.code);return {name:config.name.trim()||F.nameFor(effects),effects};}const split=config.choice.indexOf(':'),kind=config.choice.slice(0,split),id=config.choice.slice(split+1),entry=(kind==='preset'?library.presets:library.saved).find((item,i)=>String(item.id??i)===id);if(!entry)throw Error('所选滤镜已不存在，请重新选择。');return {name:entry.name,effects:F.sanitize(entry.effects)};}
 async function save(config){setBusy(true);try{const value=resolve(config);if(!value)throw Error('请填写滤镜。');const data=await P.service('/api/filters/save',value);setLibrary(data);window.WebVideoFilterLibrary?.accept(data);setMessage('已保存“'+value.name+'”。');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function apply(){if(busy)return;selection.stop();setBusy(true);try{if(!model||WebVideoPlus.state().model?.path!==model.path||WebVideoPlus.state().model?.source!==model.source)throw Error('剧本已改变，请重新选择。');const bg=resolve(background),fig=resolve(figure),plan=F.plan(model,items,selection.selected,bg?.effects,fig?.effects);if(!plan.changed){setMessage('请为选中的组件选择需要添加的滤镜。');return;}await P.commit(plan,'批量滤镜');selection.setSelected(new Set());let saveError='';if(saveTogether){for(const [config,value]of [[background,bg],[figure,fig]])if(config.choice==='manual'&&value){try{const data=await P.service('/api/filters/save',value);setLibrary(data);window.WebVideoFilterLibrary?.accept(data);}catch(e){saveError+=' 保存滤镜失败：'+e.message;}}}setMessage('已在 '+plan.changed+' 个组件后添加 '+plan.appended+' 条滤镜语句，原文已自动备份。'+saveError);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function picker(label,config,setConfig){const type=label==='背景滤镜'?'background':'figure',entries=[{value:'none',name:'不添加'},{value:'manual',name:'手动输入'},...webVideoFilterOptions(library,type)];return h('section',{className:'wvp-filter-picker'},h('strong',null,label),h(WebVideoLibraryPicker,{label,value:config.choice,disabled:busy,entries,onChange:value=>setConfig({...config,choice:value})}),config.choice==='manual'&&h(R.Fragment,null,h('input',{'aria-label':label+'名字',value:config.name,disabled:busy,placeholder:'请输入滤镜名称',onChange:e=>setConfig({...config,name:e.target.value})}),h('textarea',{'aria-label':label+'代码',rows:3,value:config.code,disabled:busy,placeholder:'粘贴一行或多行 WebGAL 效果代码',onChange:e=>setConfig({...config,code:e.target.value})}),h('button',{type:'button',disabled:busy,onClick:()=>save(config)},'保存')));}

 const duplicateSelected=items.some(item=>item.existing&&selection.selected.has(item.row.id));
 const eligible=items.filter(item=>item.eligible),allSelected=eligible.length>0&&eligible.every(item=>selection.selected.has(item.row.id)),targetName=target=>target==='bg-main'?'背景':window.WebVideoCharacterMap?.names()?.[target?.toLowerCase()]||window.WebVideoNavigationMetadata.positions[target?.replace(/^fig-/,'')]||target;
 return h('div',{className:'wvp-filter-panel'},h('div',{className:'wvp-filter-pickers'},picker('背景滤镜',background,setBackground),picker('人物滤镜',figure,setFigure)),h('div',{className:'wvp-expression-actions'},h('label',{className:'wvp-filter-allow-animation'},h('input',{type:'checkbox',checked:allowAnimations,disabled:busy,onChange:e=>{const value=e.target.checked;selection.stop();setAllowAnimations(value);if(!value)selection.setSelected(old=>new Set(items.filter(item=>!item.isAnimation&&old.has(item.row.id)).map(item=>item.row.id)));}}),'允许选择动画'),h('button',{type:'button',disabled:busy||!eligible.length,onClick:()=>selection.setSelected(allSelected?new Set():new Set(eligible.map(item=>item.row.id)))},allSelected?'取消全选':'全选'),h('button',{type:'button',disabled:busy||!eligible.length,onClick:()=>selection.setSelected(new Set(eligible.filter(item=>!selection.selected.has(item.row.id)).map(item=>item.row.id)))},'反选'),h('span',null,'已选择 '+selection.selected.size+' 项')),duplicateSelected&&h('p',{className:'wvp-expression-warning',role:'alert'},'有些行正在添加第二个滤镜/效果，请检查是否选择重复'),h('div',{className:'wvp-expression-list',ref:selection.list,role:'listbox','aria-label':'选择批量滤镜组件','aria-multiselectable':true,onPointerMove:selection.move,onPointerUp:selection.stop,onPointerCancel:selection.stop,onLostPointerCapture:selection.stop},...items.map((item,index)=>h('div',{key:item.row.id,'data-filter-row':index,role:'option','aria-selected':selection.selected.has(item.row.id),'aria-disabled':!item.eligible,tabIndex:item.eligible?0:-1,className:'wvp-expression-row'+(item.eligible?'':' disabled')+(selection.selected.has(item.row.id)?' selected':''),onPointerDown:e=>selection.down(index,e),onKeyDown:e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();selection.choose(index,e);}},title:item.eligible?item.row.title:item.reason},h('span',{className:'wvp-expression-check'},selection.selected.has(item.row.id)?'✓':''),h('span',{className:'wvp-expression-line'},item.row.startLine),h('span',{className:'wvp-expression-text'},item.row.title),h('span',{className:'wvp-expression-reason wvp-filter-target'+(item.departure?' wvp-filter-inapplicable':'')},item.eligible?targetName(item.target):item.reason),!item.departure&&item.existing&&h('span',{className:'wvp-filter-existing',title:item.details||item.summary},item.summary)))),manual&&h('label',{className:'wvp-filter-save-together'},h('input',{type:'checkbox',checked:saveTogether,disabled:busy,onChange:e=>setSaveTogether(e.target.checked)}),'同时保存此滤镜'),message&&h('p',{className:'wvp-expression-message',role:'status'},message),h('footer',null,h('span',null,'拖动连续选择 · Ctrl 多选 · Shift 选择头尾'),h('button',{type:'button',className:'primary',disabled:busy||!selection.selected.size,onClick:apply},busy?'处理中…':'确认')));
}
WebVideoTools.register('filter','批量滤镜',WebVideoBatchFilterPanel);
