const WebVideoBatchNext=(()=>{
 const types=[['say','普通对话'],['changeBg','切换背景'],['changeFigure','切换立绘'],['video','播放视频'],['playEffect','效果声音'],['setAnimation','调用动画'],['setComplexAnimation','复杂动画'],['setTransform','单段动画'],['setTempAnimation','多段动画'],['setTransition','进出场动画'],['pixi','使用特效'],['pixiInit','清除特效'],['miniAvatar','角落头像'],['setTextbox','文本显示'],['filmMode','电影模式']];
 const canonical=command=>({playVideo:'video',pixiPerform:'pixi'})[command]||command;
 const supported=new Set(types.map(([command])=>command));
 // Match the native parser's unescaped statement terminator, before any inline comment.
 function codeEnd(source){const match=/(?<!\\);/.exec(source);return match?match.index:source.trimEnd().length;}
 function hasNext(row){return /(?:^| )-next(?:\s*=|\s|$)/.test(row.source.slice(0,codeEnd(row.source)));}
 function rows(model,enabled){return (model?.statements||[]).filter(row=>supported.has(canonical(row.command))||row.command==='intro').map(row=>{const command=canonical(row.command),existing=hasNext(row),available=supported.has(command),eligible=available&&!existing&&enabled.has(command);return {row,command,existing,available,eligible,label:types.find(([key])=>key===command)?.[1]||'全屏文字',reason:!available?'不支持 -next，仅作提示':existing?'已有 -next 参数':!enabled.has(command)?'未勾选此类型':''};});}
 function plan(model,items,selected){const patches=[];for(const item of items){const row=item.row;if(!item.eligible||!selected.has(row.id)||hasNext(row))continue;const end=codeEnd(row.source),at=row.source.slice(0,end).trimEnd().length,terminated=row.source[end]===';',after=row.source.slice(0,at)+' -next'+(terminated?'':';')+row.source.slice(at);patches.push({startOffset:row.startOffset,endOffset:row.endOffset,before:row.source,after,line:row.startLine});}
  patches.sort((a,b)=>a.startOffset-b.startOffset);for(let i=1;i<patches.length;i++)if(patches[i].startOffset<patches[i-1].endOffset)throw Error('语句范围发生重叠，未修改剧本。');let after=model.source;for(const patch of [...patches].reverse())after=after.slice(0,patch.startOffset)+patch.after+after.slice(patch.endOffset);WebVideoProject.parse(after);return {path:model.path,before:model.source,after,patches,changed:patches.length,operation:{type:'batchNext'}};
 }
 return {types,rows,plan};
})();
function WebVideoBatchNextPanel(){
 const R=reactExports,h=R.createElement,N=WebVideoBatchNext,model=WebVideoPlus.state().model,revision=(model?.path||'')+'\n'+(model?.source||''),[enabled,setEnabled]=R.useState(()=>new Set(N.types.filter(([key])=>key!=='say').map(([key])=>key))),[busy,setBusy]=R.useState(false),[message,setMessage]=R.useState(''),items=R.useMemo(()=>N.rows(model,enabled),[model,enabled]);
 const selection=useWebVideoInlineSelection(items,revision,busy),eligible=items.filter(item=>item.eligible),selected=eligible.filter(item=>selection.selected.has(item.row.id)),allSelected=eligible.length>0&&selected.length===eligible.length;
 R.useEffect(()=>{selection.setSelected(new Set(items.filter(item=>item.eligible).map(item=>item.row.id)));},[revision]);
 function changeType(command,value){selection.stop();const next=new Set(enabled);value?next.add(command):next.delete(command);const nextItems=N.rows(model,next);selection.setSelected(new Set(nextItems.filter(item=>item.eligible&&(!eligible.length||allSelected||selection.selected.has(item.row.id))).map(item=>item.row.id)));setEnabled(next);}
 function stop(){selection.stop();}
 async function apply(){if(busy)return;selection.stop();setBusy(true);setMessage('');try{if(!model||WebVideoPlus.state().model?.path!==model.path||WebVideoPlus.state().model?.source!==model.source)throw Error('剧本已改变，请重新选择。');const plan=N.plan(model,items,selection.selected);if(!plan.changed){setMessage('没有需要追加 -next 的语句。');return;}await WebVideoProject.commit(plan,'批量加-next');setMessage('已为 '+plan.changed+' 条语句添加 -next，原文已自动备份。');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return h('div',{className:'wvp-expression-panel wvp-next-panel'},h('fieldset',{className:'wvp-next-types',disabled:busy},h('legend',null,'语句类型'),...N.types.map(([command,label])=>h('label',{key:command},h('input',{type:'checkbox',checked:enabled.has(command),onChange:e=>changeType(command,e.target.checked)}),label))),h('div',{className:'wvp-expression-actions'},h('button',{type:'button',disabled:busy||!eligible.length,onClick:()=>{const all=!allSelected;selection.setSelected(all?new Set(eligible.map(item=>item.row.id)):new Set());}},allSelected?'取消全选':'全选'),h('button',{type:'button',disabled:busy||!eligible.length,onClick:()=>{const ids=new Set(eligible.filter(item=>!selection.selected.has(item.row.id)).map(item=>item.row.id));selection.setSelected(ids);}},'反选'),h('span',null,'已选择 '+selected.length+' 项')),h('div',{className:'wvp-expression-list',ref:selection.list,role:'listbox','aria-label':'选择追加 -next 的语句','aria-multiselectable':true,onPointerMove:selection.move,onPointerUp:stop,onPointerCancel:stop,onLostPointerCapture:stop},...items.map((item,index)=>h('div',{key:item.row.id,'data-filter-row':index,role:'option','aria-selected':item.eligible&&selection.selected.has(item.row.id),'aria-disabled':!item.eligible,tabIndex:item.eligible?0:-1,className:'wvp-expression-row'+(item.eligible?'':' disabled')+(item.eligible&&selection.selected.has(item.row.id)?' selected':''),title:item.row.source.trim(),onPointerDown:e=>selection.down(index,e),onKeyDown:e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();selection.choose(index,e);}}},h('span',{className:'wvp-expression-check'},item.eligible&&selection.selected.has(item.row.id)?'✓':''),h('span',{className:'wvp-expression-line'},item.row.startLine),h('span',{className:'wvp-next-type'},item.label),h('span',{className:'wvp-expression-text'},item.row.command==='say'?[item.row.speaker,item.row.content].filter(Boolean).join('：'):item.row.content||'关闭'),item.reason&&h('span',{className:'wvp-expression-reason'},item.reason)))),message&&h('p',{className:'wvp-expression-message',role:'status'},message),h('footer',null,h('span',null,'拖动连续选择 · Ctrl 多选 · Shift 选择头尾'),h('button',{type:'button',className:'primary',disabled:busy||!selected.length,onClick:apply},busy?'处理中…':'确认')));
}
WebVideoTools.register('batchNext','批量加-next',WebVideoBatchNextPanel);
