const WebVideoCharacterMapEnabled=__WEBVIDEO_CHARACTER_MAP_ENABLED__;
/* Shared character aliases. The editable JSON lives outside game projects. */
const WebVideoCharacterMap=(()=>{
 const listeners=new Set();let state={opened:false,data:null,error:'',busy:false},ticket=0;
 const emit=()=>listeners.forEach(fn=>fn());
 async function request(route='/api/character-map',body){const d=await(await fetch('/assets/video-export-service.json',{cache:'no-store'})).json(),u=new URL(d.baseUrl);if(u.protocol!=='http:'||!['localhost','127.0.0.1'].includes(u.hostname))throw Error('映射表服务地址无效');const response=await fetch(u.origin+route,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+d.token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw Error(data.error||'映射表操作失败');return data;}
 function accept(data){state={...state,data,error:''};const model=window.WebVideoPlus?.state().model;if(model)window.WebVideoPlus.publish(model.path,model.source,true);emit();}
 return {state:()=>state,names:()=>state.data?.idToName||(WebVideoCharacterMapEnabled?{}:window.WebVideoNavigationMetadata?.characterNames||{}),subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},open(){state={...state,opened:true};emit();},close(){state={...state,opened:false};emit();},async load(){const current=++ticket;try{const data=await request();if(current!==ticket)return;accept(data);return data;}catch(e){if(current===ticket){state={...state,error:e.message};emit();}throw e;}},async save(rows,hash){++ticket;const data=await request('/api/character-map',{rows,expectedHash:hash});accept(data);return data;},async reset(hash){++ticket;const data=await request('/api/character-map/reset',{expectedHash:hash});accept(data);return data;},exitTerre:()=>request('/api/character-map/exit-terre',{}),openFolder:()=>request('/api/character-map/open-folder',{}),emit};
})();
window.WebVideoCharacterMap=WebVideoCharacterMap;
function WebVideoCharacterMapButton(){const R=reactExports,h=R.createElement,M=WebVideoCharacterMap,[,refresh]=R.useReducer(n=>n+1,0);R.useEffect(()=>M.subscribe(refresh),[]);return h(Button,{onClick:()=>M.open(),appearance:'subtle'},'调整id对应表',M.state().data?.fatal?'（需修复）':'');}
function WebVideoCharacterMapHost(){
 const R=reactExports,h=R.createElement,M=WebVideoCharacterMap,[,refresh]=R.useReducer(n=>n+1,0),[rows,setRows]=R.useState([]),[hash,setHash]=R.useState(''),[dirty,setDirty]=R.useState(false),[busy,setBusy]=R.useState(false),[message,setMessage]=R.useState('');const dark=useEditorStore.use.isDarkMode();
 const state=M.state();
 const adopt=data=>{if(!data)return;setRows((data.rows||[]).map(row=>({...row})));setHash(data.hash||'');setDirty(false);};
 R.useEffect(()=>M.subscribe(refresh),[]);
 R.useEffect(()=>{if(!WebVideoCharacterMapEnabled)return;M.load().then(data=>{if(data?.fatal)M.open();}).catch(()=>{});},[]);
 R.useEffect(()=>{if(state.opened){setMessage('');M.load().then(adopt).catch(e=>setMessage(e.message));}},[state.opened]);
 R.useEffect(()=>{const focus=()=>{if(WebVideoCharacterMapEnabled&&!dirty&&!busy)M.load().then(data=>{if(state.opened)adopt(data);}).catch(()=>{});};window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[dirty,busy,state.opened]);
 const warnings=[];const names=new Map(),ids=new Map();rows.forEach((row,i)=>{for(const alias of row.names.split(';').map(n=>n.trim()).filter(Boolean)){if(names.has(alias.toLowerCase()))warnings.push('名字“'+alias+'”重复：第 '+names.get(alias.toLowerCase())+'、'+(i+1)+' 行；采用第 '+(i+1)+' 行。');names.set(alias.toLowerCase(),i+1);}const id=row.id.trim();if(id){if(ids.has(id.toLowerCase()))warnings.push('ID“'+id+'”重复：第 '+ids.get(id.toLowerCase())+'、'+(i+1)+' 行；采用第 '+(i+1)+' 行。');ids.set(id.toLowerCase(),i+1);}});
 const update=(index,key,value)=>{setRows(old=>old.map((row,i)=>i===index?{...row,[key]:value}:row));setDirty(true);setMessage('');};
 async function run(action){setBusy(true);try{await action();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const close=()=>{if(busy)return;if(dirty&&!window.confirm('有尚未保存的修改，确定放弃并关闭吗？'))return;M.close();};
 return h(Dialog,{open:state.opened,onOpenChange:(_,data)=>{if(!data.open)close();}},h(DialogSurface,{className:'wvp-character-map','data-theme':dark?'dark':'light','aria-label':'调整id对应表'},h('header',null,h('h2',null,'调整id对应表'),h(Button,{onClick:close,disabled:busy},'关闭')),h('p',null,'所有游戏共用。多个名字用 ; 分隔，显示标注优先使用不带姓氏的名字。匹配不区分大小写；重复时，下方行覆盖上方行。'),h('div',{className:'wvp-map-actions'},h(Button,{disabled:busy,onClick:()=>run(async()=>{await M.openFolder();setMessage('文件夹已打开。修改 characters.json 后，返回此处点击“重新读取”。');})},'打开 JSON 文件夹'),h(Button,{disabled:busy,onClick:()=>{if(dirty&&!window.confirm('重新读取会放弃尚未保存的修改，继续吗？'))return;run(async()=>{adopt(await M.load());setMessage('已重新读取。');});}},'重新读取')),
 (state.error||message)&&h('p',{role:'status',className:'wvp-map-message'},message||state.error),state.data?.fatal?h('div',{role:'alert',className:'wvp-map-fatal'},h('strong',null,'映射表格式有误，未采用其中的映射。'),h('p',null,state.data.message),h('p',null,'不会自动恢复或覆盖文件。你可以恢复出厂表，或退出 Terre 后手动修改 JSON。'),h(Button,{disabled:busy,onClick:()=>{if(!window.confirm('恢复内置出厂表？当前文件会另存为备份。'))return;run(async()=>{adopt(await M.reset(state.data.hash));setMessage('已恢复出厂表，旧文件已另存。');});}},'恢复出厂设置'),h(Button,{disabled:busy,onClick:()=>run(async()=>{await window.WebVideoPlus?.flushEditor?.();await M.openFolder();await M.exitTerre();setMessage('已请求退出 Terre。请修改 characters.json 后重新启动。');})},'退出 Terre，手动修改')):state.data&&h(R.Fragment,null,h('div',{className:'wvp-map-table-wrap'},h('table',null,h('thead',null,h('tr',null,h('th',null,'行'),h('th',null,'角色名字（用 ; 分隔）'),h('th',null,'ID'),h('th',null,''))),h('tbody',null,...rows.map((row,i)=>h('tr',{key:i},h('td',null,i+1),h('td',null,h('input',{'aria-label':'第 '+(i+1)+' 行名字',value:row.names,disabled:busy,placeholder:'户山香澄;香澄',onChange:e=>update(i,'names',e.target.value)})),h('td',null,h('input',{'aria-label':'第 '+(i+1)+' 行 ID',value:row.id,disabled:busy,placeholder:'ksm',onChange:e=>update(i,'id',e.target.value)})),h('td',null,h(Button,{'aria-label':'删除第 '+(i+1)+' 行',disabled:busy,onClick:()=>{setRows(old=>old.filter((_,n)=>n!==i));setDirty(true);}},'删除'))))))),h(Button,{disabled:busy,onClick:()=>{setRows(old=>[...old,{names:'',id:''}]);setDirty(true);}},'在末尾增加一行'),warnings.length>0&&h('div',{className:'wvp-map-warnings',role:'status'},h('strong',null,'发现重复，仍然可以保存'),h('ul',null,...warnings.map((text,i)=>h('li',{key:i},text)))),h('footer',null,h('span',null,dirty?'有未保存修改':'已保存'),h(Button,{appearance:'primary',disabled:busy||!dirty,onClick:()=>run(async()=>{const data=await M.save(rows,hash);adopt(data);setMessage(data.warnings.length?'已保存；重复项按下方行覆盖。':'已保存，导航标注已更新。');})},busy?'保存中…':'保存')))));
}
