let webVideoCheckCache=null;
const webVideoCheckDismissals=new Map();
function webVideoInspect(model,project){if(webVideoCheckCache?.model!==model||webVideoCheckCache?.project!==project)webVideoCheckCache={model,project,result:window.WebVideoProjectCore.inspect(model,project)};const result=webVideoCheckCache.result,dismissed=webVideoCheckDismissals.get(model.path);return {...result,issues:result.issues.filter(issue=>!dismissed?.types.has(issue.code)&&!dismissed?.rows.some(item=>item.code===issue.code&&window.WebVideoProjectCore.resolveAnchor(model,item.anchor)?.id===issue.rowId))};}
const WebVideoCheckActions={
 dismissIssue(model,issue,all){if(!model)return;let state=webVideoCheckDismissals.get(model.path);if(!state){state={types:new Set(),rows:[]};webVideoCheckDismissals.set(model.path,state);}if(all)state.types.add(issue.code);else{const row=model.statements.find(row=>row.id===issue.rowId);if(row)state.rows.push({code:issue.code,anchor:window.WebVideoProjectCore.anchor(model,row)});}WebVideoPlus.changed();},
 dismissMarker(id,all){const path=WebVideoPlus.state().model?.path;if(all)WebVideoPlus.clearReviewMarks?.();return WebVideoProject.update(p=>{p.markers=p.markers.filter(mark=>all?mark.path!==path:mark.id!==id);});},
 dismissReview(row,all){if(all){WebVideoPlus.clearReviewMarks?.();return this.dismissMarker('',true);}WebVideoPlus.acknowledgeReview(row);}
};
window.WebVideoCheckActions=WebVideoCheckActions;
function WebVideoChecksPanel(){
 const R=reactExports,h=R.createElement,P=WebVideoProject,C=window.WebVideoProjectCore,model=WebVideoPlus.state().model,project=P.state().project,[status,setStatus]=R.useState('待调整'),[message,setMessage]=R.useState(''),[busy,setBusy]=R.useState(false),items=R.useMemo(()=>(model?.rows||[]).map(row=>({row,eligible:true})),[model]);
 const select=useWebVideoInlineSelection(items,(model?.path||'')+'\n'+(model?.source||''),busy);if(!model)return h('p',null,'请先打开一个剧本。');const result=webVideoInspect(model,project),all=items.length>0&&items.every(item=>select.selected.has(item.row.id));
 async function mark(){setBusy(true);try{const marks=items.filter(item=>select.selected.has(item.row.id)).map(item=>C.anchor(model,item.row,status));await P.update(p=>{p.markers=p.markers.filter(existing=>existing.path!==model.path||!select.selected.has(C.resolveAnchor(model,existing)?.id));p.markers.push(...marks);});select.setSelected(new Set());setMessage('制作标记已添加，可在时间线右键取消。');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function section(row){const next=model.rows.find(item=>item.command==='changeBg'&&item.startLine>row.startLine),ids=items.filter(item=>item.row.startLine>=row.startLine&&(!next||item.row.startLine<next.startLine)).map(item=>item.row.id);select.setSelected(old=>new Set([...old,...ids]));}
 return h('div',{className:'wvp-checks-panel'},h('label',null,h('input',{type:'checkbox',checked:project.showChecks!==false,onChange:e=>P.update(p=>{p.showChecks=e.target.checked;})}),'在时间线中显示'),h('div',{className:'wvp-check-list'},result.issues.length?result.issues.map((issue,i)=>h('div',{className:'wvp-check-item',key:i},h('span',null,'第 '+issue.line+' 行 · '+issue.message),h('button',{onClick:()=>WebVideoPlus.jump({startLine:issue.line})},'定位'))):h('p',null,'目前没有检查提示。')),h('h3',null,'制作标记'),h('div',{className:'wvp-expression-actions'},h('select',{'aria-label':'制作标记类型',value:status,onChange:e=>setStatus(e.target.value)},...['待调整','待配音','待核对','已完成'].map(value=>h('option',{key:value,value},value))),h('button',{disabled:busy,onClick:()=>select.setSelected(all?new Set():new Set(items.map(item=>item.row.id)))},all?'取消全选':'全选'),h('button',{disabled:busy,onClick:()=>select.setSelected(new Set(items.filter(item=>!select.selected.has(item.row.id)).map(item=>item.row.id)))},'反选')),h('div',{className:'wvp-expression-list wvp-marker-selection',ref:select.list,role:'listbox','aria-multiselectable':true,onPointerMove:select.move,onPointerUp:select.stop,onPointerCancel:select.stop,onLostPointerCapture:select.stop},...items.map((item,index)=>h('div',{key:item.row.id,'data-filter-row':index,role:'option','aria-selected':select.selected.has(item.row.id),tabIndex:0,className:'wvp-expression-row'+(select.selected.has(item.row.id)?' selected':''),onPointerDown:e=>select.down(index,e),onKeyDown:e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();select.choose(index,e);}}},h('span',{className:'wvp-expression-check'},select.selected.has(item.row.id)?'✓':''),h('span',{className:'wvp-expression-line'},item.row.startLine),h('span',{className:'wvp-expression-text'},(item.row.speaker?item.row.speaker+'：':'')+item.row.title),item.row.command==='changeBg'&&h('button',{onPointerDown:e=>e.stopPropagation(),onClick:e=>{e.stopPropagation();section(item.row);}},'本节')))),h('p',{className:'wvp-help'},'拖拽连续选择，Ctrl 多选，Shift 选择头尾。'),message&&h('p',{role:'status'},message),h('button',{className:'primary',disabled:busy||!select.selected.size,onClick:mark},'应用标记'));
}
WebVideoTools.register('checks','检查与标记',WebVideoChecksPanel);
WebVideoTools.registerDecorator('checks',(model,rows,project)=>{const result=webVideoInspect(model,project),visible=new Set(rows.map(row=>row.id)),marks=new Map();for(const item of result.resolvedMarkers){const id=item.row&&(visible.has(item.row.id)?item.row.id:item.row.navigationOwnerId);if(id){if(!marks.has(id))marks.set(id,[]);marks.get(id).push(item.mark);}}return rows.map(row=>({...row,checkIssues:project.showChecks!==false?result.issues.filter(issue=>issue.rowId===row.id):[],productionMarks:marks.get(row.id)||[]}));});
