function WebVideoCuePanel({kind}){
 const R=reactExports,F=WebVideoForm,h=F.h,P=WebVideoProject,[selection,setSelection]=R.useState(null),[target,setTarget]=R.useState('speaker'),[value,setValue]=R.useState(''),[effect,setEffect]=R.useState({brightness:1,contrast:1,saturation:1,blur:0}),[duration,setDuration]=R.useState(0),[plan,setPlan]=R.useState(null),[busy,setBusy]=R.useState(false),[message,setMessage]=R.useState('');
 const title={expression:'添加表情',motion:'添加动作',filter:'应用滤镜'}[kind];
 const change=setter=>event=>{setter(event.target.value);setPlan(null);};
 async function choose(){try{const selected=await WebVideoTools.select('set');if(selected){setSelection(selected);setPlan(null);}}catch(error){setMessage(error.message);}}
 function preview(){try{const next=P.plan(selection,{type:'figureCue',kind,target,value,effect,duration:Number(duration)*1000});if(!next.changed)throw Error('没有选中对白，请选择要添加演出的对白。');setPlan(next);setMessage('将在以下对白开始前添加演出，确认后应用。');}catch(error){setMessage(error.message);setPlan(null);}}
 async function apply(){setBusy(true);try{await P.commit(plan,title);setMessage('已修改 '+plan.changed+' 处，并保存操作前备份。');setSelection(null);setPlan(null);}catch(error){setMessage(error.message);}finally{setBusy(false);}}
 return h('div',null,h('div',{className:'wvp-tool-grid'},F.field('修改谁',h('select',{value:target,onChange:change(setTarget)},...([['speaker','说话的人（自动匹配）'],['left','左侧人物'],['center','中间人物'],['right','右侧人物'],...(kind==='filter'?[['background','背景']]:[])]).map(([key,label])=>h('option',{key,value:key},label)))),kind!=='filter'&&F.field(kind==='expression'?'表情名称':'动作名称',h('input',{value,onChange:change(setValue),placeholder:kind==='expression'?'填写模型已有的表情名称':'填写模型已有的动作名称'}))),
 kind==='filter'&&h('div',{className:'wvp-tool-grid'},...Object.entries({brightness:'亮度',contrast:'对比度',saturation:'饱和度',blur:'模糊'}).map(([key,label])=>F.field(label,h('input',{type:'number',min:0,max:key==='blur'?20:5,step:.1,value:effect[key],onChange:e=>{setEffect({...effect,[key]:Number(e.target.value)});setPlan(null);}}))),F.field('过渡时间（秒）',h('input',{type:'number',min:0,max:60,step:.1,value:duration,onChange:change(setDuration)}))),
 h('p',{className:'wvp-help'},kind==='filter'?'亮度、对比度、饱和度为 1 时保持原样；模糊为 0 时关闭。':'每句对白前添加同一个表情或动作，之后可以在原编辑器里逐句调整。'),F.selection(selection,choose),
 plan&&h('section',{className:'wvp-change-preview wvp-cue-preview'},h('strong',null,'将修改 '+plan.changed+' 处'),h('ul',null,...plan.patches.map(p=>{const row=WebVideoPlus.state().model.rows.find(r=>r.startLine===p.line);return h('li',{key:p.line},'第 '+p.line+' 行 · '+(row?.displaySpeaker||row?.speaker||'旁白')+'：'+(row?.content||'').slice(0,60)+' → '+title+(kind==='filter'?'':'「'+value+'」'));})),h('details',null,h('summary',null,'查看生成的语句'),h('pre',null,plan.patches.map(p=>p.after.trim()).join('\n')))),F.notice(message),h('div',{className:'wvp-tool-actions'},F.button('预览修改',preview,{disabled:busy||!selection}),F.button('确认应用',apply,{className:'primary',disabled:busy||!plan?.changed||WebVideoPlus.state().model?.source!==plan.before})));
}
WebVideoTools.register('filter','应用滤镜',()=>reactExports.createElement(WebVideoCuePanel,{kind:'filter'}));
WebVideoTools.register('replaceText','替换文字',()=>reactExports.createElement(WebVideoBatchPanel,{initialMode:'text',fixedMode:true}));
WebVideoTools.register('templates','演出模板',()=>reactExports.createElement(WebVideoBatchPanel,{initialMode:'insert',fixedMode:true,templateOnly:true}));
