/* Only numerical effect payloads survive extraction; commands and targets never enter the library. */
const WebVideoFilters=(()=>{
 const M=window.WebVideoNavigationMetadata,extras={shockwaveFilter:'冲击波滤镜',radiusAlphaFilter:'径向透明度滤镜'},fields={...M.fields,...Object.fromEntries(Object.entries(extras).map(([key,label])=>[key,{path:key,label}]))};
 const get=(value,path)=>path.split('.').reduce((v,key)=>v?.[key],value),set=(o,path,value)=>{const parts=path.split('.');if(parts.length===1)o[parts[0]]=value;else(o[parts[0]]??={})[parts[1]]=value;};
 function clean(effect){if(!effect||Array.isArray(effect)||typeof effect!=='object')throw Error('效果片段必须是 JSON 对象。');const output={};for(const [key,meta]of Object.entries(fields)){const value=get(effect,meta.path);if(value===undefined)continue;if(typeof value!=='number'||!Number.isFinite(value))throw Error(meta.label+'必须是有效数字。');set(output,meta.path,value);}if(!Object.keys(output).length)throw Error('没有找到可保存的效果参数。');return output;}
 function sanitize(effects){if(!Array.isArray(effects)||!effects.length||effects.length>100)throw Error('请输入 1 到 100 段效果。');return effects.map(clean);}
 function extract(code){const text=code.trim();if(!text)throw Error('请填写滤镜代码。');if(text.startsWith('{')||text.startsWith('[')){const value=JSON.parse(text);return sanitize(Array.isArray(value)?value:[value]);}const parsed=WebVideoProject.parse(text),effects=[];for(const statement of parsed.sentenceList||[]){if(statement.isLineBreakHolder)continue;const command=commandType[statement.command]||statement.commandRaw,args=Object.fromEntries((statement.args||[]).map(a=>[a.key,a.value]));if(command==='comment')continue;let value;if(command==='setTransform'||command==='setTempAnimation')value=JSON.parse(statement.content);else if(args.transform!==undefined)value=typeof args.transform==='object'?args.transform:JSON.parse(args.transform);else throw Error('第 '+(statement.startLine+1)+' 行没有明确的效果片段，请使用 setTransform 或带 transform 的语句。');effects.push(...(Array.isArray(value)?value:[value]));}return sanitize(effects);}
 function nameFor(effects){return effects.map(effect=>Object.entries(fields).filter(([,meta])=>get(effect,meta.path)!==undefined).map(([key,meta])=>{const prefix=key.startsWith('bloom')?'泛光':key.startsWith('bevel')?'倒角':'';return prefix+meta.label+'：'+get(effect,meta.path);}).join('、')).join('；');}
 function rows(model,allowAnimations=false){
  const animations=new Set(['setAnimation','setComplexAnimation','setTransform','setTempAnimation','setTransition']),all=model?.rows||[],statements=model?.statements||[],byId=new Map(all.map(row=>[row.id,row]));
  return all.filter(row=>row.command==='changeBg'||row.command==='changeFigure'&&row.main||animations.has(row.command)&&!row.parentId).map(row=>{
   const target=row.command==='changeBg'?'bg-main':row.target,parts=[...(row.embeddedEffects||[])],related=new Map();if(animations.has(row.command))related.set(row.id,row);
   for(const child of all)if(child.parentId===row.id&&animations.has(child.command))related.set(child.id,child);
   for(let i=statements.findIndex(item=>item.id===row.id)+1;i>0&&i<statements.length;i++){const next=statements[i];if(next.command==='comment')continue;if(!animations.has(next.command)||String(next.args.target??'')!==target)break;related.set(next.id,byId.get(next.id)||next);}
   for(const effect of related.values())parts.push(...(effect.parts?.length?effect.parts:[{title:effect.title||'效果',items:[]} ]));
   if(!parts.length&&row.args.transform){try{const value=typeof row.args.transform==='object'?row.args.transform:JSON.parse(row.args.transform);if(Object.keys(value).length)parts.push({title:'已有变换效果',items:[]});}catch{parts.push({title:'效果参数无法解析',items:[]});}}
   const names=[...new Set(parts.map(part=>part.filterName).filter(Boolean))],labels=[...new Set(parts.filter(part=>!part.filterName).map(part=>part.title).filter(Boolean))],existing=parts.length>0,summary=names.length?'滤镜：'+names.join(' · '):existing?'效果：'+labels.join(' · '):'',details=parts.map(part=>[part.title,...(part.items||[]),part.footer].filter(Boolean).join('，')).join('；');
   const departure=row.command==='changeFigure'&&(!row.content||row.content==='none'||row.args.clear===true);return {row,target,departure,isAnimation:animations.has(row.command),background:target==='bg-main',eligible:!departure&&(allowAnimations||!animations.has(row.command))&&typeof target==='string'&&!!target&&!/[\s;|]/.test(target),reason:departure?'不适用，仅作提示':!allowAnimations&&animations.has(row.command)?'需允许选择动画':target?'目标参数无效':'未指定目标',existing,summary,details};
  });
 }
 function plan(model,items,selected,background,figure){const eol=model.source.includes('\r\n')?'\r\n':'\n',patches=[];let appended=0;for(const item of items){if(!item.eligible||!selected.has(item.row.id))continue;const effects=item.background?background:figure;if(!effects?.length)continue;const lines=effects.map(effect=>'setTransform:'+JSON.stringify(effect)+' -target='+item.target+' -duration=0 -next;');const at=item.row.endOffset,prefix=at>0&&!/[\r\n]$/.test(model.source.slice(0,at))?eol:'';patches.push({startOffset:at,endOffset:at,before:'',after:prefix+lines.join(eol)+eol,line:item.row.startLine});appended+=lines.length;}let after=model.source;for(const patch of [...patches].reverse())after=after.slice(0,patch.startOffset)+patch.after+after.slice(patch.endOffset);WebVideoProject.parse(after);return {path:model.path,before:model.source,after,patches,changed:patches.length,appended,operation:{type:'batchFilter'}};}
 return {extract,sanitize,nameFor,rows,plan};
})();
