function webVideoSingleLineHintText(){return window.WebVideoSingleLineHint?.createText?.()||(()=>{const id='__wvp_hint_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);return 'choose:时间 / 地点:'+id+' -defaultChoose=1 -wvpHint=1800;\nlabel:'+id+';';})();}
function WebVideoSingleLineHintTopbarButton(){const h=reactExports.createElement;return h(IconWithTextItemSmall,{icon:h('span',{'aria-hidden':true,style:{fontSize:'18px',lineHeight:1}},'—'),text:'单行提示',onClick:()=>addSentenceText(webVideoSingleLineHintText())});}
function WebVideoChangeSceneTopbarButton(){const h=reactExports.createElement,item=sentenceEditorConfig.find(entry=>entry.type===commandType.changeScene),label=item?.title?.()||'场景跳转';return h(IconWithTextItemSmall,{icon:h('span',{'aria-hidden':true,style:{fontSize:'17px',lineHeight:1}},'→'),text:label,onClick:()=>addSentenceText(item?.initialText?.()||'changeScene:start.txt;')});}
function WebVideoAddSentenceDialog(props){
 const R=reactExports,h=R.createElement,[query,setQuery]=R.useState(''),[gamePage,setGamePage]=R.useState(!!props.gameOnly),[presetPage,setPresetPage]=R.useState(false);
 R.useEffect(()=>{if(props.open){setQuery('');setGamePage(!!props.gameOnly);setPresetPage(false);}},[props.open]);
 const c=commandType,groups=[
  ['常规演出',[c.say,c.changeBg,c.changeFigure,c.video,c.playEffect],false],
  ['舞台对象控制',[c.setAnimation,c.setComplexAnimation,c.setTransform,c.setTempAnimation,c.setTransition,c.pixi,c.pixiInit,c.intro,c.miniAvatar,c.setTextbox,c.filmMode],false],
  ['场景与分支',[c.callScene,c.changeScene,c.choose,c.label,c.jumpLabel,c.return],true],
  ['鉴赏',[c.unlockCg,c.unlockBgm],true],
  ['游戏控制',[c.bgm,c.getUserInput,c.setVar,c.showVars,c.wait,c.applyStyle,c.callSteam,c.end],true]
 ];
 const assigned=new Set(groups.flatMap(g=>g[1]));groups.push(['其他语句',sentenceEditorConfig.filter(item=>item.type!==c.comment&&!assigned.has(item.type)).map(item=>item.type),true]);
 const key=query.trim().toLowerCase();let visible=0;
 const sections=groups.map(([title,types,folded])=>{const entries=types.map(type=>sentenceEditorConfig.find(item=>item.type===type)).filter(Boolean).filter(item=>!key||[item.title(),item.descText(),item.initialText()].some(value=>String(value).toLowerCase().includes(key))),singleLine=title==='舞台对象控制'&&(!key||'单行提示 时间 地点 横行 自动继续 分支样式'.includes(key));if((!entries.length&&!singleLine)||(!key&&__WEBVIDEO_MODULES__.includes('compactGameTools')&&folded!==gamePage))return null;visible+=entries.length+(singleLine?1:0);const list=h('div',{className:'wvp-add-list'},title==='常规演出'&&__WEBVIDEO_MODULES__.includes('presetEffects')&&h('button',{type:'button',className:'wvp-add-command',onClick:()=>setPresetPage(true)},h('strong',null,'Video+预制效果')),singleLine&&h('button',{type:'button',className:'wvp-add-command',onClick:()=>{props.onChoose(webVideoSingleLineHintText());props.onOpenChange(false);}},h('span',{className:'wvp-add-icon','aria-hidden':true},'—'),h('span',{className:'wvp-add-copy'},h('strong',null,'单行提示'),h('span',null,'分支横条样式 · 默认 1.8 秒后自动继续'))),...entries.map(item=>h('button',{type:'button',key:item.type,className:'wvp-add-command',onClick:()=>{props.onChoose(item.initialText());props.onOpenChange(false);}},h('span',{className:'wvp-add-icon','aria-hidden':true},item.icon),h('span',{className:'wvp-add-copy'},h('strong',null,item.title()),h('span',null,item.descText())))));
 return h('section',{key:title,className:'wvp-add-section'},h('h3',null,title),list);
 });
 return h(Dialog,{open:props.open,onOpenChange:(_,data)=>props.onOpenChange(data.open)},h(DialogSurface,{className:'wvp-add-dialog','aria-label':props.titleText||'添加新语句'},h('div',{className:'wvp-add-body'},h('header',{className:'wvp-add-heading'},h('h2',null,gamePage?'游戏工具':props.titleText||'添加新语句'),h(DialogTrigger,{action:'close'},h(Button,{appearance:'subtle','aria-label':'关闭添加语句',icon:h(Dismiss24Regular)}))),h('p',{className:'wvp-add-hint'},gamePage?'场景与分支、鉴赏和游戏控制。': '选择需要添加的演出语句。'),h('input',{className:'wvp-add-search',type:'search','aria-label':'搜索语句',placeholder:'搜索语句名称、用途或命令…',value:query,onChange:e=>setQuery(e.target.value)}),!props.gameOnly&&!key&&__WEBVIDEO_MODULES__.includes('compactGameTools')&&h('button',{type:'button',className:'wvp-game-page-link',onClick:()=>setGamePage(!gamePage)},gamePage?'返回常用演出':'游戏工具（场景、鉴赏、游戏控制）'),h('div',{className:'wvp-add-content'},presetPage?h(R.Fragment,null,h('button',{type:'button',onClick:()=>setPresetPage(false)},'返回语句类型'),h(window.WebVideoPresetChooser,{insertLine:props.insertLine,onDone:()=>props.onOpenChange(false)})):h(R.Fragment,null,WebVideoCharacterMapEnabled&&gamePage&&(!key||'鉴赏功能'.includes(key))&&h('section',{className:'wvp-add-section'},h(GameConfig,{mode:'appreciation'})),...sections,!visible&&h('p',{className:'wvp-add-empty',role:'status'},'没有匹配的语句，试试“背景”“立绘”或“等待”。'))))));
}

function WebVideoGameTools(){const R=reactExports,h=R.createElement,[open,setOpen]=R.useState(false);return h(R.Fragment,null,h(TabItem,{title:'游戏工具'},h(WebVideoChangeSceneTopbarButton),h('button',{type:'button',className:'wvp-ribbon-button',onClick:()=>setOpen(true)},h('svg',{width:18,height:18,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.6,'aria-hidden':true},h('path',{d:'M4 4h6v6H4z M14 4h6v6h-6z M4 14h6v6H4z M14 14h6v6h-6z'})),'打开游戏工具')),h(WebVideoAddSentenceDialog,{open,onOpenChange:setOpen,titleText:'游戏工具',gameOnly:true,onChoose:text=>addSentenceText(text)}));}
