const WebVideoNovel=(()=>{
 function prepare(source,mapping){if(!source.trim())throw Error('请粘贴小说原文。');if(source.length>2000000)throw Error('文本过大，请按卷分次处理。');const units=[];let buffer='';const flush=()=>{if(buffer){units.push({id:units.length,text:buffer});buffer='';}};for(const c of source){if(/[“”「」『』"\r\n]/.test(c)){flush();units.push({id:units.length,text:c});}else{buffer+=c;if(/[。！？!?；;，,：:]/.test(c)||[...buffer].length>=80)flush();}}flush();if(units.length>200000)throw Error('文本片段过多，请按卷分次处理。');const names=mapping?.nameToId||{},knownSpeakers=Object.entries(names).filter(([name])=>name&&source.toLowerCase().includes(name.toLowerCase())).map(([name,id])=>({name,id}));return {source,units,knownSpeakers};}
 function resolve(prepared,output){const segments=output?.segments;if(!Array.isArray(segments)||!segments.length)throw Error('模型没有返回有效分段。');let next=0;const rows=[],omitted=[];for(const segment of segments){if(!segment||Object.keys(segment).some(k=>!['from','to','kind','speaker','uncertain','sceneBreak'].includes(k))||!Number.isInteger(segment.from)||!Number.isInteger(segment.to)||segment.from!==next||segment.to<segment.from||segment.to>=prepared.units.length)throw Error('模型返回的原文范围有遗漏、重复或无效字段，未应用。');next=segment.to+1;const text=prepared.units.slice(segment.from,next).map(unit=>unit.text).join('');if(!['dialogue','narration','cue','layout'].includes(segment.kind))throw Error('模型返回了不支持的段落类型。');if(typeof segment.speaker!=='string'||typeof segment.uncertain!=='boolean'||typeof segment.sceneBreak!=='boolean')throw Error('模型标注格式不完整。');const speaker=segment.speaker.trim(),validSpeaker=!!speaker&&speaker.length<=40&&/^[\p{L}\p{N} ·・]+$/u.test(speaker)&&prepared.source.includes(speaker);if(segment.kind==='layout'){if(!/^[\s“”「」『』"]+$/.test(text))throw Error('模型试图移除正文内容，已拒绝应用。');omitted.push({text,reason:'版式'});continue;}rows.push({...segment,text,speaker:validSpeaker?speaker:'',uncertain:segment.uncertain||segment.kind==='dialogue'&&!validSpeaker});}if(next!==prepared.units.length)throw Error('模型没有完整处理原文，未应用。');for(let i=0;i<rows.length;i++){const row=rows[i];if(row.kind!=='cue')continue;const following=rows[i+1],name=prepared.knownSpeakers.find(item=>item.name.toLowerCase()===row.speaker.toLowerCase());const pure=name&&new RegExp('^'+row.speaker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:说|说道|问|问道|答|答道|回答道)[：:，,]$').test(row.text.trim());if(pure&&row.from===row.to&&!row.uncertain&&following?.kind==='dialogue'&&following.speaker===row.speaker&&!following.uncertain){omitted.push({text:row.text,reason:'说话者已在人物栏表达'});row.omit=true;}else{row.kind='narration';row.uncertain=true;}}return {rows:rows.filter(row=>!row.omit),omitted};}
 function validateStage(stage,count,min=0,max=count-1,requireFirst=true){if(!stage||!Array.isArray(stage.changes)||![1,2].includes(stage.maxActors))throw Error('舞台结果无效。');const actors=new Map(stage.assets.actors.map(a=>[a.key,a])),backgrounds=new Set(stage.assets.backgrounds);let previous=min-1;for(const change of stage.changes){if(!change||Object.keys(change).some(k=>!['at','background','cast'].includes(k))||!Number.isInteger(change.at)||change.at<min||change.at>max||change.at<=previous||!Array.isArray(change.cast)||change.cast.length>stage.maxActors)throw Error('舞台安排的行号或人数超出限制。');previous=change.at;if(change.background!==null&&change.background!=='none'&&!backgrounds.has(change.background))throw Error('模型选择了不存在的背景。');const seen=new Set();for(const entry of change.cast){const actor=actors.get(entry.actor);if(!actor||seen.has(entry.actor)||!actor.figures.includes(entry.figure)||String(entry.figure).split('/').some(part=>part.toLowerCase()==='.mtn_exp')||Object.keys(entry).some(k=>!['actor','figure'].includes(k)))throw Error('模型选择了不存在或重复的人物立绘。');seen.add(entry.actor);}}if(requireFirst&&stage.changes[0]?.at!==0)throw Error('缺少初始舞台安排。');return stage;}
 function plan(model,prepared,result){const eol=model.source.includes('\r\n')?'\r\n':'\n',stage=result.staging;if(stage)validateStage(stage,result.rows.length);const actors=new Map((stage?.assets.actors||[]).map(a=>[a.key,a])),changes=new Map((stage?.changes||[]).map(c=>[c.at,c])),positions=['center','left','right','left13','right13','left14','right14'];let code='',reviewRelative=[],count=0,current=new Map(),bg=null;
  const safe=value=>{if(typeof value!=='string'||/[\r\n;|\\]/.test(value)||value.includes(' -'))throw Error('素材路径或ID含不能安全写入的字符，请人工处理。');return value;};
  const emit=line=>{reviewRelative.push(code.length);code+=line+eol;count++;};
  for(const row of model.statements||[]){if(row.command==='changeBg')bg=row.content||'none';if(row.command!=='changeFigure')continue;const pos=positions.find(p=>row.args[p]===true)||'center',explicit=typeof row.args.id==='string'||typeof row.args.id==='number'?String(row.args.id):'',id=explicit||'fig-'+pos;if(!row.content||row.content==='none'||row.args.clear===true){if(explicit)current.delete(id);else for(const [key,value]of current)if(value.pos===pos)current.delete(key);}else current.set(id,{id,file:row.content,pos,explicit:!!explicit});}
  if(stage){for(const old of current.values())emit('changeFigure:none'+(old.explicit?' -id='+safe(old.id):'')+' -'+old.pos+' -next;');current.clear();}
  for(let index=0;index<result.rows.length;index++){const row=result.rows[index],change=changes.get(index);if(change){if(change.background!==null&&change.background!==bg){emit('changeBg:'+safe(change.background)+' -next;');bg=change.background;}const desired=new Map(change.cast.map((item,i)=>{const actor=actors.get(item.actor);return [actor.id,{...actor,file:item.figure,pos:change.cast.length===1?'center':i===0?'left':'right',explicit:true}];}));for(const [id,old]of current){const next=desired.get(id);if(!next||next.file!==old.file||next.pos!==old.pos)emit('changeFigure:none -id='+safe(id)+' -'+old.pos+' -next;');}for(const [id,next]of desired){const old=current.get(id);if(!old||old.file!==next.file||old.pos!==next.pos)emit('changeFigure:'+safe(next.file)+' -id='+safe(id)+' -'+next.pos+' -next;');}current=desired;}
   let text=row.text.replace(/\r\n|\r|\n/g,'|');if(row.kind==='dialogue')text=text.replace(/^[“「『"]|[”」』"]$/g,'');if(!text.trim())continue;if(/ -/.test(text)||text.includes('\\')||row.text.includes('|'))throw Error('原文包含可能被WebGAL当作参数的内容，请人工处理：'+row.text.slice(0,50));const speaker=row.kind==='dialogue'?row.speaker:'',match=speaker&&[...current.values()].find(actor=>actor.name===speaker||(actor.aliases||[]).some(name=>name.toLowerCase()===speaker.toLowerCase())),id=match?.id||'';if(row.sceneBreak)code+='; 场景变化（AI标记，待核对）'+eol;emit((speaker?speaker:':')+(speaker?':':'')+text.replace(/;/g,'\\;')+(id?' -id -figureId='+safe(id):'')+';');}
  if(!count)throw Error('没有可追加的正文。');const prefix=model.source&&!/[\r\n]$/.test(model.source)?eol:'',after=model.source+prefix+code;WebVideoProject.parse(after);return {path:model.path,before:model.source,after,patches:[{startOffset:model.source.length,endOffset:model.source.length,before:'',after:prefix+code}],reviewOffsets:reviewRelative.map(n=>model.source.length+prefix.length+n),changed:count,operation:{type:'novelImport'}};
 }
 return {prepare,resolve,plan,validateStage};
})();
