const WebVideoPresetLibrary=(()=>{
 let data={presets:window.WebVideoNavigationMetadata?.effectPresets||[],saved:[]},pending=null,compiled=null;
 const stable=value=>JSON.stringify(sort(value)),sort=value=>Array.isArray(value)?value.map(sort):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,sort(value[key])])):value;
 const allowed=new Set(['setTransform','setTempAnimation','setAnimation','setComplexAnimation','setTransition','pixi','pixiInit','filmMode','setTextbox','miniAvatar']);
 const canonical=c=>c==='pixiPerform'?'pixi':c;
 function parseCode(code){const parsed=WebVideoProject.parse(code).sentenceList.filter(s=>!s.isLineBreakHolder&&(commandType[s.command]||s.commandRaw)!=='comment');if(!parsed.length)throw Error('请填写至少一条效果语句。');return parsed.map(s=>{const command=canonical(commandType[s.command]||s.commandRaw);if(!allowed.has(command))throw Error('预制效果不支持此类语句：'+command);if(s.startLine!==s.endLine)throw Error('每条效果语句需完整写在一行内。');const args=Object.fromEntries(s.args.map(a=>[a.key,a.value]));let content=s.content;if(['setTransform','setTempAnimation'].includes(command)){content=JSON.parse(content);if(command==='setTempAnimation'?!Array.isArray(content):!content||Array.isArray(content)||typeof content!=='object')throw Error('效果参数格式不正确。');}return {command,content,args};});}
 function signature(row){let content=row.content;try{if(['setTransform','setTempAnimation'].includes(row.command)&&typeof content==='string')content=JSON.parse(content);}catch{return null;}const args={...row.args};delete args.target;delete args.next;return stable({command:canonical(row.command),content,args});}
 function entries(){return data.presets.concat(data.saved.map(item=>({...item,category:'手动添加'})));}
 function compile(){if(compiled)return compiled;if(typeof WebVideoProject==='undefined')return [];compiled=[];for(const entry of [...data.saved].reverse().concat(data.presets)){try{const rows=parseCode(entry.code);compiled.push({entry,rows,keys:rows.map(signature)});}catch{}}compiled.sort((a,b)=>b.keys.length-a.keys.length);return compiled;}
 function decorate(rows,statements){const covered=new Set(),all=compile();for(let i=0;i<statements.length;i++){const first=statements[i];if(covered.has(first.id))continue;for(const preset of all){const slice=statements.slice(i,i+preset.keys.length);if(slice.length!==preset.keys.length||slice.some((r,n)=>signature(r)!==preset.keys[n]))continue;
    // A single-target preset can match any object; multi-target presets retain their target relationships.
    const expected=preset.rows.map(r=>String(r.args.target||'')),actual=slice.map(r=>String(r.args.target||''));if(new Set(expected.filter(Boolean)).size>1?stable(expected)!==stable(actual):new Set(actual.filter(Boolean)).size>1)continue;
    const targetIds=[...new Set(actual.filter(Boolean))],name=preset.entry.name;for(const statement of slice){const row=rows.find(r=>r.id===statement.id);if(!row)continue;row.presetEffectName=name;row.title=name+(targetIds.length?' · '+targetIds.map(id=>window.WebVideoCharacterMap?.names()?.[id.toLowerCase()]||window.WebVideoNavigationMetadata.positions[id.replace(/^fig-/,'')]||(id==='bg-main'?'背景':id)).join('、'):'');row.parts=[{title:row.title,items:[]}];covered.add(row.id);if(statement!==first)row.presetContinuation=first.id;}break;
   }}return rows;}
 const api={entries,parseCode,decorate,accept(value){data={presets:value.presets||[],saved:value.saved||[]};compiled=null;const model=window.WebVideoPlus?.state().model;if(model)window.WebVideoPlus.publish(model.path,model.source,true);},async load(){if(pending)return pending;pending=(async()=>{try{const config=await(await fetch('/assets/video-export-service.json',{cache:'no-store'})).json(),url=new URL(config.baseUrl);if(url.protocol!=='http:'||!['localhost','127.0.0.1'].includes(url.hostname))return;const response=await fetch(url.origin+'/api/preset-effects',{headers:{Authorization:'Bearer '+config.token},signal:AbortSignal.timeout(5000)});if(response.ok)api.accept(await response.json());}catch{}finally{pending=null;}})();return pending;}};return api;
})();
window.WebVideoPresetLibrary=WebVideoPresetLibrary;
