async function webVideoInsertPreset(code,model,insertLine){
 if(!model)throw Error('请先打开故事文本。');if(WebVideoPlus.state().model?.path!==model.path||WebVideoPlus.state().model?.source!==model.source)throw Error('剧本已改变，请重新打开效果选择窗口。');WebVideoPresetLibrary.parseCode(code);const eol=model.source.includes('\r\n')?'\r\n':'\n';let offset=model.source.length;if(insertLine!==undefined){const lines=model.source.split('\n');if(!Number.isInteger(insertLine)||insertLine<0||insertLine>lines.length)throw Error('插入位置无效，请重新选择。');offset=lines.slice(0,insertLine).reduce((n,line)=>n+line.length+1,0);offset=Math.min(offset,model.source.length);}const before=offset>0&&!/[\r\n]/.test(model.source[offset-1])?eol:'',snippet=before+code.trim().replace(/\r?\n/g,eol)+eol,after=model.source.slice(0,offset)+snippet+model.source.slice(offset);await WebVideoProject.commit({path:model.path,before:model.source,after,changed:1,patches:[{startOffset:offset,endOffset:offset,before:'',after:snippet}],operation:{type:'presetEffect'}},'插入预制效果');
}
function WebVideoPresetChooser({insertLine,onDone}={}){
 const R=reactExports,h=R.createElement,model=R.useRef(WebVideoPlus.state().model),[entries,setEntries]=R.useState(()=>WebVideoPresetLibrary.entries()),[query,setQuery]=R.useState(''),[chosen,setChosen]=R.useState(null),[target,setTarget]=R.useState(null),[backgroundTarget,setBackgroundTarget]=R.useState(false),[busy,setBusy]=R.useState(false),[message,setMessage]=R.useState('');
 R.useEffect(()=>{let live=true;WebVideoProject.service('/api/preset-effects').then(value=>{WebVideoPresetLibrary.accept(value);if(live)setEntries(WebVideoPresetLibrary.entries());}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;};},[]);
 const groups=new Map();for(const item of entries.filter(item=>!query||item.name.toLowerCase().includes(query.toLowerCase()))){const category=item.category||'其他演出';if(!groups.has(category))groups.set(category,[]);groups.get(category).push(item);}
 function choose(entry){setChosen(entry);try{const targets=[...new Set(WebVideoPresetLibrary.parseCode(entry.code).map(row=>row.args.target).filter(Boolean))];setBackgroundTarget(targets.length===1&&targets[0]==='bg-main');setTarget(targets.length===1?(targets[0]==='bg-main'?'bg-main':''):null);}catch(e){setMessage(e.message);}}
 async function apply(){if(!chosen||busy)return;setBusy(true);try{let code=chosen.code;const parsed=WebVideoPresetLibrary.parseCode(code),targets=[...new Set(parsed.map(row=>row.args.target).filter(Boolean))];if(targets.length===1){let resolved=targets[0]==='bg-main'?'bg-main':String(target||'').trim();if(resolved&&resolved!=='bg-main'){const map=WebVideoCharacterMap.state().data||await WebVideoCharacterMap.load();resolved=map?.nameToId?.[resolved.toLowerCase()]||Object.keys(map?.idToName||{}).find(id=>id.toLowerCase()===resolved.toLowerCase())||resolved;if(/[\s;|]/.test(resolved))throw Error('请填写有效的人物名字或 ID。');}code=code.split('\n').map(line=>{const end=/(?<!\\);/.exec(line)?.index??line.length;return line.slice(0,end).replace(/ -target=[^\s;]+/g,()=>resolved?' -target='+resolved:'')+line.slice(end);}).join('\n');}await webVideoInsertPreset(code,model.current,insertLine);setMessage('已插入预制效果，原文已自动备份。');onDone?.();if(!onDone)WebVideoTools.close();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return h('div',{className:'wvp-preset-chooser'},h('input',{type:'search',value:query,placeholder:'搜索预制效果',disabled:busy,onChange:e=>setQuery(e.target.value)}),h('div',{className:'wvp-preset-groups'},...[...groups].map(([category,items])=>h('details',{key:category,className:'wvp-library-category',open:query?true:undefined},h('summary',null,category+' · '+items.length),h('div',{className:'wvp-preset-options'},...items.map(item=>h('button',{type:'button',key:item.id,disabled:busy,className:chosen?.id===item.id?'chosen':'',onClick:()=>choose(item)},item.name)))))),chosen&&h('div',{className:'wvp-preset-chosen'},h('strong',null,chosen.name),target!==null&&h('label',null,'目标',h('input',{value:backgroundTarget?'背景':target,disabled:busy||backgroundTarget,placeholder:'可直接输入人物名字或id，也可留空自行调整',onChange:e=>setTarget(e.target.value),'aria-label':'效果目标'}))),message&&h('p',{role:'status'},message),h('footer',null,h('span',null,insertLine===undefined?'插入到故事末尾':'插入到第 '+(insertLine+1)+' 行前'),h('button',{type:'button',className:'primary',disabled:busy||!chosen,onClick:apply},busy?'处理中…':'插入')));
}
window.WebVideoPresetChooser=WebVideoPresetChooser;
function WebVideoPresetManage(){
 const R=reactExports,h=R.createElement,[name,setName]=R.useState(''),[code,setCode]=R.useState(''),[message,setMessage]=R.useState(''),[busy,setBusy]=R.useState(false),[saved,setSaved]=R.useState([]);
 R.useEffect(()=>{WebVideoProject.service('/api/preset-effects').then(value=>setSaved(value.saved||[])).catch(e=>setMessage(e.message));},[]);
 async function save(){setBusy(true);try{if(!name.trim()||!code.trim())throw Error('请填写名称和效果语句。');WebVideoPresetLibrary.parseCode(code);const value=await WebVideoProject.service('/api/preset-effects/save',{name:name.trim(),code:code.trim()});WebVideoPresetLibrary.accept(value);setSaved(value.saved||[]);setMessage('已加入“手动添加”，所有游戏共用。');setName('');setCode('');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return h('div',{className:'wvp-preset-manage'},h('label',null,'名称',h('input',{value:name,required:true,maxLength:200,disabled:busy,onChange:e=>setName(e.target.value)})),h('label',null,'效果语句',h('textarea',{value:code,required:true,rows:7,disabled:busy,placeholder:'填写一行或多行 WebGAL 效果语句，每条语句完整写在一行内',onChange:e=>setCode(e.target.value)})),h('p',{className:'wvp-help'},'名称和语句均为必填。保存后归入“手动添加”。'),message&&h('p',{role:'status'},message),h('button',{type:'button',className:'primary',disabled:busy||!name.trim()||!code.trim(),onClick:save},busy?'保存中…':'追加'),h('details',{className:'wvp-library-category'},h('summary',null,'手动添加 · '+saved.length),...saved.map(item=>h('p',{key:item.id},item.name))));
}
WebVideoTools.register('presetEffects','Video+预制效果',WebVideoPresetChooser);
WebVideoTools.register('presetManage','追加Video+预制效果',WebVideoPresetManage);
