function WebVideoAnogoActionEditor({onBack}){
 const R=reactExports,h=R.createElement,P=WebVideoProject,[data,setData]=R.useState(null),[rows,setRows]=R.useState([]),[busy,setBusy]=R.useState(false),[dirty,setDirty]=R.useState(false),[message,setMessage]=R.useState('');
 const adopt=value=>{setData(value);setRows((value.rows||[]).map(row=>({...row})));setDirty(false);};
 R.useEffect(()=>{let active=true;P.service('/api/anogo-actions').then(value=>{if(active)adopt(value);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 async function run(fn){setBusy(true);try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const edit=(index,key,value)=>{setRows(old=>old.map((row,i)=>i===index?{...row,[key]:value}:row));setDirty(true);};
 return h('div',{className:'wvp-anogo-map'},h('h3',null,'Anogo 动作／表情映射'),h('p',null,'Anogo 的“动作”同时用于匹配动作和表情。默认表来自 Anogo；可填写关键词或模型中的完整名称，多个动作名字用 ; 分隔。'),h('div',{className:'wvp-tool-row'},h('button',{disabled:busy,onClick:()=>{if(!dirty||window.confirm('放弃未保存的映射修改并返回吗？'))onBack();}},'返回导入'),h('button',{disabled:busy,onClick:()=>run(async()=>{await P.service('/api/anogo-actions/open-folder',{});})},'打开 JSON 文件夹'),h('button',{disabled:busy,onClick:()=>{if(!dirty||window.confirm('放弃未保存的修改并重新读取吗？'))run(async()=>adopt(await P.service('/api/anogo-actions')));}},'重新读取')),data?.fatal?h('div',{className:'wvp-expression-warning',role:'alert'},h('p',null,data.message),h('button',{disabled:busy,onClick:()=>{if(window.confirm('恢复出厂映射？现有文件会另存为备份。'))run(async()=>{adopt(await P.service('/api/anogo-actions/reset',{expectedHash:data.hash}));setMessage('已恢复出厂映射。');});}},'恢复出厂设置'),h('button',{disabled:busy,onClick:()=>run(async()=>{await WebVideoPlus.flushEditor?.();await P.service('/api/anogo-actions/open-folder',{});await WebVideoCharacterMap.exitTerre();setMessage('已请求退出 Terre，请修改映射 JSON 后重新启动。');})},'退出 Terre，手动修改')):data&&h(R.Fragment,null,h('div',{className:'wvp-anogo-map-table'},h('table',{className:'wvp-tool-table'},h('thead',null,h('tr',null,h('th',null,'动作名字'),h('th',null,'动作关键词／名称'),h('th',null,'表情关键词／名称'),h('th',null,''))),h('tbody',null,...rows.map((row,i)=>h('tr',{key:i},...['names','motion','expression'].map(key=>h('td',{key},h('input',{'aria-label':'第 '+(i+1)+' 行 '+key,value:row[key],disabled:busy,onChange:e=>edit(i,key,e.target.value)}))),h('td',null,h('button',{disabled:busy,onClick:()=>{setRows(old=>old.filter((_,index)=>index!==i));setDirty(true);}},'删除'))))))),h('div',{className:'wvp-tool-row'},h('button',{disabled:busy,onClick:()=>{setRows(old=>[...old,{names:'',motion:'',expression:''}]);setDirty(true);}},'在末尾增加一行'),h('button',{className:'primary',disabled:busy||!dirty,onClick:()=>run(async()=>{const next=await P.service('/api/anogo-actions',{rows,expectedHash:data.hash});adopt(next);setMessage('已保存。'+(next.warnings||[]).join(' '));})},'保存'))),message&&h('p',{role:'status'},message));
}
function WebVideoImportPanel(){
 const R=reactExports,h=R.createElement,P=WebVideoProject,[input,setInput]=R.useState(''),[useActions,setUseActions]=R.useState(false),[editing,setEditing]=R.useState(false),[busy,setBusy]=R.useState(false),[message,setMessage]=R.useState(''),[warnings,setWarnings]=R.useState([]);
 async function loadFile(file){if(!file)return;try{if(file.size>4*1024*1024)throw Error('文件不能超过 4 MB。');setInput(await file.text());setMessage('');setWarnings([]);}catch(e){setMessage(e.message);}}
 async function execute(importNow){if(busy)return;setBusy(true);setWarnings([]);try{const model=WebVideoPlus.state().model;if(!model)throw Error('请先打开要追加的故事。');const characters=await WebVideoCharacterMap.load();if(!characters||characters.fatal)throw Error('角色 ID 映射表不可用，请先修复。');let actions=null;if(useActions){actions=await P.service('/api/anogo-actions');if(actions.fatal)throw Error('动作映射表格式有误，请先编辑或恢复。');}const plan=await WebVideoAnogo.compile(input,model,characters,actions,useActions);if(WebVideoPlus.state().model?.path!==model.path||WebVideoPlus.state().model?.source!==model.source)throw Error('故事已改变，请重新操作。');if(importNow){await P.commit(plan,'导入 Anogo 故事');setInput('');setMessage('已追加到故事末尾并自动备份；'+plan.reviewCount+' 条标记为待核对。');}else setMessage('编译检查通过：'+plan.statementCount+' 条 WebGAL 语句，'+plan.reviewCount+' 条需要核对。');setWarnings(plan.warnings);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 if(editing)return h(WebVideoAnogoActionEditor,{onBack:()=>setEditing(false)});
 return h('div',{className:'wvp-anogo-import'},h('a',{href:'https://github.com/A-kirami/anogo',target:'_blank',rel:'noopener noreferrer'},'Anogo是什么？'),h('p',null,'本工具只提供Anogo生成文本的导入和编译检查，您可下载Anogo使用完整功能。'),h('input',{type:'file',accept:'.json,.yaml,.yml','aria-label':'选择 Anogo JSON 或 YAML 文件',disabled:busy,onChange:e=>loadFile(e.target.files?.[0])}),h('textarea',{'aria-label':'Anogo文本',rows:9,value:input,disabled:busy,placeholder:'粘贴 Anogo 生成的 JSON / YAML 文本',onChange:e=>{setInput(e.target.value);setMessage('');setWarnings([]);}}),h('div',{className:'wvp-tool-row'},h('label',null,h('input',{type:'checkbox',checked:useActions,disabled:busy,onChange:e=>setUseActions(e.target.checked)}),'使用Anogo动作'),h('button',{disabled:busy,onClick:()=>setEditing(true)},'编辑动作／表情映射')),useActions&&h('p',{className:'wvp-expression-warning',role:'alert'},'Anogo动作、表情导入机制缺乏维护，若您无特殊需求，我们推荐您手动设置每个表情、动作'),message&&h('p',{role:'status'},message),warnings.length>0&&h('ul',{className:'wvp-id-warnings'},...warnings.map((text,i)=>h('li',{key:i},text))),h('footer',null,h('button',{disabled:busy||!input.trim(),onClick:()=>execute(false)},'编译检查'),h('button',{className:'primary',disabled:busy||!input.trim(),onClick:()=>execute(true)},busy?'处理中…':'导入到故事末尾')));
}
WebVideoTools.register('textImport','导入Anogo故事',WebVideoImportPanel);
