/* Injected inside Terre's module, using its React, parser and editor instances. */
const WebVideoPlus = (()=>{
  const Core=window.WebVideoTimelineCore,selection=new Core.Selection(),listeners=new Set(),editors=new Map(),reviews=new Map();
  let model=null,position=1,opened=false,pending=null,error='',notice='',activePath='',selectionStamp='',requestedMode='set';
  const modules=__WEBVIDEO_MODULES__;
  const emit=()=>{listeners.forEach(fn=>fn());const stamp=[activePath,model?.revision,selection.mode,[...selection.ids].join(','),selection.range?.join(':')].join('|');if(stamp!==selectionStamp){selectionStamp=stamp;window.dispatchEvent(new CustomEvent('webvideo:selectionchange',{detail:selection.snapshot()}));}};
  const canonical=path=>String(path||'').replace(/\\/g,'/').replace(/^\//,'');
  function syncReviews(path,source){const entry=reviews.get(path);if(!entry||entry.source===source)return;const old=entry.source;let start=0,suffix=0;while(start<old.length&&start<source.length&&old[start]===source[start])start++;while(suffix<old.length-start&&suffix<source.length-start&&old[old.length-1-suffix]===source[source.length-1-suffix])suffix++;const oldEnd=old.length-suffix,delta=source.length-old.length;
   entry.marks=entry.marks.flatMap(mark=>{let offset;if(mark.endOffset<=start)offset=mark.startOffset;else if(mark.startOffset>=oldEnd)offset=mark.startOffset+delta;else{if(old.indexOf(mark.source)!==old.lastIndexOf(mark.source))return [];const at=source.indexOf(mark.source);if(at<0||source.indexOf(mark.source,at+1)>=0)return [];offset=at;}return source.slice(offset,offset+mark.source.length)===mark.source?[{...mark,startOffset:offset,endOffset:offset+mark.source.length}]:[];});entry.source=source;
  }
  const api={version:'0.4.10',selectionApiVersion:1,modules,
    subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},
    markForReview(path,source,offsets){path=canonical(path);if(!model||path!==activePath||model.source!==source)return;syncReviews(path,source);const entry=reviews.get(path)||{source,marks:[]};for(const offset of offsets){const row=model.statements.find(item=>item.startOffset===offset);if(row&&!entry.marks.some(mark=>mark.startOffset===offset))entry.marks.push({startOffset:offset,endOffset:row.endOffset,source:row.source});}reviews.set(path,entry);emit();},
    reviewRows(rows){const visible=new Set(rows.map(row=>row.id)),pending=new Map();for(const mark of reviews.get(activePath)?.marks||[]){const statement=model?.statements.find(row=>row.startOffset===mark.startOffset),owner=statement&&(visible.has(statement.id)?statement.id:statement.navigationOwnerId);if(owner){if(!pending.has(owner))pending.set(owner,[]);pending.get(owner).push(mark.startOffset);}}return rows.map(row=>pending.has(row.id)?{...row,reviewOffsets:pending.get(row.id),annotations:[...row.annotations,'待核对']}:row);},
    clearReviewMarks(){const entry=reviews.get(activePath);if(entry){entry.marks=[];emit();}},
    acknowledgeReview(row){const entry=reviews.get(activePath);if(!entry)return;const offsets=new Set(row.reviewOffsets||[row.startOffset]),count=entry.marks.length;entry.marks=entry.marks.filter(mark=>!offsets.has(mark.startOffset));if(count!==entry.marks.length)emit();},
    activate(path){path=canonical(path);if(activePath!==path){activePath=path;model=null;selection.model=null;selection.clear();position=1;opened=false;error='';notice='';if(pending){pending.resolve(null);pending=null;}emit();}const editor=editors.get(path);if(editor)editor.publish();},
    publish(path,text,force=false){path=canonical(path);if(path!==activePath)return;syncReviews(path,text);if(!force&&model&&model.path===path&&model.source===text){window.WebVideoNavigation?.loadAnimations(model,()=>{if(activePath===path&&model?.source===text)api.publish(path,text,true);});return;}try{const next=Core.derive(path,text,parseScene(text),commandType);const had=selection.ids.size>0;const changed=selection.bind(next);model=next;error='';notice=had&&changed?'剧本已变化，原选择已清除。':'';emit();if(!force)window.WebVideoNavigation?.loadAnimations(next,()=>{if(activePath===path&&model?.source===text)api.publish(path,text,true);});}catch(e){model=null;selection.model=null;selection.clear();error='时间线暂不可用：'+e.message;emit();}},
    position(path,line){if(canonical(path)===activePath&&position!==line){position=line;emit();}},
    attachMonaco(editor,path,flush){path=canonical(path);let ready=false;const publish=()=>{if(ready)api.publish(path,editor.getValue());};const registration={editor,publish,flush,replace(text){editor.pushUndoStop();editor.executeEdits('WebVideo+',[{range:editor.getModel().getFullModelRange(),text,forceMoveMarkers:true}]);editor.pushUndoStop();},ready(){ready=true;publish();},jump(line){editor.setPosition({lineNumber:line,column:1});editor.revealLineInCenter(line);editor.focus();}};editors.set(path,registration);const content=editor.onDidChangeModelContent(publish),cursor=editor.onDidChangeCursorPosition(e=>api.position(path,e.position.lineNumber)),change=editor.onDidChangeModel(publish);editor.onDidDispose(()=>{content.dispose();cursor.dispose();change.dispose();if(editors.get(path)===registration)editors.delete(path);});},
    flushEditor(){return editors.get(activePath)?.flush?.();},
    replaceBuffer(path,text){path=canonical(path);editors.get(path)?.replace?.(text);if(path===activePath)api.publish(path,text);},
    monacoReady(value){const editor=typeof value==='string'?editors.get(canonical(value)):[...editors.values()].find(item=>item.editor===value);editor?.ready?.();},
    attachGraphical(path,text,rows,virtualizer,loaded,replace){path=canonical(path);const registration={replace,publish:()=>{if(loaded)api.publish(path,text);},jump(line){const i=rows.findIndex(r=>line-1<=r.endLine);if(i>=0)virtualizer.scrollToIndex(i,{align:'start'});editorLineHolder.recordSceneEditingLine(path,line);api.position(path,line);}};editors.set(path,registration);registration.publish();return()=>{if(editors.get(path)===registration)editors.delete(path);};},
    jump(row,{preview=true}={}){const editor=editors.get(activePath);if(editor){editor.jump(row.startLine);api.position(activePath,row.startLine);if(preview&&model){const hadNotice=!!notice;notice='';if(hadNotice)emit();const snapshot={path:model.path,source:model.source,revision:model.revision};WebVideoRuntime.syncPreview(snapshot,row).catch(error=>{if(api.validateSelection(snapshot)){notice=error.message;emit();}});}}else{notice='编辑器正在加载，请稍后重试。';emit();}},
    state(){return {model,position,opened,error,notice,selection,selectionMode:requestedMode};},
    open(){if(!modules.includes('timelineSelector'))return;opened=true;emit();},
    close(confirm=false){const snapshot=confirm?selection.snapshot():null;if(confirm&&(!snapshot||!snapshot.ids.length))return;opened=false;if(pending){pending.resolve(snapshot);pending=null;}emit();},
    requestSelection(options={}){if(!modules.includes('timelineSelector'))return Promise.reject(Error('尚未安装时间线选择模块'));if(pending)return Promise.reject(Error('已有工具正在请求选择'));if(!model)return Promise.reject(Error('请先打开剧本'));if(options.mode&&!['range','set'].includes(options.mode))return Promise.reject(Error('无效选择模式'));selection.clear();requestedMode=options.mode||'set';selection.mode=requestedMode;opened=true;emit();return new Promise(resolve=>{pending={resolve};});},
    getSelection(){return selection.snapshot();},
    validateSelection(snapshot){return !!model&&!!snapshot&&snapshot.path===model.path&&snapshot.revision===model.revision&&snapshot.source===model.source;},
    clearSelection(){selection.clear();emit();},notify(message){notice=String(message||'');emit();},changed:emit
  };
  window.WebVideoPlus=api;return api;
})();
function WebVideoTimelineHost(){
  const R=reactExports,h=R.createElement,api=WebVideoPlus,Core=window.WebVideoTimelineCore;
  const tag=useGameEditorContext(s=>s.currentTag),game=useEditorStore.use.subPage(),dark=useEditorStore.use.isDarkMode();
  const [,refresh]=R.useReducer(n=>n+1,0),[collapsed,setCollapsed]=R.useState(false),[query,setQuery]=R.useState(''),[speaker,setSpeaker]=R.useState(''),[kind,setKind]=R.useState(''),[collapsedGroups,setCollapsedGroups]=R.useState(new Set());
  const widthLimit=()=>Math.max(200,Math.min(560,Math.floor(window.innerWidth*.55)));
  const clampWidth=value=>Math.round(Math.min(widthLimit(),Math.max(200,Number(value)||280)));
  const [navWidth,setNavWidth]=R.useState(()=>{try{return clampWidth(localStorage.getItem('webvideo-plus.navigator-width'));}catch{return 280;}}),resizeState=R.useRef(null),widthRef=R.useRef(navWidth);
  const setWidth=(value,save=false)=>{const next=clampWidth(value);widthRef.current=next;setNavWidth(next);if(save)try{localStorage.setItem('webvideo-plus.navigator-width',String(next));}catch{}};
  const finishResize=e=>{if(!resizeState.current)return;resizeState.current=null;setWidth(widthRef.current,true);if(e?.currentTarget?.hasPointerCapture?.(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);};
  R.useEffect(()=>{const resize=()=>{setWidth(widthRef.current);refresh();},blur=()=>finishResize();window.addEventListener('resize',resize);window.addEventListener('blur',blur);return()=>{window.removeEventListener('resize',resize);window.removeEventListener('blur',blur);};},[]);
  const drag=R.useRef(null),rowRefs=R.useRef(new Map()),dialogRef=R.useRef(null);
  const path=tag?.type==='scene'?(tag.path.startsWith('games/')?tag.path:`games/${game}/game/${tag.path}`):'';
  R.useEffect(()=>api.subscribe(refresh),[]);
  R.useEffect(()=>{const toggle=()=>setCollapsed(value=>!value);window.addEventListener('webvideo:toggle-navigator',toggle);return()=>window.removeEventListener('webvideo:toggle-navigator',toggle);},[]);
  R.useEffect(()=>{api.activate(path);setQuery('');setSpeaker('');setKind('');return()=>api.activate('');},[path]);
  R.useEffect(()=>{const timer=setInterval(()=>{if(path)api.position(path,Math.max(1,editorLineHolder.getSceneLine(path)));},180);return()=>clearInterval(timer);},[path]);
  const state=api.state(),mode=state.selectionMode,model=state.model,selection=state.selection,convertibleSingleChoices=model?.statements?.filter(row=>row.convertibleSingleChoose)||[],all=api.reviewRows(window.WebVideoTools?window.WebVideoTools.decorate(model):model?.rows||[]),visible=Core.filter(all,{text:query,speaker,kind});
  R.useEffect(()=>{const finish=()=>drag.current=null;window.addEventListener('pointerup',finish);window.addEventListener('blur',finish);return()=>{window.removeEventListener('pointerup',finish);window.removeEventListener('blur',finish);};},[]);
  R.useEffect(()=>setCollapsedGroups(new Set()),[path,model?.revision]);
  const groupIds=[...new Set(all.flatMap(item=>[...(item.parentId?[item.parentId]:[]),...(item.embeddedEffects?.length?[item.id]:[])]))],allGroupsCollapsed=groupIds.length>0&&groupIds.every(id=>collapsedGroups.has(id));
  const toggleAllGroups=()=>setCollapsedGroups(allGroupsCollapsed?new Set():new Set(groupIds));
  const toggleGroup=id=>setCollapsedGroups(previous=>{const next=new Set(previous);next.has(id)?next.delete(id):next.add(id);return next;});
  const activeStatement=model?.statements.find(row=>row.startLine<=state.position&&row.endLine>=state.position),active=activeStatement?.navigationOwnerId||all.filter(r=>r.startLine<=state.position).at(-1)?.id;
  R.useEffect(()=>{const parent=all.find(row=>row.id===active)?.parentId;if(parent)setCollapsedGroups(previous=>{if(!previous.has(parent))return previous;const next=new Set(previous);next.delete(parent);return next;});},[active]);
  R.useEffect(()=>{rowRefs.current.get(active)?.scrollIntoView({block:'nearest'});},[active,collapsed]);
  R.useEffect(()=>{if(state.opened){const previous=document.activeElement;dialogRef.current?.querySelector('button,[tabindex="0"]')?.focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();api.close();}if(e.key==='Tab'){const elements=[...(dialogRef.current?.querySelectorAll('button,input,select,[tabindex="0"]')||[])].filter(x=>!x.disabled);if(!elements.length)return;const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};}},[state.opened]);
  if(!path)return null;
  const button=(text,onClick,props={})=>h('button',{type:'button',onClick,...props},text);
  const convertHints=async rows=>{try{const result=await window.WebVideoSingleLineHint.convertRows(rows);if(!result.canceled)api.notify('已转换 '+result.changed+' 个单选分支为单行提示。');}catch(error){api.notify(error.message||String(error));}};
  const choose=(row,e)=>{if(mode==='range'&&selection.ids.size>1&&!e.shiftKey)selection.clear();selection.select(row.id,{shift:e.shiftKey,range:mode==='range',free:mode==='set'});api.changed();};
  const chooseSection=(id,next=false)=>{const old=new Set(selection.ids);selection.section(id,next);if(mode==='set'){selection.mode='set';selection.range=null;for(const id of old)selection.ids.add(id);}api.changed();};
  const sectionActions=row=>h('span',{className:'wvp-section-actions'},button('本节',e=>{e.stopPropagation();chooseSection(row.id);}));
  const rowIcon=item=>h('svg',{className:'wvp-kind-icon',width:17,height:17,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.7,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true},h('path',{d:({section:'M3 5h18v14H3z M3 14l5-5 5 5 3-3 5 5',figure:'M8 7a4 4 0 1 0 8 0 4 4 0 1 0-8 0 M4 21a8 8 0 0 1 16 0',event:'M9 4l10 8-10 8z',dialogue:'M4 4h16v12H10l-6 4z'})[item.kind]}));
  const reviewMenu=(event,item)=>{event.preventDefault();event.stopPropagation();if(window.WebVideoCheckActions)window.WebVideoCheckActions.dismissReview(item,event.shiftKey);else if(event.shiftKey)api.clearReviewMarks();else api.acknowledgeReview(item);};
  const production=(item)=>item.productionMarks?.map(mark=>h('span',{key:mark.id,className:'wvp-annotation marker',title:'右键取消、shift+右键取消全部',onContextMenu:event=>{event.preventDefault();event.stopPropagation();window.WebVideoCheckActions?.dismissMarker(mark.id,event.shiftKey);}},mark.status));
  const row=(item,selector=false,{part={title:item.title,items:[],footer:''},index=0,secondary=false,contextOnly=false,hasChildren=false,collapsed=false,toggle}={})=>{
    const compact=secondary||!!part.filterName||['playEffect','miniAvatar','filmMode','setTextbox','pixi','pixiPerform','pixiInit'].includes(item.command),title=item.kind==='dialogue'?item.title:(item.parts?.length>1&&!secondary?item.title+' · '+part.title:part.title),parameters=[...(part.items||[]),part.footer].filter(Boolean).join('，'),annotations=index===0?item.annotations:[],time=index===0?item.videoTime:null,details=!compact&&parameters;
    return h('div',{key:item.id+':'+index,ref:el=>{if(!selector&&index===0){if(el)rowRefs.current.set(item.id,el);else rowRefs.current.delete(item.id);}},className:'wvp-row wvp-projected-row '+item.kind+(secondary?' wvp-secondary':'')+(contextOnly?' wvp-context-row':'')+((details||(!secondary&&(time||annotations.length||item.speakerSource||item.productionMarks?.length>0)))?' has-details':'')+(active===item.id?' current':'')+(selector&&selection.ids.has(item.id)?' selected':''),role:contextOnly?'group':selector?'option':'button',tabIndex:contextOnly?-1:0,'aria-selected':selector&&!contextOnly?selection.ids.has(item.id):undefined,'aria-current':!selector&&active===item.id?'location':undefined,title:'第 '+item.startLine+' 行 · '+title+(parameters?'：'+parameters:'')+(annotations.length?' · '+annotations.join(' · '):''),onClick:e=>{if(contextOnly)return;if(!selector){api.acknowledgeReview(item);api.jump(item);}else if(mode!=='range')choose(item,e);},onDoubleClick:()=>{if(!contextOnly)api.jump(item);},onKeyDown:e=>{if(!contextOnly&&e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selector?choose(item,e):(api.acknowledgeReview(item),api.jump(item));}},onPointerDown:e=>{if(contextOnly)return;if(selector&&mode==='range'&&e.button===0&&e.target===e.currentTarget||selector&&mode==='range'&&e.button===0&&!e.target.closest('button')){e.preventDefault();if(!e.shiftKey&&selection.ids.size>1)selection.clear();selection.select(item.id,{range:true});drag.current=item.id;api.changed();}},onPointerEnter:()=>{if(selector&&drag.current){selection.select(item.id,{range:true});api.changed();}},onContextMenu:selector&&item.kind==='section'?e=>{e.preventDefault();chooseSection(item.id);}:undefined},
      h('span',{className:'wvp-line'},!secondary&&rowIcon(item),h('span',null,item.startLine)),h('div',{className:'wvp-row-main'},h('div',{className:'wvp-title'},item.kind==='dialogue'&&h('strong',{className:item.narration?'wvp-narration':''},(item.displaySpeaker||item.speaker)+'  '),title,compact&&parameters&&h('span',{className:'wvp-inline-parameters'},' · '+parameters),secondary&&time&&h('span',{className:'wvp-time'},' · '+time),secondary&&production(item),secondary&&item.reviewOffsets?.length>0&&h('span',{className:'wvp-annotation marker',title:'右键取消、shift+右键取消全部',onContextMenu:event=>reviewMenu(event,item)},'待核对'),index===0&&item.checkIssues?.map(issue=>h('span',{key:issue.code,className:'wvp-check-alert',tabIndex:0,title:issue.message+'\n右键取消、shift+右键取消所有此类提示','aria-label':issue.message,onClick:event=>event.stopPropagation(),onContextMenu:event=>{event.preventDefault();event.stopPropagation();window.WebVideoCheckActions?.dismissIssue(model,issue,event.shiftKey);}},'！'))),!secondary&&(details||time||annotations.length>0||item.speakerSource||item.productionMarks?.length>0)&&h('div',{className:'wvp-row-detail'},item.kind==='dialogue'&&item.speakerSource&&h('span',{className:'wvp-speaker-source '+item.speakerSourceType,'aria-label':'说话者：'+item.speakerSource},item.speakerSource),details&&h('span',{className:'wvp-parameters'},parameters),time&&h('span',{className:'wvp-time'},time),production(item),...annotations.map((text,i)=>h('span',{key:i,className:'wvp-annotation marker',...(text==='待核对'&&item.reviewOffsets?.length?{title:'右键取消、shift+右键取消全部',onContextMenu:event=>reviewMenu(event,item)}:{})},text)))),!selector&&index===0&&item.convertibleSingleChoose&&h('button',{type:'button',className:'wvp-convert-hint',title:'取消原跳转目标，改为显示后自动继续',onClick:e=>{e.stopPropagation();convertHints([item]);}},'转为单行提示'),hasChildren&&h('button',{type:'button',className:'wvp-group-toggle','aria-label':(collapsed?'展开':'收起')+'附属组件','aria-expanded':!collapsed,onClick:e=>{e.stopPropagation();toggle();}},h('svg',{width:12,height:12,viewBox:'0 0 16 16',fill:'none',stroke:'currentColor','aria-hidden':true},h('path',{d:collapsed?'m6 3 5 5-5 5':'m3 6 5 5 5-5'}))),selector&&!contextOnly&&selection.ids.has(item.id)&&h('span',{className:'wvp-check','aria-hidden':true},h('svg',{width:13,height:13,viewBox:'0 0 20 20',fill:'none',stroke:'currentColor',strokeWidth:2},h('path',{d:'m4 10 4 4 8-8'}))),selector&&item.kind==='section'&&sectionActions(item));
  };
  const tree=(items,selector=false)=>webVideoRenderTree({h,all,visible:items,selector,row,collapsedGroups,toggleGroup});
  const empty=state.error||(!model?'正在读取当前剧本…':all.length?'没有匹配的事件。':'当前剧本没有可显示的剧情事件。');
  const nav=api.modules.includes('timelineNavigator')?h('aside',{className:'wvp-nav'+(collapsed?' collapsed':''),'aria-label':'剧情导航','data-theme':dark?'dark':'light',style:{width:collapsed?48:navWidth,minWidth:collapsed?48:navWidth}},!collapsed&&h('div',{className:'wvp-resizer',role:'separator',tabIndex:0,'aria-label':'调整剧情导航宽度','aria-orientation':'vertical','aria-valuemin':200,'aria-valuemax':widthLimit(),'aria-valuenow':navWidth,title:'拖动调整宽度；方向键微调',onPointerDown:e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();resizeState.current={right:e.currentTarget.parentElement.getBoundingClientRect().right};e.currentTarget.setPointerCapture(e.pointerId);},onPointerMove:e=>{if(resizeState.current)setWidth(resizeState.current.right-e.clientX);},onPointerUp:finishResize,onPointerCancel:finishResize,onLostPointerCapture:finishResize,onKeyDown:e=>{const values={ArrowLeft:navWidth+16,ArrowRight:navWidth-16,Home:200,End:widthLimit()};if(e.key in values){e.preventDefault();setWidth(values[e.key],true);}}}),h('div',{className:'wvp-heading'},button(collapsed?'展开':'收起',()=>setCollapsed(!collapsed),{'aria-expanded':!collapsed}),!collapsed&&h('strong',null,'剧情导航'),!collapsed&&typeof WebVideoTimeToggle==='function'&&h(WebVideoTimeToggle,{model})), !collapsed&&h(R.Fragment,null,model?.firstBgmLine&&h('p',{className:'wvp-bgm-warning',role:'note'},'不推荐使用WebGAL自带背景音乐，您可使用WebVideo+提供的音乐工具'),model?.firstManualLine&&(convertibleSingleChoices.length?h('div',{className:'wvp-manual-warning',role:'alert'},h('span',null,model.firstManualLine+'行起有手动点选组件；其中 '+convertibleSingleChoices.length+' 个单选分支可转为单行提示。'),button('全部转为单行提示',()=>convertHints(convertibleSingleChoices),{title:'取消这些单选分支的原跳转目标，改为显示后自动继续'})):h('p',{className:'wvp-manual-warning',role:'alert'},model.firstManualLine+'行有手动点选组件，时间线不可靠')),state.notice&&h('p',{className:'wvp-nav-status',role:'status'},state.notice),h('div',{className:'wvp-subtitle wvp-nav-actions'},h('span',null,`当前第 ${state.position} 行 · ${all.length} 个组件`),groupIds.length>0&&button(allGroupsCollapsed?'全部展开':'全部收起',toggleAllGroups,{'aria-label':allGroupsCollapsed?'展开全部附属组件':'收起全部附属组件'})),h('div',{className:'wvp-list'},all.length?tree(all):h('p',{className:'wvp-empty'},empty)))):null;
  const selected={mode:selection.mode,ranges:selection.range?[{startLine:selection.range[0],endLine:selection.range[1]}]:[]};
  const modal=state.opened?h(WebVideoStorySelector,{api,model,mode,dark,dialogRef}):null;
  return h(R.Fragment,null,nav,modal);
}
function WebVideoStorySelector({api,model,mode,dark,dialogRef}){
 const R=reactExports,h=R.createElement,continuous=mode==='range',items=R.useMemo(()=>(model?.rows||[]).map(row=>({row,eligible:true})),[model]),pick=useWebVideoInlineSelection(items,(model?.path||'')+'\n'+(model?.source||''),false,continuous);
 const chosen=items.filter(item=>pick.selected.has(item.row.id));
 function confirm(){const selection=api.state().selection;selection.clear();if(continuous&&chosen.length){selection.select(chosen[0].row.id,{range:true});selection.select(chosen.at(-1).row.id,{range:true});}else{selection.mode='set';selection.results(chosen.map(item=>item.row));}api.close(true);}
 function section(row){const next=items.find(item=>item.row.command==='changeBg'&&item.row.startLine>row.startLine);pick.setSelected(new Set(items.filter(item=>item.row.startLine>=row.startLine&&(!next||item.row.startLine<next.row.startLine)).map(item=>item.row.id)));}
 return h('div',{className:'wvp-overlay','data-theme':dark?'dark':'light'},h('section',{className:'wvp-dialog wvp-story-selector',ref:dialogRef,role:'dialog','aria-modal':true,'aria-label':continuous?'选择导出片段':'选择剧情'},h('header',null,h('h2',null,continuous?'选择导出片段':'选择剧情'),h('button',{onClick:()=>api.close()},'关闭')),h('p',{className:'wvp-help'},continuous?'拖拽选择一段，或点击起点和终点；也可用 Shift 选择头尾。导出始终是一个连续区间。':'拖拽连续选择，Ctrl 多选，Shift 选择头尾。'),h('div',{className:'wvp-expression-actions'},h('button',{onClick:()=>pick.setSelected(new Set(items.map(item=>item.row.id)))},'全选'),h('button',{onClick:()=>pick.setSelected(new Set())},'取消选择')),h('div',{className:'wvp-expression-list',ref:pick.list,role:'listbox','aria-multiselectable':true,onPointerMove:pick.move,onPointerUp:pick.stop,onPointerCancel:pick.stop,onLostPointerCapture:pick.stop},...items.map((item,index)=>h('div',{key:item.row.id,'data-filter-row':index,role:'option','aria-selected':pick.selected.has(item.row.id),tabIndex:0,className:'wvp-expression-row'+(pick.selected.has(item.row.id)?' selected':''),onPointerDown:event=>pick.down(index,event),onKeyDown:event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();pick.choose(index,event);}}},h('span',{className:'wvp-expression-check'},pick.selected.has(item.row.id)?'✓':''),h('span',{className:'wvp-expression-line'},item.row.startLine),h('span',{className:'wvp-expression-text'},(item.row.speaker?item.row.speaker+'：':'')+item.row.title),item.row.command==='changeBg'&&h('button',{onPointerDown:event=>event.stopPropagation(),onClick:event=>{event.stopPropagation();section(item.row);}},'本节')))),h('footer',null,h('span',null,chosen.length?'第 '+chosen[0].row.startLine+'—'+chosen.at(-1).row.endLine+' 行':'尚未选择'),h('button',{className:'primary',disabled:!chosen.length,onClick:confirm},'确认'))));
}
function WebVideoSelectionButton(){return reactExports.createElement(IconWithTextItemSmall,{text:'选择剧情',onClick:()=>WebVideoPlus.open()});}
