globalThis.__createNativeTimeline=async({script,policy})=>{
   await __reportNativePlan({phase:"initializing",checkpoint:"timeline-entry"});
   const w=__wgProbe,core=w.core,pc=core.gameplay.performController,clock=__pwClock.controller,embed=clock._embedder,nativeTimer=embed.setTimeout.bind(embed);
   embed.setTimeout=(fn,delay)=>delay===undefined?(queueMicrotask(fn),()=>{}):nativeTimer(fn,delay);
   for(const [key,value] of Object.entries({textSpeed:policy.textSpeed,autoSpeed:policy.autoSpeed}))w.store.dispatch({type:'userData/setOptionData',payload:{key,value}});
   await __reportNativePlan({phase:"initializing",checkpoint:"before-clock"});await clock.runFor(500);await __reportNativePlan({phase:"initializing",checkpoint:"after-clock"});await clock.pauseAt(Date.now());if(!policy.renderDuringPlan){const app=core.gameplay.pixiStage.currentApp;app.ticker.remove(app.render,app);app.render=()=>{};}
   const normalize=src=>decodeURIComponent(new URL(src,location.href).pathname),mediaTimers=new WeakMap(),pause=HTMLMediaElement.prototype.pause;
   HTMLMediaElement.prototype.play=function(){pause.call(this);const d=policy.durations[normalize(this.currentSrc||this.src)];if(d&&!this.loop&&this.id!=='bgm'){clearTimeout(mediaTimers.get(this));mediaTimers.set(this,setTimeout(()=>this.dispatchEvent(new Event('ended')),d));}return Promise.resolve();};
   HTMLMediaElement.prototype.pause=function(){clearTimeout(mediaTimers.get(this));return pause.call(this);};
   const yieldQueue=[],yieldChannel=new MessageChannel();yieldChannel.port1.onmessage=()=>yieldQueue.shift()?.();const yieldTask=()=>new Promise(resolve=>{yieldQueue.push(resolve);yieldChannel.port2.postMessage(0);});const planStepMs=100,domWorkload=[];const sampleDom=()=>{if(typeof globalThis.__gpuDomCaptureNeeded!=='function')return;const capture=globalThis.__gpuDomCaptureNeeded();if(!capture)return;const state=globalThis.__gpuDomState,reason=state?.dirtyReason||'mutation',units=reason==='animation'||reason==='video'?Math.max(1,Math.round(planStepMs*(Number(policy.fps)||60)/1000)):1;domWorkload.push({atMs:origin===null?0:performance.now()-origin,reason,units});if(state)state.dirty=false;};const singleLineHintDuration=(s,params)=>{if(s.commandRaw!=='choose'||Number(params.defaultChoose)!==1||params.next===true)return 0;const options=String(s.content||'').split(/(?<!\\)\|/);if(options.length!==1)return 0;const nodes=options[0].split(/(?<!\\):/);if(nodes.length!==2||!/^__wvp_hint_[A-Za-z0-9_]+$/.test(nodes[1].trim()))return 0;const ms=Number(params.wvpHint);return Number.isFinite(ms)&&ms>=100&&ms<=60000?ms:1800;};const singleChooseItem=()=>{const main=document.getElementById('chooseContainer')?.firstElementChild;if(!main||main.children.length!==1)return null;const outer=main.firstElementChild;return outer&&outer.children.length===1?outer.firstElementChild:null;};const events=[],elastic=[],controlEvents=[];let origin=null,lastCommand='',lastParams={},lastLine=0,done=false,finishedAt=0,manualTimer=null,hintTimer=null,hintError='';
   // A timer queued during a non-blocking wait must not settle a later say.
   let autoGeneration=0;
   const cancelPendingAuto=()=>{autoGeneration++;if(core.gameplay.autoTimeout!=null){clearTimeout(core.gameplay.autoTimeout);core.gameplay.autoTimeout=null;}};
   globalThis.__nativeScheduleAuto=(fn,delay)=>{const generation=autoGeneration,startMs=performance.now()-origin,line=lastLine,eligible=lastCommand==='say'&&!lastParams.notend;return setTimeout(()=>{if(generation!==autoGeneration)return;if(pc.performList.some(p=>p.blockingAuto())){core.gameplay.autoTimeout=null;return;}if(eligible)elastic.push({startMs,endMs:performance.now()-origin,line});fn();},delay);};
   const recordTextSettle=()=>{if(origin!==null&&!done)controlEvents.push({atMs:performance.now()-origin,kind:'text-settle',line:lastLine});};core.events.textSettle.on(recordTextSettle);
   const finish=()=>{done=true;finishedAt=performance.now();w.nativeStopAuto();};
   globalThis.__nativeObserve=s=>{cancelPendingAuto();if(origin===null)origin=performance.now();lastCommand=s.command===0?'say':s.commandRaw;lastParams=Object.fromEntries(s.args.map(a=>[a.key,a.value]));lastLine=core.sceneManager.sceneData.currentSentenceId;events.push({index:lastLine,atMs:performance.now()-origin,command:lastCommand});if(manualTimer){clearTimeout(manualTimer);manualTimer=null;}if(hintTimer){clearTimeout(hintTimer);hintTimer=null;}const hintMs=singleLineHintDuration(s,lastParams);if(hintMs)hintTimer=setTimeout(()=>{hintTimer=null;const item=singleChooseItem();if(!item){hintError='单行提示未能显示唯一选项';return;}item.click();},hintMs);if(lastCommand==='end')finish();};
   const ended=()=>core.sceneManager.sceneData.currentSentenceId>=core.sceneManager.sceneData.currentScene.sentenceList.length;
   globalThis.__nativeBeforeNext=()=>{if(ended()&&!pc.hasBlockingNextPerform()&&!pc.performList.some(p=>p.blockingAuto())){finish();return false;}if(origin!==null)controlEvents.push({atMs:performance.now()-origin,kind:'next'});return true;};
   if(policy.mode==='manual'){
    const arrange=pc.arrangeNewPerform;pc.arrangeNewPerform=function(perform,s,...rest){if(s.command===0&&perform.performName!=='vocal-play'&&!perform.isHoldOn){const params=Object.fromEntries(s.args.map(a=>[a.key,a.value]));if(!params.notend){const n=w.compileText(s.content,3).reduce((sum,a)=>sum+a.length,0);perform.duration=n*w.textDelay(policy.textSpeed)+w.textAnimation(policy.textSpeed);}}return arrange.call(this,perform,s,...rest);};
   }
   document.querySelector('.html-body__title-enter')?.style.setProperty('display','none');
   __probeCommands['preview.command.set-component-visibility']({showStarter:false,isShowLogo:false,showTitle:false,showControls:false,controlsVisibility:false,isEnterGame:true});
   if(typeof globalThis.__gpuDomInstall==='function')globalThis.__gpuDomInstall();__probeCommands['preview.command.run-scene-content']({sceneContent:script});
   await __reportNativePlan({phase:'initializing',checkpoint:'scene-started'});
   let poll;
   if(policy.mode==='auto')w.nativeAuto();
   else poll=setInterval(()=>{if(origin===null||done||manualTimer||pc.performList.some(p=>p.blockingAuto()||p.blockingNext()))return;const delay=lastCommand==='say'&&!lastParams.notend?policy.holdMs:0,begin=performance.now()-origin;manualTimer=setTimeout(()=>{manualTimer=null;if(delay>0)elastic.push({startMs:begin,endMs:performance.now()-origin,line:lastLine});w.nativeNext();},delay);},10);
   let steps=0;const maxSteps=108000;while(!done&&steps++<maxSteps){globalThis.__nativePlanProgress={phase:'advancing',line:lastLine+1,totalLines:core.sceneManager.sceneData.currentScene.sentenceList.length,videoSeconds:origin===null?0:(performance.now()-origin)/1000,events:events.length};await clock.runFor(planStepMs);await yieldTask();if(hintError)throw new Error(hintError);await __exportWaitForStageAssets();sampleDom();if(steps%50===0)await __reportNativePlan({...__nativePlanProgress,phase:'planning-progress',performs:pc.performList.map(p=>({name:p.performName,duration:p.duration,hold:p.isHoldOn}))});}
   core.events.textSettle.off(recordTextSettle);clearInterval(poll);clearTimeout(manualTimer);clearTimeout(hintTimer);w.nativeStopAuto();yieldChannel.port1.close();yieldChannel.port2.close();
   if(!done)throw new Error('播放时序规划超时，场景可能含等待交互的指令');
   return {events,elastic,controlEvents,domWorkload,durationMs:origin===null?0:finishedAt-origin,options:w.store.getState().userData.optionData};
  };
