/* One native timing job per source/settings, shared by the navigator and music configuration. */
const WebVideoTimingTasks=(()=>{
 const running=new Map();let configPromise=null;
 const config=()=>configPromise||(configPromise=WebVideoProject.service('/api/config').finally(()=>{setTimeout(()=>{configPromise=null;},1000);}));
 async function run(model,values,{signal,onProgress,force=false}={}){const P=WebVideoProject,game=model.path.split('/')[1],scene=model.path.split('/game/scene/')[1];if(signal?.aborted)throw Error('计算已取消。');const [cfg,hash]=await Promise.all([config(),P.sha(model.source.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n'))]);if(signal?.aborted)throw Error('计算已取消。');const settings={...cfg.settings,...values,mode:'auto',bgmBaseMode:'auto'},key=JSON.stringify([model.path,hash,settings]);
  let entry=running.get(key);if(!entry||entry.cancelled){entry={users:0,listeners:new Set(),started:Date.now(),job:null,done:false,cancelled:false,progress:{message:'准备计算故事时间',progress:0,elapsed:0}};running.set(key,entry);entry.promise=(async()=>{const report=job=>{entry.progress={message:job.message||job.phase||'正在分析故事',progress:Number(job.progress)||0,elapsed:(Date.now()-entry.started)/1000};for(const fn of entry.listeners)fn(entry.progress);};try{const job=await P.service('/api/timing',{project:game,scene,sourceText:model.source,settings,linearTimeline:true});entry.job=job.id;if(entry.cancelled){await P.service('/api/jobs/'+job.id+'/cancel',{});throw Error('计算已取消。');}for(let i=0;i<3600;i++){if(entry.cancelled)throw Error('计算已取消。');const data=await P.service('/api/timing/'+job.id);report(data.job);if(data.job.state==='completed'){if(data.sourceHash!==hash)throw Error('时间结果与当前故事不一致。');const seconds=Number(data.timing.durationSeconds);if(!Number.isFinite(seconds)||seconds<0)throw Error('无效的故事时长。');const dependencyHash=data.timing?.storyTimeline?.dependencyHash;if(dependencyHash)(window.WebVideoValidatedStoryTimings??=new Set()).add(dependencyHash);return {seconds,timing:data.timing,settings,sourceHash:hash};}if(['failed','needs_attention','canceled'].includes(data.job.state))throw Error(data.job.message||'计算失败。');await new Promise(resolve=>setTimeout(resolve,500));}throw Error('故事计算超时。');}finally{entry.done=true;if(running.get(key)===entry)running.delete(key);}})();entry.promise.catch(()=>{});}
  entry.users++;if(onProgress){entry.listeners.add(onProgress);onProgress(entry.progress);}let abort;
  try{return await new Promise((resolve,reject)=>{abort=()=>reject(Error('计算已取消。'));signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)return abort();entry.promise.then(resolve,reject);});}finally{signal?.removeEventListener('abort',abort);if(onProgress)entry.listeners.delete(onProgress);entry.users--;if(!entry.done&&entry.users===0){entry.cancelled=true;if(entry.job)P.service('/api/jobs/'+entry.job+'/cancel',{}).catch(()=>{});}}
 }
 return {run};
})();
window.WebVideoTimingTasks=WebVideoTimingTasks;
