const WebVideoTools=(()=>{
 const panels=new Map(),decorators=new Map(),listeners=new Set(),closeGuards=new Map();let active=null,picking=false,context={},windowOverlay=null,overlayOwner=null;const emit=()=>listeners.forEach(fn=>fn());
 const api={modules:__WEBVIDEO_MODULES__,register(id,title,component){panels.set(id,{title,component});},registerDecorator(id,fn){decorators.set(id,fn);},decorate(model){if(!model)return [];let rows=model.rows;for(const fn of decorators.values())rows=fn(model,rows,WebVideoProject.state().project);return rows;},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},state(){return {active,picking,panel:panels.get(active),context,windowOverlay};},setContext(value){context=value;},setWindowOverlay(owner,node){if(active===owner||overlayOwner===owner){windowOverlay=node;overlayOwner=node?owner:null;emit();}},open(id){if(!panels.has(id))return;active=id;emit();},close(){if(WebVideoProject.state().busy||closeGuards.get(active)?.()===false)return;active=null;windowOverlay=null;overlayOwner=null;emit();},registerCloseGuard(id,fn){closeGuards.set(id,fn);return()=>{if(closeGuards.get(id)===fn)closeGuards.delete(id);};},async select(mode='set'){picking=true;emit();try{return await WebVideoPlus.requestSelection({mode});}finally{picking=false;emit();}},emit};window.WebVideoTools=api;return api;
})();
function WebVideoToolsHost(){
 const R=reactExports,h=R.createElement,P=WebVideoProject,T=WebVideoTools;
 const game=useEditorStore.use.subPage(),dark=useEditorStore.use.isDarkMode(),tag=useGameEditorContext(s=>s.currentTag),tags=useGameEditorContext(s=>s.tags),addTag=useGameEditorContext(s=>s.addTag),setTag=useGameEditorContext(s=>s.updateCurrentTag),showSidebar=useGameEditorContext(s=>s.updateIsShowSidebar);
 const [,refresh]=R.useReducer(n=>n+1,0),ref=R.useRef(null);
 R.useEffect(()=>T.subscribe(refresh),[]);R.useEffect(()=>P.subscribe(refresh),[]);R.useEffect(()=>WebVideoPlus.subscribe(refresh),[]);
 R.useEffect(()=>{P.activate(game);return()=>T.close();},[game]);
 const openScene=name=>{const existing=tags.find(t=>t.path==='scene/'+name||t.path===`games/${game}/game/scene/${name}`),next=existing||{type:'scene',path:'scene/'+name,name:name.split('/').pop()};if(!existing)addTag(next);setTag(next);};
 T.setContext({game,tag,openScene,showPreview(){showSidebar(true);useEditorStore.getState().updateIsShowPreview(true);}});
 const state=T.state(),projectState=P.state(),opened=!!state.panel&&!state.picking;
 R.useEffect(()=>{if(!opened)return;const previous=document.activeElement;ref.current?.querySelector('.wvp-tool-content button,.wvp-tool-content input,.wvp-tool-content textarea,.wvp-tool-content select')?.focus();const key=e=>{if(e.isComposing)return;if(e.key==='Escape'){e.preventDefault();T.close();}if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button,input,textarea,select,[tabindex="0"]')].filter(n=>!n.disabled&&n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[opened,state.active]);
 return h(R.Fragment,null,!!state.panel&&h('div',{className:'wvp-overlay','data-theme':dark?'dark':'light',style:state.picking?{display:'none'}:undefined,'aria-hidden':state.picking||undefined},h('section',{className:'wvp-dialog wvp-tool-dialog'+(state.active==='idTools'?' wvp-id-dialog':state.active==='backups'?' wvp-backup-dialog':['expressionPrep','batchNext','autoExit','filterEdit','presetEffects'].includes(state.active)?' wvp-expression-dialog':state.active==='filter'?' wvp-filter-dialog':state.active==='musicTimeline'?' wvp-export-music-dialog':''),role:'dialog','aria-modal':true,'aria-labelledby':'wvp-tool-title',ref},h('header',null,h('div',null,h('h2',{id:'wvp-tool-title'},state.panel.title),h('p',{className:'wvp-tool-intro'},({novelImport:'两轮生成正文骨架与基础舞台；最多两人，不填表情动作，不添加特效。先核对结果，再追加到当前故事。',filterEdit:'选择已有滤镜后更换或删除，只修改原滤镜覆盖的参数，保留语句的其他效果。',presetEffects:'展开分类选择效果，可调整单目标效果的目标，默认插入故事末尾。',presetManage:'追加命名的演出语句，保存在所有游戏共用的预制效果库。',autoExit:'同一位置换入不同立绘文件或不同 ID 的角色时，在登场前补充离场。默认全文，可选择特定登场项；修改前自动备份。',batchNext:'为所选语句补充 -next（连续执行），已有参数保持不变。默认处理当前故事全文，普通对话默认不选，全屏文字不参与。',expressionPrep:'在选中的对话前复制对应的切换立绘，供逐句调整表情。默认会忽略已设定表情变化的语句',filter:'选择背景和人物滤镜，再选择要追加效果的组件。只保存效果片段，目标和时序由工具自动设置。',batchTools:'表情与滤镜工具。',idTools:'利用默认映射表为所有需要的语句追加id。您可以在配置窗口编辑默认映射表。',videoWorkflow:'检查播放时间，逐句预览，或把选中片段导出为视频。',musicTimeline:'音乐保持原始长度；同一播放器行顺序播放，增加播放器行可并行播放。',textImport:'追加到当前故事末尾，导入前自动备份。',checks:'查看制作提醒，标记还需要调整的剧情。',backups:'选择备份，确认后回滚。当前内容会自动备份。'})[state.active]||'')),h('div',{className:'wvp-tool-header-actions'},__WEBVIDEO_MODULES__.includes('backups')&&!['backups','idTools','expressionPrep','filter','batchNext','autoExit','filterEdit','presetEffects','presetManage','novelImport','textImport','musicTimeline'].includes(state.active)&&h('button',{type:'button',onClick:()=>T.open('backups')},'备份与恢复'),h('button',{type:'button',disabled:projectState.busy,onClick:()=>T.close()},'关闭'))),projectState.error&&h('p',{className:'wvp-notice',role:'alert'},projectState.error),h('div',{className:'wvp-tool-content',key:state.active},projectState.loading?h('p',null,'正在读取项目设置…'):projectState.error?h('p',null,'请修复配置后重新打开项目。'):h(state.panel.component)),state.windowOverlay)),null);
}
const WebVideoForm={
 h:(...args)=>reactExports.createElement(...args),
 button(label,action,props={}){return reactExports.createElement('button',{type:'button',onClick:action,...props},label);},
 field(label,control){return reactExports.createElement('label',{className:'wvp-tool-field'},reactExports.createElement('span',null,label),control);},
 notice(text){return text&&reactExports.createElement('p',{className:'wvp-tool-status',role:'status'},text);},
 selection(selection,choose){const h=reactExports.createElement;return h('div',{className:'wvp-tool-selection'},h('div',{className:'wvp-selection-copy'},h('strong',null,selection?`已选 ${selection.ids.length} 个剧情事件`:'选择要处理的剧情'),h('small',null,selection?(selection.mode==='range'?'从第 '+selection.ranges[0].startLine+' 行到第 '+selection.ranges[0].endLine+' 行':'仅修改已勾选的剧情'):'可以圈选一段，也可以挑选多句。')),this.button(selection?'重新选择':'选择剧情',choose));},
 preview(plan){const h=reactExports.createElement;return plan&&h('section',{className:'wvp-change-preview'},h('strong',null,`影响预览 · ${plan.changed??plan.patches?.length??1} 处修改`),plan.warnings?.length>0&&h('ul',null,...plan.warnings.map((x,i)=>h('li',{key:i},x))),h('div',{className:'wvp-diff'},h('div',null,h('span',null,'修改前'),h('pre',null,plan.before)),h('div',null,h('span',null,'修改后'),h('pre',null,plan.after))));}
};
