using System;using System.Linq;using System.Collections.Generic;
namespace NativeVideo {
 public static class ModuleCatalog {
  public static readonly string[] Selectable={"timelineNavigator","timelineSelector","videoWorkflow","idTools","expressionPrep","filter","filterEdit","batchNext","autoExit","presetEffects","musicTimeline","textImport","checks","backups","exporter","compactGameTools","generativeAI"};
  public static readonly string[] Advanced=Selectable.Where(id=>id!="generativeAI").ToArray();
  public static readonly Dictionary<string,string> Labels=new Dictionary<string,string>{{"generativeAI","安装基于生成式AI的组件"},{"timelineNavigator","剧情导航"},{"timelineSelector","导出片段选择"},{"videoWorkflow","剧情实际时间"},{"idTools","一键id补全"},{"expressionPrep","预位表情调整"},{"filter","批量滤镜"},{"filterEdit","修改已有滤镜"},{"batchNext","批量加-next"},{"autoExit","自动离场"},{"presetEffects","Video+预制效果"},{"musicTimeline","配置导出音乐"},{"textImport","导入Anogo故事"},{"checks","检查与标记"},{"backups","备份与恢复 / 自动备份"},{"exporter","导出视频"},{"compactGameTools","游戏工具收纳"},{"timelineCore","时间线基础"},{"projectCore","编辑工具基础"},{"exportKernel","本机服务与导出内核"}};
  static readonly Dictionary<string,string[]> Dependencies=new Dictionary<string,string[]>{{"generativeAI",new[]{"backups"}},{"timelineNavigator",new[]{"timelineCore"}},{"timelineSelector",new[]{"timelineCore"}},{"exporter",new[]{"exportKernel","timelineSelector"}},{"idTools",new[]{"backups"}},{"expressionPrep",new[]{"backups"}},{"filter",new[]{"backups"}},{"filterEdit",new[]{"backups"}},{"batchNext",new[]{"backups"}},{"autoExit",new[]{"backups"}},{"presetEffects",new[]{"backups"}},{"musicTimeline",new[]{"backups"}},{"textImport",new[]{"backups"}},{"checks",new[]{"projectCore","timelineSelector"}},{"backups",new[]{"projectCore","exportKernel"}},{"videoWorkflow",new[]{"projectCore","timelineSelector","timelineNavigator","exportKernel"}},{"projectCore",new[]{"timelineCore"}},{"compactGameTools",new string[0]},{"timelineCore",new string[0]},{"exportKernel",new string[0]}};
  public static string[] Normalize(IEnumerable<string> requested){var old=requested.Distinct().ToArray();var list=old.SelectMany(id=>id=="batchTools"?new[]{"expressionPrep","filter","filterEdit","batchNext","autoExit","presetEffects","backups"}:id=="projectCore"?new[]{"backups"}:new[]{id}).Where(id=>id!="timelineCore"&&id!="exportKernel").Distinct().ToArray();if(list.Except(Selectable).Any())throw new ArgumentException("存在未知或不可直接选择的模块");return list;}
  public static string[] Resolve(IEnumerable<string> requested){var list=Normalize(requested);var resolved=new HashSet<string>();Action<string> add=null;add=id=>{if(resolved.Add(id))foreach(var dependency in Dependencies[id])add(dependency);};foreach(var id in list)add(id);return Selectable.Concat(new[]{"timelineCore","projectCore","exportKernel"}).Where(resolved.Contains).ToArray();}
  public static bool NeedsKernel(IEnumerable<string> modules){return modules.Contains("exportKernel")||modules.Contains("exporter")||modules.Contains("videoWorkflow");}
  public static Dictionary<string,string[]> Graph(){return new Dictionary<string,string[]>(Dependencies);}
 }
}
