import fs from 'node:fs';
import { WebVideoNovel } from './novel-core.mjs';
import { randomUUID } from 'node:crypto';
import { Context } from '@deepseek-ai/cordis';
import LlmRuntime, { createUserMessage, APP_IDENTITY } from '@deepseek-ai/dsh-llm';
import * as LlmPiAi from '@deepseek-ai/dsh-llm-pi-ai';
const input=JSON.parse(await new Promise((resolve,reject)=>{let text='';process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{text+=chunk;if(text.length>24000000)reject(Error('INPUT_TOO_LARGE'));});process.stdin.on('end',()=>resolve(text));}));
const version=JSON.parse(fs.readFileSync(new URL('./package.json',import.meta.url),'utf8').replace(/^\uFEFF/,'')).version;
APP_IDENTITY.product='webvideo-plus';APP_IDENTITY.version=version;
const sessionId=/^[a-f0-9-]{36}$/i.test(input.sessionId||'')?input.sessionId:randomUUID();
const nativeFetch=globalThis.fetch;
globalThis.fetch=(resource,options={})=>{const url=new URL(typeof resource==='string'?resource:resource.url||String(resource));if(url.hostname==='opencode.ai'&&/^\/zen(?:\/|$)/.test(url.pathname)){const headers=new Headers(options.headers||resource.headers);headers.set('user-agent','webvideo-plus/'+version);headers.set('x-opencode-session',sessionId);options={...options,headers};}return nativeFetch(resource,options);};
function redact(value){let text=String(value??'');for(const secret of [input.key,encodeURIComponent(input.key||''),Buffer.from(input.key||'').toString('base64')].filter(Boolean))text=text.split(secret).join('[已隐藏]');return text.replace(/Bearer\s+[^\s,"'}]+/gi,'Bearer [已隐藏]').replace(/(["']?(?:authorization|x-api-key|api[_-]?key|secret|token)["']?\s*[:=]\s*)(?:"[^"]*"|'[^']*'|[^\s,;}]+)/gi,'$1[已隐藏]').replace(/https?:\/\/[^\s"']+/g,url=>url.split('?')[0]).replace(/[\x00-\x1f]+/g,' ').slice(0,700);}
let ctx;
try{
 if(!['models','test','novel','stage'].includes(input.action))throw Error('UNKNOWN_ACTION');
 process.env.WEBVIDEO_AI_KEY=input.key;ctx=new Context();await ctx.plugin(LlmRuntime);
 const known=input.provider!=='custom',route=known?input.provider:'webvideo-custom',isGo=new URL(input.baseURL).hostname==='opencode.ai';
 const profile={apiKeyEnv:'WEBVIDEO_AI_KEY',baseURL:input.baseURL,retryPolicy:{mode:'normal',maxRetries:0},...(['novel','stage'].includes(input.action)?{timeoutMs:3600000,streamIdleTimeoutMs:3600000,defaultMaxTokens:272000}:{}),...(isGo?{headers:{'x-opencode-session':sessionId}}:{})};
 if(!known||input.apiOverride)profile.api=input.api;
 if(input.model)profile.models=[{id:input.model,api:input.api}];
 if(!known&&!profile.models)profile.models=[{id:'connection-check',api:input.api}];
 await ctx.plugin(LlmPiAi,{providers:{[route]:profile}});const signal=AbortSignal.timeout(input.action==='novel'?3600000:45000);
 if(input.action==='models'){
   const listingBase=input.provider==='opencode-go'&&new URL(input.baseURL).hostname==='opencode.ai'?'https://opencode.ai/zen/go/v1':input.baseURL;
   let models;
   if(['google-generative-ai','mistral-conversations'].includes(input.api)){
     models=[];let page='';const seenPages=new Set();do{const root=listingBase.replace(/\/$/,'');const url=new URL(root+(input.api==='mistral-conversations'&&!root.endsWith('/v1')?'/v1':'')+'/models');if(input.api==='google-generative-ai'){url.searchParams.set('pageSize','1000');if(page)url.searchParams.set('pageToken',page);}const response=await fetch(url,{headers:input.api==='google-generative-ai'?{'x-goog-api-key':input.key,'user-agent':'webvideo-plus/'+version}:{Authorization:'Bearer '+input.key,'user-agent':'webvideo-plus/'+version},signal});if(!response.ok)throw Object.assign(Error('模型目录读取失败'),{status:response.status,code:'DISCOVERY_FAILED'});const body=await response.json();if(input.api==='google-generative-ai'){if(!Array.isArray(body.models))throw Error('模型目录格式无效');models.push(...body.models.filter(m=>m.supportedGenerationMethods?.includes('generateContent')).map(m=>({id:m.name.replace(/^models\//,''),name:m.displayName||m.name})));}else{if(!Array.isArray(body.data))throw Error('模型目录格式无效');models.push(...body.data.filter(m=>m.id).map(m=>({id:m.id,name:m.name||m.id})));}page=input.api==='google-generative-ai'?body.nextPageToken||'':'';if(page&&seenPages.has(page))throw Error('模型目录返回重复分页');seenPages.add(page);if(models.length>10000)throw Error('模型目录超过上限');}while(page);
   }else models=await ctx.llm.discoverModels('llm-pi-ai',{baseURL:listingBase,api:input.provider==='opencode-go'?'openai-completions':input.api,apiKey:input.key},signal);
   const catalog=JSON.parse(fs.readFileSync(new URL('./providers.json',import.meta.url),'utf8')).providers.find(p=>p.id===input.provider),mixed=new Set((catalog?.models||[]).map(m=>m.api)).size>1;
   process.stdout.write(JSON.stringify({ok:true,models:models.map(m=>{const metadata=catalog?.models.find(row=>row.id===m.id);return {id:m.id,name:m.name||metadata?.name||m.id,...(metadata?{api:metadata.api,baseURL:metadata.baseURL}:!mixed?{api:input.api,baseURL:input.baseURL}:{needsProtocol:true})};})}));
 }else if(input.action==='novel'){
   if(!Array.isArray(input.units)||input.units.map(u=>u.text).join('')!==input.source)throw Error('原文范围不一致');
   const system=fs.readFileSync(new URL('./novel-prompt.txt',import.meta.url),'utf8')+'\n长文分批：只标注本批units；beforeContext/afterContext仅供理解，不可输出为本批片段。';const batches=[];let start=0,chars=0;for(let i=0;i<input.units.length;i++){chars+=input.units[i].text.length;if(chars>=3000||i-start>=179){batches.push([start,i+1]);start=i+1;chars=0;}}if(start<input.units.length)batches.push([start,input.units.length]);const segments=[],cast=new Set();
   for(let batch=0;batch<batches.length;batch++){const [from,to]=batches[batch],units=input.units.slice(from,to).map((u,id)=>({id,text:u.text}));process.stdout.write(JSON.stringify({type:'progress',completed:batch,total:batches.length})+'\n');let text='',finish;
    for(let attempt=0;attempt<2;attempt++){text='';finish=null;try{
    for await(const chunk of ctx.llm.stream({provider:route,model:input.model,sessionId,system,messages:[createUserMessage({content:[{type:'text',text:JSON.stringify({units,knownSpeakers:input.knownSpeakers||[],beforeContext:input.units.slice(Math.max(0,from-12),from).map(u=>u.text).join(''),afterContext:input.units.slice(to,to+8).map(u=>u.text).join('')})}],source:{kind:'plugin',plugin:'webvideo-novel-structure'}})],signal})){if(chunk.type==='text-delta')text+=chunk.text;if(chunk.type==='finish')finish=chunk.reason;}
    if(finish?.kind!=='stop'){const kind=finish?.kind||'missing-finish',detail=kind==='max-tokens'?'达到模型或服务商的输出限制，返回内容被截断。':kind==='aborted'?'请求被中止。':'返回未完整结束（'+kind+'）。';throw Object.assign(Error(finish?.failure?.message||'第 '+(batch+1)+' 批：'+detail+'剧本未改动。'),{code:finish?.failure?.code||(kind==='max-tokens'?'MODEL_OUTPUT_LIMIT':'INCOMPLETE_OUTPUT'),status:finish?.failure?.status});}
     break;
    }catch(error){if(attempt===1||signal.aborted||[400,401,403,404,429].includes(Number(error.status))||/QUOTA|CREDENTIAL|AUTH|UNKNOWN_MODEL|INVALID_CONFIG/.test(String(error.code||'')))throw error;process.stdout.write(JSON.stringify({type:'progress',completed:batch,total:batches.length,retrying:true})+'\n');await new Promise(resolve=>setTimeout(resolve,1000));signal.throwIfAborted();}}
    const trimmed=text.trim().replace(/^```(?:json)?\s*\n([\s\S]*?)\n```$/,'$1');let result;try{result=JSON.parse(trimmed);}catch{throw Error('第 '+(batch+1)+' 批返回格式无效，未改动剧本。');}WebVideoNovel.resolve({source:input.source,units,knownSpeakers:input.knownSpeakers||[]},result);if(!Array.isArray(result.cast))throw Error('模型没有返回在场角色名单。');for(const name of result.cast){if(typeof name!=='string'||!name.trim()||!input.source.includes(name))throw Error('角色名单引用了原文不存在的名字。');cast.add(name);}segments.push(...result.segments.map(row=>({...row,from:row.from+from,to:row.to+from})));process.stdout.write(JSON.stringify({type:'progress',completed:batch+1,total:batches.length})+'\n');
   }
   WebVideoNovel.resolve({source:input.source,units:input.units,knownSpeakers:input.knownSpeakers||[]},{segments});process.stdout.write(JSON.stringify({ok:true,segments,cast:[...cast]}));
 }else if(input.action==='stage'){
   const prepared={source:input.source,units:input.units,knownSpeakers:input.knownSpeakers||[]},resolved=WebVideoNovel.resolve(prepared,{segments:input.segments}),all=resolved.rows.map((r,at)=>({at,text:r.text,speaker:r.speaker,kind:r.kind,sceneBreak:r.sceneBreak})),changes=[];
   const system=fs.readFileSync(new URL('./stage-prompt.txt',import.meta.url),'utf8');let previousState={background:null,cast:[]};const total=Math.ceil(all.length/45);
   for(let batch=0;batch<total;batch++){const rows=all.slice(batch*45,(batch+1)*45);let text='',finish;process.stdout.write(JSON.stringify({type:'progress',completed:batch,total})+'\n');
    for(let attempt=0;attempt<2;attempt++){text='';finish=null;try{for await(const chunk of ctx.llm.stream({provider:route,model:input.model,sessionId,system,messages:[createUserMessage({content:[{type:'text',text:JSON.stringify({rows,actors:input.stageAssets.actors,backgrounds:input.stageAssets.backgrounds,maxActors:input.maxActors,previousState})}],source:{kind:'plugin',plugin:'webvideo-basic-stage'}})],signal})){if(chunk.type==='text-delta')text+=chunk.text;if(chunk.type==='finish')finish=chunk.reason;}if(finish?.kind!=='stop')throw Object.assign(Error(finish?.failure?.message||'舞台安排输出未完整结束'),{code:finish?.failure?.code||finish?.kind,status:finish?.failure?.status});break;}catch(error){if(attempt===1||signal.aborted||[400,401,403,404,429].includes(Number(error.status)))throw error;process.stdout.write(JSON.stringify({type:'progress',completed:batch,total,retrying:true})+'\n');}}
    let output;try{output=JSON.parse(text.trim().replace(/^```(?:json)?\s*\n([\s\S]*?)\n```$/,'$1'));}catch{throw Error('舞台安排格式无效，未改动剧本。');}WebVideoNovel.validateStage({assets:input.stageAssets,changes:output.changes,maxActors:input.maxActors},all.length,rows[0]?.at??0,rows.at(-1)?.at??0,batch===0);changes.push(...output.changes);for(const change of output.changes)previousState={background:change.background??previousState.background,cast:change.cast};process.stdout.write(JSON.stringify({type:'progress',completed:batch+1,total})+'\n');
   }
   process.stdout.write(JSON.stringify({ok:true,changes})); }else{
   let text='',finish=null;for await(const chunk of ctx.llm.stream({provider:route,model:input.model,sessionId,messages:[createUserMessage({content:[{type:'text',text:'Reply with OK only to confirm API connectivity for the WebVideo+ WebGAL script editor.'}],source:{kind:'plugin',plugin:'webvideo-connection-check'}})],maxTokens:256,signal})){if(chunk.type==='text-delta')text+=chunk.text;if(chunk.type==='finish')finish=chunk.reason;}
   if(finish?.kind==='error'||finish?.kind==='aborted'){const failure=finish.failure||{};throw Object.assign(new Error(failure.message||'PROVIDER_ERROR'),{code:failure.code,status:failure.status});}
   if(!text.trim())throw Object.assign(Error('模型没有返回文本，可能在输出限额内只返回了推理内容。'),{code:'EMPTY_RESPONSE'});
   process.stdout.write(JSON.stringify({ok:true,message:'连接成功，模型已响应。'}));
 }
}catch(error){const code=redact(error?.code||'CONNECTION_FAILED'),detail=redact(error?.message||'请求未完成'),status=Number(error?.status||error?.statusCode)||Number(String(error?.message||'').match(/(?:answered|HTTP|status)\s*[:=]?\s*([45]\d{2})/i)?.[1])||null;const text=code+' '+detail;const hint=status===401||/AUTH|CREDENTIAL/i.test(code)?'认证失败':status===403?'访问被拒绝':status===404?'模型或接口不存在':status===429||/QUOTA|RATE_LIMIT/i.test(code)?'额度或请求频率受限':/timeout|abort/i.test(text)?'请求超时或中止':'连接未完成';process.stdout.write(JSON.stringify({ok:false,error:hint+(status?'（HTTP '+status+'）':'')+' ['+code+']：'+detail,status,code}));process.exitCode=1;
}finally{delete process.env.WEBVIDEO_AI_KEY;await ctx?.dispose();}
