import fs from 'node:fs';
import { WebVideoNovel } from './novel-core.mjs';
import { randomUUID } from 'node:crypto';
import { Context } from '@deepseek-ai/cordis';
import LlmRuntime, { createUserMessage, APP_IDENTITY } from '@deepseek-ai/dsh-llm';
import * as LlmPiAi from '@deepseek-ai/dsh-llm-pi-ai';
const input=JSON.parse(await new Promise((resolve,reject)=>{let text='';process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{text+=chunk;if(text.length>24000000)reject(Error('INPUT_TOO_LARGE'));});process.stdin.on('end',()=>resolve(text));}));
const version=JSON.parse(fs.readFileSync(new URL('./package.json',import.meta.url),'utf8').replace(/^\uFEFF/,'')).version;
APP_IDENTITY.product='webvideo-plus';APP_IDENTITY.version=version;
const sessionId=/^[a-f0-9-]{36}$/i.test(input.sessionId||'')?input.sessionId:randomUUID();
const nativeFetch=globalThis.fetch;
globalThis.fetch=(resource,options={})=>{const url=new URL(typeof resource==='string'?resource:resource.url||String(resource));if(url.hostname==='opencode.ai'&&/^\/zen(?:\/|$)/.test(url.pathname)){const headers=new Headers(options.headers||resource.headers);headers.set('user-agent','webvideo-plus/'+version);headers.set('x-opencode-session',sessionId);options={...options,headers};}return nativeFetch(resource,options);};
function redact(value){let text=String(value??'');for(const secret of [input.key,encodeURIComponent(input.key||''),Buffer.from(input.key||'').toString('base64')].filter(Boolean))text=text.split(secret).join('[已隐藏]');return text.replace(/Bearer\s+[^\s,"'}]+/gi,'Bearer [已隐藏]').replace(/(["']?(?:authorization|x-api-key|api[_-]?key|secret|token)["']?\s*[:=]\s*)(?:"[^"]*"|'[^']*'|[^\s,;}]+)/gi,'$1[已隐藏]').replace(/https?:\/\/[^\s"']+/g,url=>url.split('?')[0]).replace(/[\x00-\x1f]+/g,' ').slice(0,700);}
function refusalText(value){return /content[_ -]?filter|content policy|safety|moderation|refus(?:e|ed|al)?|cannot comply|can't comply|cannot assist|can't assist|not able to assist|policy violation|unsafe|prohibited|blocked by|sensitive content|拒绝|拒答|内容过滤|安全策略|安全政策|无法协助|不能协助|无法帮助|不能帮助|不予回答/i.test(String(value??''));}
function finishError(finish,signal,fallback){const kind=finish?.kind||'missing-finish',failure=finish?.failure||{};let code=failure.code||fallback?.code||'INCOMPLETE_OUTPUT',message=failure.message||fallback?.message||'模型响应未完整结束。';if(kind==='max-tokens'){code='MODEL_OUTPUT_LIMIT';message='达到模型或服务商的输出限制，返回内容被截断。';}else if(kind==='aborted'&&signal.aborted){code='TIMEOUT';message='模型响应超过本次请求的等待上限。';}else if(kind==='aborted'&&!failure.code)code='ABORTED';return Object.assign(Error(message),{code,status:failure.status,requestId:failure.requestId,providerRetryAfterMs:failure.providerRetryAfterMs,finishKind:kind});}
function failureFacts(error){const failure=error?.failure||{};return {code:String(error?.code||failure.code||'CONNECTION_FAILED'),detail:String(error?.message||failure.message||'请求未完成'),status:Number(error?.status||failure.status)||null,requestId:String(error?.requestId||failure.requestId||''),retryAfterMs:Number(error?.providerRetryAfterMs||failure.providerRetryAfterMs)||null,finishKind:String(error?.finishKind||'')};}
function describeFailure(error){const facts=failureFacts(error),text=(facts.code+' '+facts.detail+' '+facts.finishKind).toLowerCase();let category='AI请求失败',advice='';if(refusalText(text)){category='模型拒答或内容过滤';advice='模型或服务商的安全策略主动终止了这次生成，可调整输入或更换模型后重试。';}else if(/TIMEOUT|DEADLINE/.test(facts.code)||/timeout|timed out|deadline|超时/.test(text)){category='请求超时';advice='模型或服务商在等待时间内没有完成响应。';}else if(/ABORTED|CANCELLED|CANCELED/.test(facts.code)||/\babort(?:ed)?\b|cancelled|canceled/.test(text)){category='请求被中止';advice='这不是本地判定的超时，通常表示服务商、SDK 或上游连接主动结束了请求。';}else if(/AUTH|INVALID_CREDENTIAL|MISSING_CREDENTIAL/.test(facts.code)||facts.status===401||facts.status===403){category='认证或访问失败';advice='请检查 API Key、模型权限和服务商账户状态。';}else if(/QUOTA/.test(facts.code)||/quota|credits|balance|insufficient[_ -]?fund/.test(text)){category='额度不足';advice='服务商报告额度、余额或信用不足。';}else if(/RATE_LIMIT/.test(facts.code)||facts.status===429){category='请求频率受限';advice=facts.retryAfterMs?'服务商建议约 '+Math.ceil(facts.retryAfterMs/1000)+' 秒后重试。':'稍后重试，或降低并发/请求频率。';}else if(/CONTEXT_WINDOW_EXCEEDED|CONTEXT_LENGTH/.test(facts.code)||/context.{0,24}(?:limit|length|window|too long)|上下文/.test(text)){category='上下文超限';advice='输入超过该模型可接受的上下文长度，请减少单次输入或换用更长上下文模型。';}else if(/MODEL_OUTPUT_LIMIT|MAX_TOKENS/.test(facts.code)||facts.finishKind==='max-tokens'){category='输出达到上限';advice='模型输出被截断；可减小单批内容或提高服务商允许的输出上限。';}else if(/EMPTY_RESPONSE/.test(facts.code)){category='模型未返回可见文本';advice='模型可能只输出了推理内容，或服务商静默过滤了正文。';}else if(/TRANSPORT|ECONN|ENOTFOUND|TLS|NETWORK/.test(facts.code)||/network|socket|dns|tls|proxy|connection reset|连接/.test(text)){category='网络或代理连接失败';advice='请检查网络、代理、服务商连通性后重试。';}else if(/STREAM_CLOSED|MALFORMED_RESPONSE|PROTOCOL|INVALID_MODEL_OUTPUT/.test(facts.code)){category='服务商响应格式异常';advice='上游流式响应提前结束或返回了本工具无法解析的格式。';}else if(/SERVER/.test(facts.code)||facts.status>=500){category='服务商内部错误';advice='通常是上游暂时故障，可稍后重试。';}else if(facts.status===404||/UNKNOWN_MODEL|MODEL_NOT_FOUND|NOT_FOUND/.test(facts.code)){category='模型或接口不存在';advice='请核对模型名、基础地址和协议。';}else if(/INVALID_REQUEST/.test(facts.code)||facts.status===400){category='请求被服务商拒绝';advice='请求参数、协议或模型能力与服务商要求不一致。';}
 const meta=[];if(facts.code)meta.push('代码 '+redact(facts.code));if(facts.status)meta.push('HTTP '+facts.status);if(facts.requestId)meta.push('请求ID '+redact(facts.requestId));const detail=redact(facts.detail),errorText=category+(meta.length?'（'+meta.join(' · ')+'）':'')+'：'+detail+(advice?' '+advice:'');return {...facts,category,error:errorText};}
function invalidModelOutput(message,text,code='INVALID_MODEL_OUTPUT'){const preview=redact(text).slice(0,260);return Object.assign(Error(message+(preview?' 模型返回开头：'+preview:'')),{code});}
let ctx;
try{
 if(!['models','test','novel','stage'].includes(input.action))throw Error('UNKNOWN_ACTION');
 process.env.WEBVIDEO_AI_KEY=input.key;ctx=new Context();await ctx.plugin(LlmRuntime);
 const known=input.provider!=='custom',route=known?input.provider:'webvideo-custom',isGo=new URL(input.baseURL).hostname==='opencode.ai',longAction=['novel','stage'].includes(input.action);
 const profile={apiKeyEnv:'WEBVIDEO_AI_KEY',baseURL:input.baseURL,retryPolicy:{mode:'normal',maxRetries:0},...(longAction?{timeoutMs:3600000,streamIdleTimeoutMs:3600000,defaultMaxTokens:272000}:{}),...(isGo?{headers:{'x-opencode-session':sessionId}}:{})};
 if(!known||input.apiOverride)profile.api=input.api;
 if(input.model)profile.models=[{id:input.model,api:input.api}];
 if(!known&&!profile.models)profile.models=[{id:'connection-check',api:input.api}];
 await ctx.plugin(LlmPiAi,{providers:{[route]:profile}});const signal=AbortSignal.timeout(longAction?3600000:45000);
 if(input.action==='models'){
   const listingBase=input.provider==='opencode-go'&&new URL(input.baseURL).hostname==='opencode.ai'?'https://opencode.ai/zen/go/v1':input.baseURL;
   let models;
   if(['google-generative-ai','mistral-conversations'].includes(input.api)){
     models=[];let page='';const seenPages=new Set();do{const root=listingBase.replace(/\/$/,'');const url=new URL(root+(input.api==='mistral-conversations'&&!root.endsWith('/v1')?'/v1':'')+'/models');if(input.api==='google-generative-ai'){url.searchParams.set('pageSize','1000');if(page)url.searchParams.set('pageToken',page);}const response=await fetch(url,{headers:input.api==='google-generative-ai'?{'x-goog-api-key':input.key,'user-agent':'webvideo-plus/'+version}:{Authorization:'Bearer '+input.key,'user-agent':'webvideo-plus/'+version},signal});if(!response.ok)throw Object.assign(Error('模型目录读取失败'),{status:response.status,code:'DISCOVERY_FAILED'});const body=await response.json();if(input.api==='google-generative-ai'){if(!Array.isArray(body.models))throw Error('模型目录格式无效');models.push(...body.models.filter(m=>m.supportedGenerationMethods?.includes('generateContent')).map(m=>({id:m.name.replace(/^models\//,''),name:m.displayName||m.name})));}else{if(!Array.isArray(body.data))throw Error('模型目录格式无效');models.push(...body.data.filter(m=>m.id).map(m=>({id:m.id,name:m.name||m.id})));}page=input.api==='google-generative-ai'?body.nextPageToken||'':'';if(page&&seenPages.has(page))throw Error('模型目录返回重复分页');seenPages.add(page);if(models.length>10000)throw Error('模型目录超过上限');}while(page);
   }else models=await ctx.llm.discoverModels('llm-pi-ai',{baseURL:listingBase,api:input.provider==='opencode-go'?'openai-completions':input.api,apiKey:input.key},signal);
   const catalog=JSON.parse(fs.readFileSync(new URL('./providers.json',import.meta.url),'utf8')).providers.find(p=>p.id===input.provider),mixed=new Set((catalog?.models||[]).map(m=>m.api)).size>1;
   process.stdout.write(JSON.stringify({ok:true,models:models.map(m=>{const metadata=catalog?.models.find(row=>row.id===m.id);return {id:m.id,name:m.name||metadata?.name||m.id,...(metadata?{api:metadata.api,baseURL:metadata.baseURL}:!mixed?{api:input.api,baseURL:input.baseURL}:{needsProtocol:true})};})}));
 }else if(input.action==='novel'){
   if(!Array.isArray(input.units)||input.units.map(u=>u.text).join('')!==input.source)throw Error('原文范围不一致');
   const system=fs.readFileSync(new URL('./novel-prompt.txt',import.meta.url),'utf8')+'\n长文分批：只标注本批units；beforeContext/afterContext仅供理解，不可输出为本批片段。';const batches=[];let start=0,chars=0;for(let i=0;i<input.units.length;i++){chars+=input.units[i].text.length;if(chars>=3000||i-start>=179){batches.push([start,i+1]);start=i+1;chars=0;}}if(start<input.units.length)batches.push([start,input.units.length]);const segments=[],cast=new Set();
   for(let batch=0;batch<batches.length;batch++){const [from,to]=batches[batch],units=input.units.slice(from,to).map((u,id)=>({id,text:u.text}));process.stdout.write(JSON.stringify({type:'progress',completed:batch,total:batches.length})+'\n');let text='',finish;
    for(let attempt=0;attempt<2;attempt++){text='';finish=null;try{
    for await(const chunk of ctx.llm.stream({provider:route,model:input.model,sessionId,system,messages:[createUserMessage({content:[{type:'text',text:JSON.stringify({units,knownSpeakers:input.knownSpeakers||[],beforeContext:input.units.slice(Math.max(0,from-12),from).map(u=>u.text).join(''),afterContext:input.units.slice(to,to+8).map(u=>u.text).join('')})}],source:{kind:'plugin',plugin:'webvideo-novel-structure'}})],signal})){if(chunk.type==='text-delta')text+=chunk.text;if(chunk.type==='finish')finish=chunk.reason;}
    if(finish?.kind!=='stop')throw finishError(finish,signal,{code:'INCOMPLETE_OUTPUT',message:'第 '+(batch+1)+' 批返回未完整结束。'});if(!text.trim())throw Object.assign(Error('第 '+(batch+1)+' 批：模型结束了请求，但没有返回可见文本。'),{code:'EMPTY_RESPONSE'});
     break;
    }catch(error){const retryText=String(error?.code||'')+' '+String(error?.message||'');if(attempt===1||signal.aborted||[400,401,403,404,429].includes(Number(error.status))||/QUOTA|CREDENTIAL|AUTH|UNKNOWN_MODEL|INVALID_CONFIG|ABORTED|MODEL_OUTPUT_LIMIT/.test(String(error.code||''))||refusalText(retryText))throw error;process.stdout.write(JSON.stringify({type:'progress',completed:batch,total:batches.length,retrying:true})+'\n');await new Promise(resolve=>setTimeout(resolve,1000));signal.throwIfAborted();}}
    const trimmed=text.trim().replace(/^```(?:json)?\s*\n([\s\S]*?)\n```$/,'$1');let result;try{result=JSON.parse(trimmed);}catch{if(refusalText(trimmed))throw invalidModelOutput('第 '+(batch+1)+' 批：模型返回了拒答或安全过滤提示。',trimmed,'MODEL_REFUSAL');throw invalidModelOutput('第 '+(batch+1)+' 批返回格式无效，未改动剧本。',trimmed);}WebVideoNovel.resolve({source:input.source,units,knownSpeakers:input.knownSpeakers||[]},result);if(!Array.isArray(result.cast))throw Error('模型没有返回在场角色名单。');for(const name of result.cast){if(typeof name!=='string'||!name.trim()||!input.source.includes(name))throw Error('角色名单引用了原文不存在的名字。');cast.add(name);}segments.push(...result.segments.map(row=>({...row,from:row.from+from,to:row.to+from})));process.stdout.write(JSON.stringify({type:'progress',completed:batch+1,total:batches.length})+'\n');
   }
   WebVideoNovel.resolve({source:input.source,units:input.units,knownSpeakers:input.knownSpeakers||[]},{segments});process.stdout.write(JSON.stringify({ok:true,segments,cast:[...cast]}));
 }else if(input.action==='stage'){
   const prepared={source:input.source,units:input.units,knownSpeakers:input.knownSpeakers||[]},resolved=WebVideoNovel.resolve(prepared,{segments:input.segments}),all=resolved.rows.map((r,at)=>({at,text:r.text,speaker:r.speaker,kind:r.kind,sceneBreak:r.sceneBreak})),changes=[];
   const system=fs.readFileSync(new URL('./stage-prompt.txt',import.meta.url),'utf8');let previousState={background:null,cast:[]};const total=Math.ceil(all.length/45);
   for(let batch=0;batch<total;batch++){const rows=all.slice(batch*45,(batch+1)*45);let text='',finish;process.stdout.write(JSON.stringify({type:'progress',completed:batch,total})+'\n');
    for(let attempt=0;attempt<2;attempt++){text='';finish=null;try{for await(const chunk of ctx.llm.stream({provider:route,model:input.model,sessionId,system,messages:[createUserMessage({content:[{type:'text',text:JSON.stringify({rows,actors:input.stageAssets.actors,backgrounds:input.stageAssets.backgrounds,maxActors:input.maxActors,previousState})}],source:{kind:'plugin',plugin:'webvideo-basic-stage'}})],signal})){if(chunk.type==='text-delta')text+=chunk.text;if(chunk.type==='finish')finish=chunk.reason;}if(finish?.kind!=='stop')throw finishError(finish,signal,{code:'INCOMPLETE_OUTPUT',message:'舞台安排输出未完整结束。'});if(!text.trim())throw Object.assign(Error('舞台安排：模型结束了请求，但没有返回可见文本。'),{code:'EMPTY_RESPONSE'});break;}catch(error){const retryText=String(error?.code||'')+' '+String(error?.message||'');if(attempt===1||signal.aborted||[400,401,403,404,429].includes(Number(error.status))||/QUOTA|CREDENTIAL|AUTH|UNKNOWN_MODEL|INVALID_CONFIG|ABORTED|MODEL_OUTPUT_LIMIT/.test(String(error.code||''))||refusalText(retryText))throw error;process.stdout.write(JSON.stringify({type:'progress',completed:batch,total,retrying:true})+'\n');await new Promise(resolve=>setTimeout(resolve,1000));signal.throwIfAborted();}}
    let output;const trimmed=text.trim().replace(/^```(?:json)?\s*\n([\s\S]*?)\n```$/,'$1');try{output=JSON.parse(trimmed);}catch{if(refusalText(trimmed))throw invalidModelOutput('舞台安排：模型返回了拒答或安全过滤提示。',trimmed,'MODEL_REFUSAL');throw invalidModelOutput('舞台安排格式无效，未改动剧本。',trimmed);}WebVideoNovel.validateStage({assets:input.stageAssets,changes:output.changes,maxActors:input.maxActors},all.length,rows[0]?.at??0,rows.at(-1)?.at??0,batch===0);changes.push(...output.changes);for(const change of output.changes)previousState={background:change.background??previousState.background,cast:change.cast};process.stdout.write(JSON.stringify({type:'progress',completed:batch+1,total})+'\n');
   }
   process.stdout.write(JSON.stringify({ok:true,changes})); }else{
   let text='',finish=null;for await(const chunk of ctx.llm.stream({provider:route,model:input.model,sessionId,messages:[createUserMessage({content:[{type:'text',text:'Reply with OK only to confirm API connectivity for the WebVideo+ WebGAL script editor.'}],source:{kind:'plugin',plugin:'webvideo-connection-check'}})],maxTokens:256,signal})){if(chunk.type==='text-delta')text+=chunk.text;if(chunk.type==='finish')finish=chunk.reason;}
   if(finish?.kind!=='stop')throw finishError(finish,signal,{code:'CONNECTION_FAILED',message:'连接测试未正常结束。'});
   if(!text.trim())throw Object.assign(Error('模型没有返回可见文本，可能只输出了推理内容或被服务商静默过滤。'),{code:'EMPTY_RESPONSE'});
   process.stdout.write(JSON.stringify({ok:true,message:'连接成功，模型已响应。'}));
 }
}catch(error){const info=describeFailure(error);process.stdout.write(JSON.stringify({ok:false,error:info.error,category:info.category,status:info.status,code:redact(info.code),requestId:info.requestId?redact(info.requestId):null,retryAfterMs:info.retryAfterMs||null,detail:redact(info.detail)}));process.exitCode=1;
}finally{delete process.env.WEBVIDEO_AI_KEY;await ctx?.dispose();}
