import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {install,uninstall,prepareUpdateUnmount,remountAfterVerifiedUpdate,verifyPackage,readState,fileHash,hostRecordPath,recoverSessionLock} from '../craft/installer/transaction.mjs';
const hash=data=>crypto.createHash('sha256').update(data).digest('hex');
function fixture(body){const home=fs.mkdtempSync(path.join(os.tmpdir(),'craft-installer-check-'));try{body(home);}finally{fs.rmSync(home,{recursive:true,force:true});}}
function payload(home,name='payload',version='1c'){
 const root=path.join(home,name),files={'node.exe':'fixture node never executed','WebGAL.Video.exe':'fixture kernel never executed','WebVideoCraft.Launcher.exe':'fixture wrapper '+version,'craft/launch-injected.mjs':'// fixture session '+version,'craft/session/api.mjs':'export const test=true;'};
 for(const [name,data]of Object.entries(files)){const file=path.join(root,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data);}
 fs.writeFileSync(path.join(root,'MANIFEST.json'),JSON.stringify({schemaVersion:1,product:'WebVideo+ Craft',version,supportedHosts:[{version:'beta.2',sha256:hash('official fixture version A')},{version:'beta.3',sha256:hash('official fixture version B')}],updateObserverValidated:false,sameNameUpdateValidated:false,entry:'craft/launch-injected.mjs',node:'node.exe',kernel:'WebGAL.Video.exe',wrapper:'WebVideoCraft.Launcher.exe',files:Object.entries(files).map(([name,data])=>({path:name,bytes:Buffer.byteLength(data),sha256:hash(data)}))}));return root;
}
function setup(home,mode='same-name'){
 const packageRoot=payload(home),adapterRoot=path.join(home,'adapter'),craftExe=path.join(home,'host/webgal-craft.exe');fs.mkdirSync(path.dirname(craftExe));fs.writeFileSync(craftExe,'official fixture version A');return {packageRoot,adapterRoot,craftExe,mode,processCheck:()=>false};
}
const statePath=o=>path.join(o.adapterRoot,'config.json');
const original=o=>path.join(path.dirname(o.craftExe),'webgal-craft.webvideo-original.exe');
function tree(root){const files=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):[path.join(dir,e.name)]);return files(root).sort().map(f=>[path.relative(root,f),fileHash(f)]);}
test('default external install leaves host untouched, repeat is idempotent',()=>fixture(home=>{const o=setup(home,'external'),before=fileHash(o.craftExe);delete o.mode;const a=install(o);assert.equal(a.state.installMode,'external');assert.equal(fileHash(o.craftExe),before);assert.equal(fs.existsSync(hostRecordPath(o.craftExe)),false);assert.equal(install(o).changed,false);assert.equal(uninstall(statePath(o),o).state.status,'detached');assert.equal(fileHash(o.craftExe),before);}));
test('same-name install/reinstall/uninstall preserves exact original and mutable data',()=>fixture(home=>{const o=setup(home),before=fileHash(o.craftExe),a=install(o);assert.equal(fileHash(original(o)),before);assert.equal(fileHash(o.craftExe),a.state.ownership.wrapperSha256);fs.mkdirSync(a.state.stateDir,{recursive:true});fs.writeFileSync(path.join(a.state.stateDir,'settings.json'),'user settings');assert.equal(install(o).changed,false);uninstall(statePath(o),o);assert.equal(fileHash(o.craftExe),before);assert.equal(fs.existsSync(original(o)),false);assert.equal(fs.existsSync(hostRecordPath(o.craftExe)),false);assert.equal(fs.readFileSync(path.join(a.state.stateDir,'settings.json'),'utf8'),'user settings');assert.equal(uninstall(statePath(o),o).changed,false);assert.equal(install(o).state.status,'installed');}));
test('verified upgrade swaps package and wrapper but preserves state/original',()=>fixture(home=>{const o=setup(home),a=install(o);fs.mkdirSync(a.state.stateDir);fs.writeFileSync(path.join(a.state.stateDir,'settings.json'),'keep');const originalHash=fileHash(original(o));o.packageRoot=payload(home,'payload2','2c');const b=install(o);assert.equal(b.state.installId,a.state.installId);assert.equal(b.state.package.version,'2c');assert.equal(fileHash(original(o)),originalHash);assert.equal(fileHash(o.craftExe),b.state.ownership.wrapperSha256);assert.equal(fs.readFileSync(path.join(a.state.stateDir,'settings.json'),'utf8'),'keep');}));
for(const phase of ['staged','published','host-replaced','recorded'])test('new install rollback at '+phase,()=>fixture(home=>{const o=setup(home),before=fileHash(o.craftExe);assert.throws(()=>install({...o,failAt:phase}),/Injected/);assert.equal(fileHash(o.craftExe),before);assert.equal(fs.existsSync(o.adapterRoot),false);assert.equal(fs.existsSync(original(o)),false);assert.equal(fs.existsSync(hostRecordPath(o.craftExe)),false);}));
for(const phase of ['published','host-replaced','recorded'])test('upgrade rollback at '+phase,()=>fixture(home=>{const o=setup(home);install(o);const before=tree(o.adapterRoot),exe=fileHash(o.craftExe),backup=fileHash(original(o)),record=fs.readFileSync(hostRecordPath(o.craftExe));o.packageRoot=payload(home,'payload2','2c');assert.throws(()=>install({...o,failAt:phase}),/Injected/);assert.deepEqual(tree(o.adapterRoot),before);assert.equal(fileHash(o.craftExe),exe);assert.equal(fileHash(original(o)),backup);assert.deepEqual(fs.readFileSync(hostRecordPath(o.craftExe)),record);}));
for(const phase of ['host-restored','record-removed'])test('uninstall rollback at '+phase,()=>fixture(home=>{const o=setup(home);install(o);const before=tree(o.adapterRoot),exe=fileHash(o.craftExe),record=fs.readFileSync(hostRecordPath(o.craftExe));assert.throws(()=>uninstall(statePath(o),{...o,failAt:phase}),/Injected/);assert.deepEqual(tree(o.adapterRoot),before);assert.equal(fileHash(o.craftExe),exe);assert.deepEqual(fs.readFileSync(hostRecordPath(o.craftExe)),record);}));
test('changed host from official update is never overwritten by stale recovery',()=>fixture(home=>{const o=setup(home);install(o);fs.writeFileSync(o.craftExe,'official fixture version B');const updated=fileHash(o.craftExe),r=uninstall(statePath(o),o);assert.equal(r.hostChanged,true);assert.equal(fileHash(o.craftExe),updated);assert.equal(fs.existsSync(original(o)),true);assert.throws(()=>install(o),/recovery|record/);}));
test('update unmount keeps recovery and explicit evidence gates reattach',()=>fixture(home=>{const o=setup(home);const manifestPath=path.join(o.packageRoot,'MANIFEST.json'),testManifest=JSON.parse(fs.readFileSync(manifestPath));testManifest.updateObserverValidated=true;testManifest.sameNameUpdateValidated=true;fs.writeFileSync(manifestPath,JSON.stringify(testManifest));const a=install(o);const detached=prepareUpdateUnmount(statePath(o),o);assert.equal(detached.state.status,'update-unmounted');assert.equal(fileHash(o.craftExe),a.state.ownership.originalSha256);fs.writeFileSync(o.craftExe,'official fixture version B');assert.throws(()=>remountAfterVerifiedUpdate(statePath(o),{},o),/evidence/);const evidence={expectedHostHash:fileHash(o.craftExe),version:'beta.3',provenance:'test official pinned fixture'};assert.throws(()=>remountAfterVerifiedUpdate(statePath(o),evidence,o),/trusted coordinator/);const b=remountAfterVerifiedUpdate(statePath(o),evidence,{...o,verifyUpdateReceipt:()=>true});assert.equal(fileHash(original(o)),evidence.expectedHostHash);assert.equal(fileHash(o.craftExe),b.state.ownership.wrapperSha256);assert.equal(b.state.host.version,'beta.3');}));
test('busy lease blocks mutations without killing any process',()=>fixture(home=>{const o=setup(home),a=install(o);fs.mkdirSync(a.state.stateDir);fs.writeFileSync(path.join(a.state.stateDir,'session.json'),JSON.stringify({schemaVersion:1,hostPid:42}));assert.throws(()=>uninstall(statePath(o),{processCheck:()=>true}),/Close/);assert.equal(fileHash(o.craftExe),a.state.ownership.wrapperSha256);}));
test('unknown target, backup and modified package fail closed',()=>fixture(home=>{const o=setup(home);fs.mkdirSync(o.adapterRoot);assert.throws(()=>install(o),/unowned/);fs.rmdirSync(o.adapterRoot);fs.writeFileSync(original(o),'unrelated');assert.throws(()=>install(o),/Unowned/);fs.unlinkSync(original(o));fs.appendFileSync(path.join(o.packageRoot,'node.exe'),'modified');assert.throws(()=>install(o),/integrity/);}));
test('manifest traversal, case duplicates and unlisted files are rejected',()=>fixture(home=>{const root=payload(home),file=path.join(root,'MANIFEST.json'),good=JSON.parse(fs.readFileSync(file));for(const bad of ['../escape','craft/../escape','C:/escape','craft\\escape','/escape','NUL','craft/con.txt','trailing.']){const m=structuredClone(good);m.files[0].path=bad;fs.writeFileSync(file,JSON.stringify(m));assert.throws(()=>verifyPackage(root),/Unsafe/);}const m=structuredClone(good);m.files.push({...m.files[0],path:'NODE.EXE'});fs.writeFileSync(file,JSON.stringify(m));assert.throws(()=>verifyPackage(root),/Duplicate/);fs.writeFileSync(file,JSON.stringify(good));fs.writeFileSync(path.join(root,'extra.txt'),'unlisted');assert.throws(()=>verifyPackage(root),/Unlisted/);}));
test('symlinked source/package/target paths are rejected',()=>fixture(home=>{const o=setup(home);fs.symlinkSync(o.packageRoot,path.join(home,'linked'),'dir');assert.throws(()=>verifyPackage(path.join(home,'linked')),/Linked/);fs.symlinkSync(path.dirname(o.craftExe),o.adapterRoot,'dir');assert.throws(()=>install(o),/Linked/);}));
test('same host lock rejects concurrent installers for different adapter roots',()=>fixture(home=>{const o=setup(home);fs.mkdirSync(o.craftExe+'.webvideo.install-lock');assert.throws(()=>install(o));assert.equal(fs.existsSync(o.adapterRoot),false);}));
test('failure before touching host never restores over a newly created foreign backup/record',()=>fixture(home=>{const o=setup(home),before=fileHash(o.craftExe);assert.throws(()=>install({...o,onPhase:phase=>{if(phase==='staged'){fs.writeFileSync(original(o),'foreign backup');fs.writeFileSync(hostRecordPath(o.craftExe),'foreign record');throw Error('foreign mutation');}}}),/foreign mutation/);assert.equal(fs.readFileSync(original(o),'utf8'),'foreign backup');assert.equal(fs.readFileSync(hostRecordPath(o.craftExe),'utf8'),'foreign record');assert.equal(fileHash(o.craftExe),before);}));
test('foreign adapter additions stop rollback rather than deleting foreign data',()=>fixture(home=>{const o=setup(home);assert.throws(()=>install({...o,onPhase:phase=>{if(phase==='published'){fs.writeFileSync(path.join(o.adapterRoot,'foreign.txt'),'keep me');throw Error('interrupt');}}}),/rollback incomplete/);assert.equal(fs.readFileSync(path.join(o.adapterRoot,'foreign.txt'),'utf8'),'keep me');assert.ok(fs.readdirSync(home).some(name=>name.includes('.transaction-')));}));
test('foreign executable change stops install rollback without overwriting updater bytes',()=>fixture(home=>{const o=setup(home);assert.throws(()=>install({...o,onPhase:phase=>{if(phase==='host-replaced'){fs.writeFileSync(o.craftExe,'new updater bytes');throw Error('interrupt');}}}),/rollback incomplete/);assert.equal(fs.readFileSync(o.craftExe,'utf8'),'new updater bytes');assert.equal(fs.readFileSync(original(o),'utf8'),'official fixture version A');}));
test('foreign record after uninstall deletion is not overwritten during rollback',()=>fixture(home=>{const o=setup(home);install(o);assert.throws(()=>uninstall(statePath(o),{...o,onPhase:phase=>{if(phase==='record-removed'){fs.writeFileSync(hostRecordPath(o.craftExe),'new owner record');throw Error('interrupt');}}}),/rollback refused/);assert.equal(fs.readFileSync(hostRecordPath(o.craftExe),'utf8'),'new owner record');}));
test('host nested inside adapter target is rejected in either overlap direction',()=>fixture(home=>{const o=setup(home);assert.throws(()=>install({...o,adapterRoot:home}),/isolated/);assert.throws(()=>install({...o,adapterRoot:path.join(path.dirname(o.craftExe),'adapter')}),/isolated/);}));

test('exclusive session lock blocks spawn-window mutation and stale recovery requires dead matching lease',()=>fixture(home=>{const o=setup(home),a=install(o);fs.mkdirSync(a.state.stateDir);const lock=path.join(a.state.stateDir,'session.lock');fs.writeFileSync(lock,JSON.stringify({sessionId:'owned-session',pid:42}));assert.throws(()=>uninstall(statePath(o),o),/Session lock/);fs.writeFileSync(path.join(a.state.stateDir,'session.json'),JSON.stringify({schemaVersion:1,sessionId:'owned-session',coordinatorPid:42,hostPid:43}));assert.throws(()=>recoverSessionLock(statePath(o),{processCheck:()=>true}),/still alive/);assert.equal(recoverSessionLock(statePath(o),{processCheck:()=>false}).changed,true);assert.equal(fs.existsSync(lock),false);}));
test('incomplete session lock fails closed before lease exists',()=>fixture(home=>{const o=setup(home),a=install(o);fs.mkdirSync(a.state.stateDir);fs.writeFileSync(path.join(a.state.stateDir,'session.lock'),'');assert.throws(()=>uninstall(statePath(o),o),/Unknown\/incomplete/);}));

test('unknown host cannot be adopted by recording its current hash',()=>fixture(home=>{const o=setup(home);fs.writeFileSync(o.craftExe,'unknown host');assert.throws(()=>install(o),/Unsupported Craft host/);assert.equal(fs.existsSync(o.adapterRoot),false);assert.equal(fs.existsSync(original(o)),false);}));

test('development package cannot remount even with caller-supplied verifier approval',()=>fixture(home=>{const o=setup(home);install(o);prepareUpdateUnmount(statePath(o),o);fs.writeFileSync(o.craftExe,'official fixture version B');assert.throws(()=>remountAfterVerifiedUpdate(statePath(o),{expectedHostHash:fileHash(o.craftExe),version:'beta.3',provenance:'test'}, {...o,verifyUpdateReceipt:()=>true}),/not validated/);assert.equal(fs.readFileSync(o.craftExe,'utf8'),'official fixture version B');}));
