import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const script=fs.readFileSync(path.join(root,'browser/update-check.js'),'utf8');
const sandbox={setTimeout,clearTimeout,AbortController,WebVideoUpdateContext:{productVersion:'1.1.0',engineId:'open-webgal.webgal',engineVersion:'4.6.4'},fetch:async()=>{throw Error('offline');}};
sandbox.globalThis=sandbox;
vm.runInNewContext(script,sandbox);
const updates=sandbox.WebVideoUpdates;
const release=(tag,engines)=>({tag_name:'v'+tag,draft:false,prerelease:false,body:engines?`<!-- webvideo-compat: {"webgal":${JSON.stringify(engines)}} -->`:''});
const releases=[release('1.2.0',['4.6.5']),release('1.1.0'),release('1.0.4')];
assert.equal(updates.classify(releases,'4.6.5','1.1.0').kind,'update');
assert.match(updates.classify(releases,'4.6.5','1.1.0').url,/v1\.2\.0$/);
assert.equal(updates.classify(releases,'4.6.4','1.0.4').kind,'update');
assert.match(updates.classify(releases,'4.6.4','1.0.4').url,/v1\.1\.0$/);
assert.equal(updates.classify(releases,'4.6.4','1.1.0').kind,'keep');
assert.equal(updates.classify([release('1.2.0'),release('1.1.0')],'4.6.4','1.1.0').kind,'unknown');
assert.equal(updates.classify(releases,'4.6.6','1.1.0').kind,'unsupported');
await updates.check(true);
assert.equal(updates.state().phase,'failed');
assert.match(updates.state().message,/检查更新失败/);
sandbox.WebVideoUpdateContext.engineId='webgal-mygo.mygo';
await updates.check(true);
assert.equal(updates.state().kind,'unknown');
assert.match(updates.state().message,/无法确认/);
console.log('Update compatibility and offline checks passed.');
