import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {KernelSession} from '../session/kernel.mjs';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};}
function fixture(t){
 const calls=[],snapshot={id:'owned',runtimeId:'open-webgal.webgal',engineVersion:'4.6.5'};
 const kernel=new KernelSession({root:'/unused',kernel:'/unused',storage:{get:()=>snapshot}});
 kernel.discovery={baseUrl:'http://127.0.0.1:4444',token:'fixture-token',pid:77,serviceId:'fixture-service'};
 kernel.child=Object.assign(new EventEmitter(),{pid:77,exitCode:null,signalCode:null});
 let queue=[],startId=id(1),status={id:id(1),state:'running'},handler;
 const original=globalThis.fetch;globalThis.fetch=async(url,options)=>{const call={url,endpoint:url.slice(kernel.discovery?.baseUrl?.length||'http://127.0.0.1:4444'.length),options,data:options.body?JSON.parse(options.body):undefined};calls.push(call);if(handler){const result=await handler(call);if(result!==undefined)return result;}
  return {ok:true,json:async()=>call.endpoint==='/api/jobs'&&options.method==='GET'?queue:call.endpoint.endsWith('/status')?status:call.endpoint==='/api/config'?{}:{id:startId,state:'running'}};
 };t.after(()=>globalThis.fetch=original);
 return {kernel,calls,snapshot,setQueue:value=>queue=value,setId:value=>startId=value,setStatus:value=>status=value,handle:value=>handler=value,request:endpoint=>kernel.request({endpoint,data:{},snapshotId:'snapshot'}),read:()=>kernel.readUpdateActivity()};
}
const idle=result=>{assert.equal(result.known,true);assert.equal(result.hasBlockingTasks,false);assert.equal(result.activeJobs,0);assert.equal(result.coverage,'known-kernel-work-only');assert.equal(result.universalIdle,false);};
const blocked=(result,known)=>{assert.equal(result.hasBlockingTasks,true);if(known!==undefined)assert.equal(result.known,known);};
test('never-used kernel reports scoped idle without startup or network',async()=>{const kernel=new KernelSession({root:'/unused',kernel:'/unused'});kernel.start=()=>{throw Error('must not start');};idle(await kernel.readUpdateActivity());assert.equal(kernel.child,null);});
test('empty authoritative queue on existing live service is idle',async t=>{const f=fixture(t);idle(await f.read());assert.equal(f.calls.length,1);assert.equal(f.calls[0].options.method,'GET');assert.equal(f.calls[0].options.headers.Authorization,'Bearer fixture-token');});
for(const state of ['queued','running'])test('untracked authoritative '+state+' queue work blocks update',async t=>{const f=fixture(t);f.setQueue([{id:id(7),state}]);blocked(await f.read(),true);});
for(const endpoint of ['/api/jobs','/api/timing'])test(endpoint+' remains tracked after start request resolves',async t=>{const f=fixture(t);assert.equal((await f.request(endpoint)).id,id(1));f.setQueue([{id:id(1),state:'running'}]);const active=await f.read();blocked(active,true);assert.equal(active.inFlight,0);assert.equal(active.activeJobs,1);f.setQueue([{id:id(1),state:'completed',phase:'completed'}]);idle(await f.read());f.setQueue([]);idle(await f.read());});
test('completed cleanup is still blocking; completed cleanup-warning history is idle',async t=>{const f=fixture(t);await f.request('/api/jobs');f.setQueue([{id:id(1),state:'completed',phase:'cleanup'}]);blocked(await f.read(),true);f.setQueue([{id:id(1),state:'completed',phase:'completed',cacheCleaned:false,cacheCleanupWarning:'historical locked cache'}]);idle(await f.read());});
for(const state of ['failed','canceled'])test('queue terminal '+state+' retires the owned task',async t=>{const f=fixture(t);await f.request('/api/jobs');f.setQueue([{id:id(1),state}]);idle(await f.read());f.setQueue([]);idle(await f.read());});
for(const state of ['needs_attention','cancelled','complete','unknown'])test('queue state '+state+' cannot be silently treated as idle',async t=>{const f=fixture(t);f.setQueue([{id:id(1),state}]);blocked(await f.read(),false);});
for(const kind of ['novel','subtitles'])for(const state of ['running','complete','failed','cancelled'])test(kind+' status '+state+' is queried authoritatively by retained ID',async t=>{const f=fixture(t),prefix=kind==='novel'?'/api/ai/novel':'/api/subtitles';await f.request(prefix+'/start');f.setStatus({id:id(1),state});const result=await f.read();if(state==='running')blocked(result,true);else idle(result);assert(f.calls.some(c=>c.endpoint===prefix+'/status'&&c.data.id===id(1)));});
test('successful cancel response alone is not proof of task termination',async t=>{const f=fixture(t);await f.request('/api/ai/novel/start');await f.kernel.request({endpoint:'/api/ai/novel/cancel',data:{id:id(1)}});blocked(await f.read(),true);f.setStatus({id:id(1),state:'cancelled'});idle(await f.read());});
test('normal terminal status observation retires old novel before its server ledger is replaced',async t=>{const f=fixture(t);await f.request('/api/ai/novel/start');f.setStatus({id:id(1),state:'complete'});await f.kernel.request({endpoint:'/api/ai/novel/status',data:{id:id(1)}});f.setId(id(2));await f.request('/api/ai/novel/start');f.setStatus({id:id(2),state:'complete'});idle(await f.read());const recent=f.calls.filter(c=>c.endpoint==='/api/ai/novel/status');assert.equal(recent.at(-1).data.id,id(2));});
test('all ordinary in-flight requests block, including before kernel startup',async t=>{const f=fixture(t),d=deferred();f.handle(c=>c.endpoint==='/api/config'?d.promise:undefined);const pending=f.kernel.request({endpoint:'/api/config'});await Promise.resolve();blocked(await f.read(),true);d.resolve({ok:true,json:async()=>({settings:{}})});await pending;idle(await f.read());});
test('snapshot/runtime preparation counts as in-flight before HTTP dispatch',async t=>{const f=fixture(t),d=deferred();f.kernel.readRuntimeStartup=()=>d.promise;const pending=f.request('/api/jobs');blocked(await f.read(),true);assert.equal(f.calls.length,0);d.resolve(undefined);await pending;f.setQueue([{id:id(1),state:'running'}]);blocked(await f.read(),true);});
test('local validation rejection does not invent a potentially started kernel job',async t=>{const f=fixture(t);f.snapshot.engineVersion='unknown';await assert.rejects(f.request('/api/jobs'),/精确档位/);assert.equal(f.calls.length,0);idle(await f.read());});
for(const failure of ['network','malformed-json','http-error','missing-id'])test('async start '+failure+' preserves transport result/error and latches uncertainty',async t=>{const f=fixture(t);f.handle(c=>{if(c.endpoint!=='/api/ai/novel/start')return;if(failure==='network')throw Error('transport lost');return{ok:failure!=='http-error',json:async()=>{if(failure==='malformed-json')throw SyntaxError('bad json');return failure==='http-error'?{error:'server rejected'}:{};}};});if(failure==='missing-id')assert.deepEqual(await f.request('/api/ai/novel/start'),{});else await assert.rejects(f.request('/api/ai/novel/start'));f.handle(undefined);const result=await f.read();blocked(result,false);assert.equal(result.reason,'kernel-start-outcome-unknown');assert.equal(f.calls.length,1,'uncertainty does not disappear after an empty queue read');});
test('more than 64 tracked starts cannot silently drop work or grow without bound',async t=>{const f=fixture(t);for(let n=1;n<=65;n++){f.setId(id(n));await f.request('/api/jobs');}const result=await f.read();blocked(result,false);assert.equal(result.reason,'kernel-task-tracking-limit');assert.equal(result.activeJobs,64);});
for(const queue of [null,{},[{id:'bad',state:'completed',phase:'completed'}],[{id:id(1),state:'running'},{id:id(1),state:'completed',phase:'completed'}],Array.from({length:1025},(_,n)=>({id:id(n),state:'failed'}))])test('malformed or excessive queue evidence fails closed '+JSON.stringify(queue).slice(0,40),async t=>{const f=fixture(t);f.setQueue(queue);blocked(await f.read(),false);});
test('missing tracked queue ID remains uncertain rather than presumed completed',async t=>{const f=fixture(t);await f.request('/api/jobs');blocked(await f.read(),false);f.setQueue([{id:id(1),state:'failed'}]);idle(await f.read());});
for(const value of [{state:'complete'},{id:id(2),state:'complete'},{id:id(1),state:'unexpected'}])test('malformed/background identity mismatch fails closed '+JSON.stringify(value),async t=>{const f=fixture(t);await f.request('/api/subtitles/start');f.setStatus(value);blocked(await f.read(),false);});
test('activity query network/HTTP failure is unknown and later same-service authoritative proof may recover',async t=>{const f=fixture(t);f.handle(()=>{throw Error('offline');});blocked(await f.read(),false);f.handle(()=>({ok:false,json:async()=>({})}));blocked(await f.read(),false);f.handle(undefined);idle(await f.read());});
for(const mutate of [f=>{f.kernel.child.exitCode=1;},f=>{f.kernel.child.signalCode='SIGTERM';},f=>{f.kernel.discovery=null;},f=>{f.kernel.discovery.pid=999;},f=>{f.kernel.discovery.baseUrl='https://foreign.example';},f=>{f.kernel.discovery.serviceId='';}])test('lost or invalid service identity blocks without startup',async t=>{const f=fixture(t);mutate(f);blocked(await f.read(),false);assert.equal(f.calls.length,0);});
test('a new request that starts and completes while polling invalidates stale idle evidence',async t=>{const f=fixture(t),d=deferred();let held=true;f.handle(c=>c.endpoint==='/api/jobs'&&c.options.method==='GET'&&held?(held=false,d.promise):undefined);const checking=f.read();await Promise.resolve();await f.request('/api/jobs');d.resolve({ok:true,json:async()=>[]});const result=await checking;blocked(result,false);assert.equal(result.reason,'kernel-activity-changed');f.setQueue([{id:id(1),state:'queued'}]);blocked(await f.read(),true);});
test('discovery or child changes during a status read cannot produce idle',async t=>{const f=fixture(t),d=deferred();f.handle(()=>d.promise);const checking=f.read();await Promise.resolve();f.kernel.discovery={...f.kernel.discovery,serviceId:'replacement'};d.resolve({ok:true,json:async()=>[]});blocked(await checking,false);});
test('concurrent status observations cannot erase newly started tasks',async t=>{const f=fixture(t);await f.request('/api/ai/novel/start');const d=deferred();f.handle(c=>c.endpoint==='/api/ai/novel/status'?d.promise:undefined);const checking=f.read();await new Promise(r=>setImmediate(r));f.setId(id(2));await f.request('/api/subtitles/start');d.resolve({ok:true,json:async()=>({id:id(1),state:'complete'})});blocked(await checking,false);assert.equal((await f.read()).hasBlockingTasks,true);});

for(const endpoint of ['/api/dialog/folder','/api/dialog/subtitle','/api/music/duration'])test('lost '+endpoint+' response keeps potentially running owned work unknown',async t=>{const f=fixture(t);f.handle(c=>{if(c.endpoint===endpoint)throw Error('request timed out while native work may still run');});await assert.rejects(f.request(endpoint),/timed out/);const result=await f.read();blocked(result,false);assert.equal(result.reason,'kernel-request-outcome-unknown');assert.equal(f.calls.length,1);});
test('lost GET response also cannot prove its owned service operation stopped',async t=>{const f=fixture(t);f.handle(()=>{throw Error('response lost');});await assert.rejects(f.kernel.request({endpoint:'/api/config'}));blocked(await f.read(),false);});
test('completed ordinary HTTP rejection preserves error without inventing ongoing native work',async t=>{const f=fixture(t);f.handle(c=>c.endpoint==='/api/dialog/folder'?{ok:false,json:async()=>({error:'cancelled validation'})}:undefined);await assert.rejects(f.request('/api/dialog/folder'),/cancelled validation/);idle(await f.read());});

test('novel cancellation followed by successful same-service restart retires replaced singleton ledger',async t=>{const f=fixture(t);await f.request('/api/ai/novel/start');await f.kernel.request({endpoint:'/api/ai/novel/cancel',data:{id:id(1)}});f.setId(id(2));await f.request('/api/ai/novel/start');f.setStatus({id:id(2),state:'complete'});idle(await f.read());assert.deepEqual(f.calls.filter(c=>c.endpoint==='/api/ai/novel/status').map(c=>c.data.id),[id(2)]);});
test('service identity change during start cannot authorize retiring earlier work',async t=>{const f=fixture(t),d=deferred();f.handle(c=>c.endpoint==='/api/ai/novel/start'?d.promise:undefined);const pending=f.request('/api/ai/novel/start');await new Promise(r=>setImmediate(r));f.kernel.discovery={...f.kernel.discovery,serviceId:'other-service'};d.resolve({ok:true,json:async()=>({id:id(1),state:'running'})});await pending;const value=await f.read();blocked(value,false);assert.equal(value.reason,'kernel-service-identity-changed');});

test('out-of-order overlapping novel starts cannot retire newer active work into false idle',async t=>{const f=fixture(t),first=deferred(),second=deferred();let starts=0;f.handle(c=>c.endpoint==='/api/ai/novel/start'?(++starts===1?first.promise:second.promise):undefined);const one=f.request('/api/ai/novel/start'),two=f.request('/api/ai/novel/start');await new Promise(r=>setImmediate(r));second.resolve({ok:true,json:async()=>({id:id(2),state:'running'})});await two;first.resolve({ok:true,json:async()=>({id:id(1),state:'running'})});await one;f.handle(undefined);f.setStatus({id:id(1),state:'complete'});await f.kernel.request({endpoint:'/api/ai/novel/status',data:{id:id(1)}});const result=await f.read();blocked(result,false);assert.equal(result.reason,'kernel-concurrent-start-outcomes');});
