import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {Node,nodes,makeDocument} from './ui-dom.mjs';
const source=fs.readFileSync(new URL('../ui/music-panel.js',import.meta.url),'utf8');
function fixture(overrides={}){
 const host=makeDocument(),calls=[],messages=[],listeners=new Set(),windowEvents={};let sourceListener,confirmValue=true,pointTarget=null;
 const snap={projectId:'p',path:'game/scene/start.txt',sceneRelativePath:'start.txt',source:'A;\nB;',revision:1};let values={textSpeed:50,autoSpeed:50};
 const state={loaded:false,dirty:false,busy:false,musicScope:null,timing:null,music:{schemaVersion:2,enabled:true,players:2,tracks:[{id:'a',name:'开场音乐',file:'a.ogg',lane:0,startSeconds:0,durationSeconds:8,volume:100},{id:'b',name:'另一首',file:'b.ogg',lane:0,startSeconds:8,durationSeconds:4,volume:80}]}};
 const emit=()=>listeners.forEach(fn=>fn(state));const result=()=>({seconds:20,settings:{...values},snapshot:{...snap},timing:{durationSeconds:20,storyTimeline:{durationSeconds:20,global:true,scenes:[{scene:'start.txt',startSeconds:0,endSeconds:20,lineTimes:[0,10000]}]}}});
 const available=(tracks,lane,start,duration,except)=>{let n=start;for(const t of tracks.filter(t=>t.id!==except&&t.lane===lane).sort((a,b)=>a.startSeconds-b.startSeconds)){if(n+duration<=t.startSeconds)break;if(n<t.startSeconds+t.durationSeconds&&n+duration>t.startSeconds)n=t.startSeconds+t.durationSeconds}return n};
 const controller={state:()=>structuredClone(state),subscribe:f=>(listeners.add(f),()=>listeners.delete(f)),peekTiming:()=>state.timing,measure:async options=>{calls.push(['measure',options.force]);options.signal?.addEventListener('abort',()=>calls.push(['abort-consumer']));options.onProgress?.({progress:.5,message:'实际测量'});state.timing=result();emit();return result()},loadMusic:async()=>{calls.push(['loadMusic']);state.loaded=true;state.musicScope='p';emit();return state.music},writeSpeeds:async p=>{calls.push(['writeSpeeds',p]);values={...values,...p};state.timing=null;emit();return values},addTracks:async(files,opt)=>{calls.push(['addTracks',files,opt]);state.music.tracks.push({id:'new',name:'新音乐',file:'new.ogg',lane:opt.lane,startSeconds:12,durationSeconds:5,volume:100});state.dirty=true;emit()},moveTrack:async(id,lane,start)=>{calls.push(['moveTrack',id,lane,start]);const t=state.music.tracks.find(t=>t.id===id);t.startSeconds=available(state.music.tracks,lane,start,t.durationSeconds,id);t.lane=lane;state.dirty=true;emit()},updateTrack:async(id,p)=>{calls.push(['updateTrack',id,p]);Object.assign(state.music.tracks.find(t=>t.id===id),p);state.dirty=true;emit()},removeTrack:async id=>{state.music.tracks=state.music.tracks.filter(t=>t.id!==id);state.dirty=true;emit()},addPlayer:async()=>{state.music.players++;state.dirty=true;emit()},removePlayer:async lane=>{state.music.players--;state.music.tracks=state.music.tracks.filter(t=>t.lane!==lane).map(t=>({...t,lane:t.lane>lane?t.lane-1:t.lane}));state.dirty=true;emit()},fitToMusic:async options=>{calls.push(['fit',options.textSpeed,options.autoSpeed]);return{...result(),matched:true,errorSeconds:0}},saveMusic:async music=>{calls.push(['save',music]);state.music=music;state.dirty=false;emit()},discardMusic:()=>{calls.push(['discard']);state.dirty=false;emit()}};Object.assign(controller,overrides);
 const bridge={capabilities:()=>({snapshot:true,timing:true,previewSettings:true,projectFiles:true,music:true,audioImport:true}),snapshot:async()=>({...snap}),subscribe:f=>(sourceListener=f,()=>sourceListener=null)};
 host.document.elementFromPoint=()=>pointTarget;
 const context={document:host.document,AbortController,setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){},confirm:()=>confirmValue,addEventListener:(event,fn)=>(windowEvents[event]??=[]).push(fn),removeEventListener:(event,fn)=>windowEvents[event]=(windowEvents[event]||[]).filter(x=>x!==fn),WebVideoCraftMedia:{availableStart:available}};context.window=context;vm.createContext(context);vm.runInContext(source,context);
 const container=new Node('div');host.body.append(container);const ui=context.WebVideoCraftMusicUI.mount(container,{bridge,controller,notify:m=>messages.push(m)});
 const list=()=>nodes(container),find=text=>list().find(n=>n.tagName==='BUTTON'&&n.textContent===text),field=label=>list().find(n=>n.getAttribute('aria-label')===label),tick=()=>new Promise(r=>setTimeout(r,10));
 return{ui,container,state,snap,calls,messages,find,field,list,tick,open:async()=>{ui.show(true);await tick()},click:async text=>{await find(text).click();await tick()},changed:()=>sourceListener?.(),confirm:value=>confirmValue=value,point:node=>pointTarget={closest:()=>node},emit:async(event,value)=>{for(const fn of windowEvents[event]||[])await fn(value);await tick()}};
}
test('opening music automatically measures and loads, presents story and player clips without ID forms',async()=>{const f=fixture();await f.open();assert.deepEqual(f.calls.slice(0,2).map(c=>c[0]),['measure','loadMusic']);assert.ok(f.list().some(n=>n.className==='wvc-music-story-bar'&&n.textContent==='0:20.0'));assert.equal(f.list().filter(n=>n.getAttribute('data-wvc-track-id')).length,2);assert.equal(f.field('配乐 ID（从配置中复制）'),undefined);f.ui.dispose()});
test('add uses native chooser and selected lane, not browser FileList',async()=>{const f=fixture();await f.open();await f.field('播放器 2 添加音乐').click();await f.tick();const call=f.calls.find(c=>c[0]==='addTracks');assert.equal(call[1],undefined);assert.equal(call[2].lane,1);assert.equal(f.state.dirty,true);f.ui.dispose()});
test('speed blur changes just one chosen speed then recalculates actual story time',async()=>{const f=fixture();await f.open();f.field('文字速度').value='65';await f.field('文字速度').emit('blur');await f.tick();assert.deepEqual({...f.calls.find(c=>c[0]==='writeSpeeds')[1]},{textSpeed:65});assert.equal(f.calls.filter(c=>c[0]==='measure').length,2);assert.equal(f.field('自动放映速度').value,50);f.ui.dispose()});
test('keyboard nudge and pointer move preserve clip duration and use non-overlap controller path',async()=>{const f=fixture();await f.open();const original=f.state.music.tracks[0].durationSeconds;let clip=f.list().find(n=>n.getAttribute('data-wvc-track-id')==='a');await clip.emit('keydown',{key:'ArrowRight'});await f.tick();assert.ok(f.calls.some(c=>c[0]==='moveTrack'));assert.equal(f.state.music.tracks[0].durationSeconds,original);clip=f.list().find(n=>n.getAttribute('data-wvc-track-id')==='a');await clip.emit('pointerdown',{button:0,clientX:0,pointerId:1});f.point(f.list().find(n=>n.getAttribute('data-wvc-player-lane')==='1'));await f.emit('pointermove',{clientX:100,clientY:0});await f.emit('pointerup',{});assert.equal(f.state.music.tracks[0].durationSeconds,original);assert.equal(f.state.music.tracks[0].lane,1);f.ui.dispose()});
test('ordinary pointerup does not replace selection controls before click',async()=>{const f=fixture();await f.open();const clip=f.list().find(n=>n.getAttribute('data-wvc-track-id')==='a');await clip.click();const remove=f.find('移除音乐');await f.emit('pointerup',{});assert.ok(remove.isConnected);await remove.click();await f.tick();assert.equal(f.state.music.tracks.some(t=>t.id==='a'),false);f.ui.dispose()});
test('matching honors selected speed participation and save retains full-length data',async()=>{const f=fixture();await f.open();f.field('文字速度参与匹配').checked=false;await f.field('文字速度参与匹配').emit('change');await f.click('调整故事速度匹配音乐');assert.deepEqual(f.calls.find(c=>c[0]==='fit').slice(1),[false,true]);await f.click('保存配置');const saved=f.calls.find(c=>c[0]==='save')[1];assert.equal(saved.tracks[0].durationSeconds,8);assert.equal(saved.enabled,true);f.ui.dispose()});
test('source change recalculates and does not replace unsaved music',async()=>{const f=fixture();await f.open();f.state.dirty=true;f.state.music.tracks[0].volume=37;f.snap.source='C;';f.snap.revision++;f.changed();await new Promise(r=>setTimeout(r,220));assert.equal(f.calls.filter(c=>c[0]==='measure').length,2);assert.equal(f.state.music.tracks[0].volume,37);f.ui.dispose()});
test('dirty close can be declined, accepted discards only draft; pending read cancels its consumer',async()=>{const f=fixture();await f.open();f.state.dirty=true;f.confirm(false);assert.equal(f.ui.canLeave(),false);f.confirm(true);assert.equal(f.ui.canLeave(),true);assert.ok(f.calls.some(c=>c[0]==='discard'));f.ui.dispose();let aborted=false;const g=fixture({measure:options=>new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>{aborted=true;reject(Error('cancel'))}))});await g.open();g.ui.show(false);await g.tick();assert.equal(aborted,true);g.ui.dispose()});
test('disabled inherited music can rejoin export and replaced selected controls release listeners',async()=>{const f=fixture();f.state.music.tracks[0].enabled=false;await f.open();let clip=f.list().find(n=>n.getAttribute('data-wvc-track-id')==='a');await clip.click();assert.equal(f.field('所选音乐参与导出').checked,false);const oldVolume=f.field('所选音乐音量');await f.list().find(n=>n.getAttribute('data-wvc-track-id')==='b').click();assert.equal(oldVolume.listeners.change.length,0);clip=f.list().find(n=>n.getAttribute('data-wvc-track-id')==='a');await clip.click();f.field('所选音乐参与导出').checked=true;await f.field('所选音乐参与导出').emit('change');await f.tick();assert.equal(f.state.music.tracks[0].enabled,true);f.ui.dispose()});

test('disabled clips outside active music end remain visible and selectable',async()=>{const f=fixture();f.state.music.tracks[0].enabled=false;f.state.music.tracks[0].startSeconds=100;await f.open();const clip=f.list().find(n=>n.getAttribute('data-wvc-track-id')==='a');assert.ok(parseFloat(clip.style.left)<100);assert.ok(parseFloat(clip.style.left)+parseFloat(clip.style.width)<=100.001);await clip.click();assert.ok(f.field('所选音乐参与导出'));f.ui.dispose()});
