import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {verifyMinisign} from '../update/minisign.mjs';
import {OFFICIAL_PUBLIC_KEY,OFFICIAL_ENDPOINT,OFFICIAL_HOST_SHA256,assertSignedInstallerIdentity,compareOfficialVersions,officialPlatform,assertOfficialUrl,fetchOfficialBytes,stageOfficialUpdate,cleanOfficialEnvironment} from '../update/official-stage.mjs';
import {CleanUpdateCoordinator} from '../update/clean-coordinator.mjs';
const encoded=s=>Buffer.from(s).toString('base64');
const vectorKey=encoded('untrusted comment: upstream minisign public key\nRWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3\n');
const vectorEd=encoded('untrusted comment: signature from minisign secret key\nRWQf6LRCGA9i59SLOFxz6NxvASXDJeRtuZykwQepbDEGt87ig1BNpWaVWuNrm73YiIiJbq71Wi+dP9eKL8OC351vwIasSSbXxwA=\ntrusted comment: timestamp:1555779966\tfile:test\nQtKMXWyYcwdpZAlPF7tE2ENJkRd1ujvKjlj1m9RtHTBnZPa5WKU5uWRs5GoP5M/VqE81QFuMKI5k/SfNQUaOAA==\n');
const vectorED=encoded('untrusted comment: signature from minisign secret key\nRUQf6LRCGA9i559r3g7V1qNyJDApGip8MfqcadIgT9CuhV3EMhHoN1mGTkUidF/z7SrlQgXdy8ofjb7bNJJylDOocrCo8KLzZwo=\ntrusted comment: timestamp:1556193335\tfile:test\ny/rUw2y8/hOUYjZU71eHp/Wo1KZ40fGy2VJEDl34XMJM+TX48Ss/17u3IvIfbVR1FkZZSNCisQbuQY+bHwhEBg==\n');
// Public vectors from the pinned minisign-verify 0.2.5 source, not generated by
// this implementation. Neither vector is an official Craft installer signature.
for(const [algorithm,signature] of [['Ed',vectorEd],['ED',vectorED]])test('pinned upstream '+algorithm+' vector validates both signatures and rejects changed bytes/comment',()=>{
 assert.equal(verifyMinisign(Buffer.from('test'),signature,vectorKey).algorithm,algorithm);
 assert.throws(()=>verifyMinisign(Buffer.from('Test'),signature,vectorKey),/signature mismatch/);
 assert.throws(()=>verifyMinisign(Buffer.from('test'),encoded(Buffer.from(signature,'base64').toString().replace('file:test','file:evil')),vectorKey),/comment signature/);
 assert.throws(()=>verifyMinisign(Buffer.from('test'),signature,OFFICIAL_PUBLIC_KEY),/key ID/);
});
test('malformed base64, envelopes, algorithms and key IDs fail closed',()=>{
 for(const value of ['',vectorED+'?',vectorED.slice(1),encoded('bad')])assert.throws(()=>verifyMinisign(Buffer.from('test'),value,vectorKey));
 const parts=Buffer.from(vectorED,'base64').toString().trim().split('\n'),binary=Buffer.from(parts[1],'base64');binary[0]=0;parts[1]=binary.toString('base64');assert.throws(()=>verifyMinisign(Buffer.from('test'),encoded(parts.join('\n')),vectorKey),/algorithm/);
});
test('signed filename binds product, version and x64 NSIS identity',()=>{
 const identity={trustedComment:'timestamp:1\tfile:WebGAL Craft_1.0.1_x64-setup.exe'};assertSignedInstallerIdentity(identity,'1.0.1');
 for(const value of ['timestamp:1\tfile:WebGAL Craft_1.0.0_x64-setup.exe','timestamp:1\tfile:Other_1.0.1_x64-setup.exe','timestamp:1\tfile:WebGAL Craft_1.0.1_arm64-setup.exe','timestamp:1\tfile:WebGAL Craft_1.0.1_x64-setup.exe\tfile:WebGAL Craft_1.0.1_x64-setup.exe'])assert.throws(()=>assertSignedInstallerIdentity({trustedComment:value},'1.0.1'),/product\/version\/architecture/);
});
for(const [a,b,n] of [['1.0.0-beta.2','1.0.0-beta.1',1],['1.0.0-beta.10','1.0.0-beta.2',1],['1.0.0','1.0.0-beta.2',1],['1.0.0+build2','1.0.0+build1',0],['1.0.0-beta.2','1.0.0',-1],['1.0.0-alpha','1.0.0-alpha.1',-1],['1.0.0-1','1.0.0-alpha',-1]])test(`official SemVer ${a} versus ${b}`,()=>assert.equal(compareOfficialVersions(a,b),n));
test('malformed SemVer does not downgrade into permissive lexical ordering',()=>{for(const v of ['1.0','01.0.0','1.0.0-beta.01','v1.0.0','1.0.0-','../../1'])assert.throws(()=>compareOfficialVersions(v,'1.0.0'));});
test('exact source/asset and redirect allowlist rejects lookalikes, foreign repositories and protocols',()=>{
 assertOfficialUrl(OFFICIAL_ENDPOINT,'metadata');assertOfficialUrl('https://api.github.com/repos/A-kirami/webgal-craft/releases/assets/577401298','asset');assertOfficialUrl('https://release-assets.githubusercontent.com/github-production-release-asset/42/x?signature=opaque','asset',{redirect:true});
 for(const url of ['http://api.github.com/repos/A-kirami/webgal-craft/releases/assets/1','https://api.github.com.evil.test/repos/A-kirami/webgal-craft/releases/assets/1','https://api.github.com/repos/foreign/craft/releases/assets/1','https://github.com/A-kirami/webgal-craft/releases/download/v1/setup.exe?other=1','https://user@github.com/A-kirami/webgal-craft/releases/download/v1/setup.exe','https://127.0.0.1/setup.exe'])assert.throws(()=>assertOfficialUrl(url,'asset',{redirect:true}));
});
test('download revalidates redirects and enforces a hard byte limit',async()=>{
 let calls=0;const url='https://api.github.com/repos/A-kirami/webgal-craft/releases/assets/1';
 await assert.rejects(fetchOfficialBytes(url,{fetchImpl:async()=>{calls++;return new Response(null,{status:302,headers:{location:'http://127.0.0.1/installer.exe'}});}}),/Unsafe/);assert.equal(calls,1);
 await assert.rejects(fetchOfficialBytes(url,{maxBytes:3,fetchImpl:async()=>new Response(Buffer.from('oversize'))}),/limit/);
 calls=0;const result=await fetchOfficialBytes(url,{fetchImpl:async()=>++calls===1?new Response(null,{status:302,headers:{location:'https://release-assets.githubusercontent.com/github-production-release-asset/42/binary?sig=x'}}):new Response(Buffer.from('MZ-fixture'))});assert.equal(result.toString(),'MZ-fixture');assert.equal(calls,2);
});
function metadata(version='1.0.1',id=1){return {version,platforms:{'windows-x86_64-nsis':{url:'https://api.github.com/repos/A-kirami/webgal-craft/releases/assets/'+id,signature:vectorED}}};}
test('platform selection is fixed to official Windows x64 NSIS',()=>{assert.equal(officialPlatform(metadata()).target,'windows-x86_64-nsis');assert.throws(()=>officialPlatform({version:'1.0.1',platforms:{'windows-aarch64':{url:'x',signature:'y'}}}),/x86_64/);});
async function stateFixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'craft-official-stage-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const adapterRoot=path.join(root,'adapter'),craftExe=path.join(root,'host/webgal-craft.exe'),stateDir=path.join(adapterRoot,'state');await fs.mkdir(adapterRoot);const state={schemaVersion:1,stateVersion:1,installId:crypto.randomUUID(),installMode:'same-name',status:'installed',adapterRoot,craftExe,originalExe:path.join(root,'host/webgal-craft.webvideo-original.exe'),kernelExe:path.join(adapterRoot,'kernel.exe'),stateDir,ownership:{wrapperSha256:'a'.repeat(64),originalSha256:OFFICIAL_HOST_SHA256},host:{version:'1.0.0-beta.2',sha256:OFFICIAL_HOST_SHA256},package:{manifestSha256:'b'.repeat(64)}};const statePath=path.join(adapterRoot,'config.json');await fs.writeFile(statePath,JSON.stringify(state));return {statePath,state};}
test('staging refuses native/fetched version divergence and downgrade before filesystem staging',async t=>{
 const {statePath,state}=await stateFixture(t);let calls=0;const fetchImpl=async()=>{calls++;return new Response(JSON.stringify(metadata('1.0.1',2)));};
 await assert.rejects(stageOfficialUpdate({statePath,currentVersion:'1.0.0-beta.2',version:'1.0.0-beta.1',metadata:metadata('1.0.0-beta.1'),fetchImpl}),/downgrade/);assert.equal(calls,0);
 await assert.rejects(stageOfficialUpdate({statePath,currentVersion:'1.0.0-beta.2',version:'1.0.1',metadata:metadata(),fetchImpl}),/metadata changed/);assert.equal(calls,1);await assert.rejects(fs.access(state.stateDir));
});
test('staging never trusts a signature from another key and creates no partial publish',async t=>{
 const {statePath,state}=await stateFixture(t);let calls=0;const fetchImpl=async()=>++calls===1?new Response(JSON.stringify(metadata())):new Response(Buffer.concat([Buffer.from('MZ'),Buffer.alloc(64)]));
 await assert.rejects(stageOfficialUpdate({statePath,currentVersion:'1.0.0-beta.2',version:'1.0.1',metadata:metadata(),fetchImpl}),/key ID/);await assert.rejects(fs.access(state.stateDir));
});
test('clean helper environment removes only per-process WebView debugger/profile variables case-insensitively',()=>{
 const original={PATH:'keep',WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'debug',webview2_user_data_folder:'profile',WEBVIEW2_PIPE_FOR_SCRIPT_DEBUGGER:'pipe',HOME:'keep'};assert.deepEqual(cleanOfficialEnvironment(original),{PATH:'keep',HOME:'keep'});assert.equal(original.WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS,'debug');
});
test('clean coordinator refuses disabled runtime policy before any stage/download',async()=>{let called=false;const c=new CleanUpdateCoordinator({autoInstallEnabled:false,cleanInstallValidated:false,stageOfficial:async()=>{called=true;}});await assert.rejects(c.prepare({}),/未启用/);assert.equal(called,false);});
test('abort waits staging cleanup and cannot start a late helper after host close',async()=>{
 let finish,aborted=false,spawned=false;const c=new CleanUpdateCoordinator({statePath:'/fixture/config.json',autoInstallEnabled:true,observerValidated:true,sameNameValidated:true,cleanInstallValidated:true,installMode:'same-name',stageOfficial:({signal})=>new Promise((_,reject)=>{signal.addEventListener('abort',()=>{aborted=true;finish=()=>reject(signal.reason);});}),spawnHelper:()=>{spawned=true;}});
 const preparing=c.prepare({version:'1.0.1'});preparing.catch(()=>{});let done=false;const abort=c.abort().then(()=>done=true);await Promise.resolve();assert.equal(aborted,true);assert.equal(done,false);finish();await abort;await assert.rejects(preparing,/取消/);assert.equal(spawned,false);assert.equal(c.busy,false);
});

test('high-bit algorithm aliases are rejected exactly as pinned Rust does',()=>{
 const keyLines=Buffer.from(vectorKey,'base64').toString().trim().split('\n'),sigLines=Buffer.from(vectorED,'base64').toString().trim().split('\n');
 for(const [lines,index,label] of [[keyLines,1,'key'],[sigLines,1,'signature']]){const bytes=Buffer.from(lines[index],'base64');bytes[0]|=0x80;bytes[1]|=0x80;const changed=[...lines];changed[index]=bytes.toString('base64');assert.throws(()=>verifyMinisign(Buffer.from('test'),label==='signature'?encoded(changed.join('\n')):vectorED,label==='key'?encoded(changed.join('\n')):vectorKey),/algorithm/);}
});
