import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {SessionRpc} from '../session/rpc.mjs';import {SessionStorage,safeChild} from '../session/storage.mjs';
test('RPC authenticates exact context/session/operation and rejects replay',async()=>{let called=0;const rpc=new SessionRpc({token:'abcd',bindingName:'bound',contextId:7,handlers:{read:async()=>++called}});const e={name:'bound',executionContextId:7,payload:JSON.stringify({token:'abcd',id:'1',method:'read',params:{}})};assert.equal((await rpc.dispatch(e)).value,1);await assert.rejects(rpc.dispatch(e),/duplicate/);await assert.rejects(rpc.dispatch({...e,executionContextId:8}),/context/);await assert.rejects(rpc.dispatch({...e,payload:e.payload.replace('abcd','efgh')}),/session/);assert.equal(called,1);});
test('metadata requires compare-and-swap and refuses traversal/symlink',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'craft-storage-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const storage=new SessionStorage(root),project={id:'p',path:root};await storage.metadata({project,file:'video-project.json',text:'{}',create:true},true);await assert.rejects(storage.metadata({project,file:'video-project.json',text:'{"x":1}'},true),/conflict/);await storage.metadata({project,file:'video-project.json',text:'{"x":1}',expectedText:'{}'},true);await assert.rejects(safeChild(root,'../x'),/invalid/);await fs.symlink(os.tmpdir(),path.join(root,'link'));await assert.rejects(safeChild(root,'link/file',{missing:true}),/linked/);});
test('owned snapshots require valid output and unchanged sources',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'craft-snapshot-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const project=path.join(root,'project'),data=path.join(root,'state');await fs.mkdir(project);await fs.writeFile(path.join(project,'source'),'before');const storage=new SessionStorage(data),s=await storage.allocate({id:'p',path:project},[project]);await fs.mkdir(path.join(s.site,'game','scene'),{recursive:true});await fs.writeFile(path.join(s.site,'index.html'),'game');await fs.writeFile(path.join(s.site,'game','scene','start.txt'),'text');await fs.writeFile(path.join(project,'source'),'changed');await assert.rejects(storage.ready(s.snapshotId),/source-changed/);await storage.discard(s.snapshotId);await assert.rejects(storage.discard(s.snapshotId),/unknown/);assert.equal(await fs.readFile(path.join(project,'source'),'utf8'),'changed');});

for(const [id,version,base] of [['open-webgal.webgal','4.6.4','4.6.4'],['open-webgal.webgal','4.6.5','4.6.5'],['webgal-mygo.mygo','3.2.1','4.6.4']])test(`snapshot preserves distinct engine identity ${id} ${version}`,async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'craft-identity-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const project=path.join(root,'project');await fs.mkdir(project);
 const storage=new SessionStorage(path.join(root,'state')),s=await storage.allocate({id:'p',path:project},[project],version,id,base);
 await fs.mkdir(path.join(s.site,'game','scene'),{recursive:true});await fs.writeFile(path.join(s.site,'index.html'),'game');await fs.writeFile(path.join(s.site,'game','scene','start.txt'),'text');
 await storage.ready(s.snapshotId);assert.deepEqual(JSON.parse(await fs.readFile(path.join(s.site,'webgal-engine.json'),'utf8')),{id,version,webgalVersion:base});assert.equal(storage.get(s.snapshotId).runtimeVersion,base);
});

test('snapshot never overwrites a contradictory materialized descriptor',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'craft-identity-conflict-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const project=path.join(root,'project');await fs.mkdir(project);
 const storage=new SessionStorage(path.join(root,'state')),s=await storage.allocate({id:'p',path:project},[project],'3.2.1','webgal-mygo.mygo','4.6.4');await fs.mkdir(s.site);
 const descriptor=JSON.stringify({id:'open-webgal.webgal',version:'4.6.4',webgalVersion:'4.6.4'});await fs.writeFile(path.join(s.site,'webgal-engine.json'),descriptor);
 await assert.rejects(storage.ready(s.snapshotId),/引擎描述/);assert.equal(await fs.readFile(path.join(s.site,'webgal-engine.json'),'utf8'),descriptor);
});

test('snapshot preserves matching original descriptor metadata',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'craft-identity-original-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const project=path.join(root,'project');await fs.mkdir(project);
 const storage=new SessionStorage(path.join(root,'state')),s=await storage.allocate({id:'p',path:project},[project],'3.2.1','webgal-mygo.mygo','4.6.4');await fs.mkdir(path.join(s.site,'game','scene'),{recursive:true});await fs.writeFile(path.join(s.site,'index.html'),'game');await fs.writeFile(path.join(s.site,'game','scene','start.txt'),'text');
 const descriptor=JSON.stringify({id:'webgal-mygo.mygo',version:'3.2.1',webgalVersion:'4.6.4',name:'MyGO',license:'MPL-2.0'},null,2);await fs.writeFile(path.join(s.site,'webgal-engine.json'),descriptor);
 await storage.ready(s.snapshotId);assert.equal(await fs.readFile(path.join(s.site,'webgal-engine.json'),'utf8'),descriptor);
});
