import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs/promises';
import {UpdateCoordinator} from '../update/coordinator.mjs';
const source=await fs.readFile(new URL('../update/client.js',import.meta.url),'utf8');
function fixture(){const calls=[],app={inert:false},stores={editor:{hasUnsavedDocuments:false},runtimeTask:{hasBlockingTasks:false}};const context={document:{querySelector:()=>app}};vm.runInNewContext(source,context);let ack={ready:true};const client=context.WebVideoCraftCreateUpdates({getStores:()=>stores,internals:{transformCallback:()=>17,unregisterCallback(){}},invoke:async(c,a)=>{calls.push([c,a]);if(c==='plugin:updater|check')return{rid:1,version:'1.0.1'};if(c==='plugin:updater|download')return 2;},rpc:async c=>{calls.push([c]);return ack;}});return{client,calls,app,stores,setAck:a=>ack=a};}
test('coordinated install forwards official resource IDs and restart false',async()=>{const f=fixture();await f.client.check();await f.client.download();await f.client.install();const install=f.calls.find(x=>x[0]==='plugin:updater|install');assert.deepEqual(JSON.parse(JSON.stringify(install[1])),{updateRid:1,bytesRid:2,restartAfterInstall:false});assert.equal(f.app.inert,false);});
test('dirty or busy native state prevents coordinator handoff',async()=>{const f=fixture();await f.client.check();await f.client.download();f.stores.editor.hasUnsavedDocuments=true;await assert.rejects(f.client.install(),/保存/);assert(!f.calls.some(x=>x[0]==='update.prepare'));});
test('unready coordinator never invokes install and restores editing',async()=>{const f=fixture();await f.client.check();await f.client.download();f.setAck({ready:false});await assert.rejects(f.client.install(),/就绪/);assert(!f.calls.some(x=>x[0]==='plugin:updater|install'));assert.equal(f.app.inert,false);});
test('unvalidated native completion observer cannot start real update',async()=>{const c=new UpdateCoordinator({observerValidated:false});await assert.rejects(c.prepare({version:'1.0.1'}),/尚未通过/);assert.equal(c.pending,null);});
test('same-name wrapper cannot pretend update handoff has been proven',async()=>{const c=new UpdateCoordinator({observerValidated:true,installMode:'same-name'});await assert.rejects(c.prepare({version:'1.0.1'}),/同名/);assert.equal(c.pending,null);});
