using System;using System.Linq;using System.Collections.Generic;using System.Threading;using System.Threading.Tasks;
namespace NativeVideo {
 public sealed partial class AiProviderStore {
  readonly Dictionary<string,Dictionary<string,object>> novelTasks=new Dictionary<string,Dictionary<string,object>>();CancellationTokenSource novelCancellation;string novelActive;
  public object StartNovel(object input,string gamesRoot){Enabled();lock(gate){if(novelActive!=null)throw new InvalidOperationException("已有小说转换正在进行，请完成或取消后再试。");string source=J.S(input,"source");if(string.IsNullOrWhiteSpace(source)||source.Length>2000000||J.A(J.Get(input,"units")).Count>200000||J.Text(input).Length>20000000)throw new ArgumentException("原文为空或文本过大，请按卷分次处理。");var settings=Read();string selected=J.S(settings,"selected");var saved=J.Get(J.Get(settings,"profiles"),selected);if(saved==null||J.S(saved,"secret")==""||J.S(saved,"model")=="")throw new ArgumentException("请先在配置中填写 API Key 并选择模型。");var request=new Dictionary<string,object>(J.D(saved));request["expectedConfiguration"]=CacheIdentity(saved);request.Remove("secret");request["source"]=source;request["units"]=J.Get(input,"units");request["knownSpeakers"]=J.Get(input,"knownSpeakers");string project=J.S(input,"project");request["maxActors"]=J.B(input,"allowTwo")?2:1;string id=Guid.NewGuid().ToString();request["sessionId"]=id;novelTasks.Clear();var state=J.O("id",id,"state","running","phase","正文与角色识别","startedAt",DateTime.UtcNow.ToString("o"));novelTasks[id]=state;novelActive=id;novelCancellation=new CancellationTokenSource();novelCancellation.CancelAfter(3600000);var cancel=novelCancellation;Task.Run(async()=>{try{var result=await Run(request,"novel",cancel.Token);cancel.Token.ThrowIfCancellationRequested();lock(gate){state["phase"]="扫描全部相关素材";}var assets=CollectStageAssets(gamesRoot,project,J.Get(result,"cast"));request["segments"]=J.Get(result,"segments");request["stageAssets"]=assets;lock(gate){state["phase"]="基础舞台安排";state["completedBatches"]=0;state["totalBatches"]=0;}var staging=await Run(request,"stage",cancel.Token);J.D(result)["staging"]=J.O("assets",assets,"changes",J.Get(staging,"changes"),"maxActors",J.Get(request,"maxActors"));lock(gate){if(cancel.IsCancellationRequested)state["state"]="cancelled";else{state["state"]="complete";state["result"]=result;}}}catch(Exception e){lock(gate){state["state"]=cancel.IsCancellationRequested?"cancelled":"failed";state["error"]=e.Message;}}finally{lock(gate){novelActive=null;novelCancellation=null;}cancel.Dispose();}});return J.O("id",id,"state","running");}}
  public object NovelStatus(object input){lock(gate){string id=J.S(input,"id");if(!novelTasks.ContainsKey(id))throw new ArgumentException("任务已结束或服务已重启，请重新生成。");return new Dictionary<string,object>(novelTasks[id]);}}
  public object CancelNovel(object input){lock(gate){if(J.S(input,"id")==novelActive)novelCancellation.Cancel();return J.O("ok",true);}}
  async Task<string> ReadNovelOutput(System.IO.StreamReader reader,string id){string line,result="";while((line=await reader.ReadLineAsync())!=null){if(line.Length>16000000)throw new System.IO.IOException("生成结果过大。");try{var data=J.Parse(line);if(J.S(data,"type")=="progress"){lock(gate){Dictionary<string,object> state;if(novelTasks.TryGetValue(id,out state)){state["completedBatches"]=J.N(data,"completed");state["totalBatches"]=J.N(data,"total");state["retrying"]=J.B(data,"retrying");}}continue;}}catch{}result=line;}return result;}

 }
}
