using System;using System.IO;using System.Linq;using System.Text;using System.Reflection;using System.Collections.Generic;using System.Security.Cryptography;using System.Diagnostics;using System.Threading.Tasks;
namespace NativeVideo {
 public sealed partial class AiProviderStore {
  readonly object gate=new object();readonly string folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"WebVideoPlus","ai");
  string FilePath{get{return Path.Combine(folder,"providers.json");}}
  void Enabled(){if(!File.Exists(Path.Combine(Files.Root,"ai-runtime","worker.mjs")))throw new IOException("尚未安装生成式AI组件，请通过安装器启用。");}
  object Catalog(){using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("ai-providers.factory.json")){if(stream==null)throw new IOException("提供商目录缺失，请重新安装。");using(var reader=new StreamReader(stream))return J.Parse(reader.ReadToEnd());}}
  Dictionary<string,object> Read(){if(!File.Exists(FilePath))return J.O("schemaVersion",1,"selected","","profiles",J.O());if(new FileInfo(FilePath).Length>2*1024*1024)throw new IOException("AI配置文件过大。");var value=J.D(J.Read(FilePath));if(J.N(value,"schemaVersion")!=1||!(J.Get(value,"profiles") is Dictionary<string,object>))throw new IOException("AI配置格式错误，原文件未被覆盖。");return value;}
  string Protect(string key){return Convert.ToBase64String(ProtectedData.Protect(Encoding.UTF8.GetBytes(key),null,DataProtectionScope.CurrentUser));}
  string Unprotect(string value){if(string.IsNullOrEmpty(value))return "";try{return Encoding.UTF8.GetString(ProtectedData.Unprotect(Convert.FromBase64String(value),null,DataProtectionScope.CurrentUser));}catch{throw new IOException("无法读取此账号保存的Key，请重新填写。");}}
  object Public(Dictionary<string,object> data){var profiles=J.O();foreach(var pair in J.D(J.Get(data,"profiles"))){var p=J.D(pair.Value);profiles[pair.Key]=J.O("provider",pair.Key,"baseURL",J.S(p,"baseURL"),"api",J.S(p,"api"),"model",J.S(p,"model"),"hasKey",J.S(p,"secret")!="","autoRouting",J.Get(p,"autoRouting"));}return J.O("catalog",Catalog(),"selected",J.S(data,"selected"),"profiles",profiles,"modelLists",PublicCache(data),"refreshingModels",refreshing);}
  public object Get(){Enabled();lock(gate)return Public(Read());}
  object Validate(object request){string id=J.S(request,"provider"),baseURL=J.S(request,"baseURL").Trim().TrimEnd('/'),api=J.S(request,"api"),model=J.S(request,"model").Trim();var provider=J.A(J.Get(Catalog(),"providers")).FirstOrDefault(p=>J.S(p,"id")==id);if(id!="custom"&&provider==null)throw new ArgumentException("请选择有效提供商。");if(provider!=null&&J.B(provider,"unsupported"))throw new ArgumentException(J.S(provider,"reason"));bool autoRouting=J.B(request,"autoRouting",true)&&id!="custom";var routing=provider==null?null:J.A(J.Get(provider,"models")).FirstOrDefault(m=>J.S(m,"id")==model);if(autoRouting&&routing!=null){api=J.S(routing,"api",api);baseURL=J.S(routing,"baseURL",J.S(provider,"baseURL")).TrimEnd('/');}else if(autoRouting&&provider!=null&&J.A(J.Get(provider,"models")).Select(m=>J.S(m,"api")).Distinct().Count()>1)throw new ArgumentException("此模型没有已核对的协议。请在自定义设置中关闭自动匹配，明确选择地址与协议。");Uri url;if(!Uri.TryCreate(baseURL,UriKind.Absolute,out url)||!new[]{"http","https"}.Contains(url.Scheme)||!string.IsNullOrEmpty(url.UserInfo)||!string.IsNullOrEmpty(url.Query)||!string.IsNullOrEmpty(url.Fragment)||baseURL.Contains("{"))throw new ArgumentException("请输入有效的API基础地址，不要填写Key或完整请求路径。");if(baseURL.EndsWith("/responses")||baseURL.EndsWith("/chat/completions"))throw new ArgumentException("请填写API基础地址，例如以 /v1 结尾，不要包含 /responses 或 /chat/completions。");var native=provider==null?null:J.A(J.Get(provider,"models")).FirstOrDefault(m=>J.S(m,"id")==model);string nativeApi=native==null?J.S(provider,"api"):J.S(native,"api");if(!new[]{"openai-completions","openai-responses","anthropic-messages"}.Contains(api)&&api!=nativeApi)throw new ArgumentException("不支持的API协议。");if(id=="custom"&&!new[]{"openai-completions","openai-responses","anthropic-messages"}.Contains(api))throw new ArgumentException("请选择受支持的自定义协议。");if(model.Length>300||model.Any(char.IsControl))throw new ArgumentException("模型名称无效。");return J.O("provider",id,"baseURL",baseURL,"api",api,"model",model,"catalogModel",native!=null,"apiOverride",api!=nativeApi,"autoRouting",autoRouting);}
  string ResolveKey(object request,Dictionary<string,object> data){string key=J.S(request,"key").Trim();if(key=="")key=Unprotect(J.S(J.Get(J.Get(data,"profiles"),J.S(request,"provider")),"secret"));if(key==""||key.Length>8192||key.Any(c=>c<33||c>126))throw new ArgumentException("请填写有效API Key；留空仅用于保留已保存的Key。");return key;}
  public object Save(object request){Enabled();lock(gate){var data=Read();var config=J.D(Validate(request));string key=ResolveKey(request,data);string encrypted=J.S(J.Get(J.Get(data,"profiles"),J.S(config,"provider")),"secret"),previousKey="";try{previousKey=Unprotect(encrypted);}catch{}config["secret"]=previousKey==key?encrypted:Protect(key);J.D(J.Get(data,"profiles"))[J.S(config,"provider")]=config;data["selected"]=J.S(config,"provider");Directory.CreateDirectory(folder);Files.Atomic(FilePath,J.Text(data));return Public(data);}}
  public object Remove(object request){Enabled();lock(gate){var data=Read();string id=J.S(request,"provider");J.D(J.Get(data,"profiles")).Remove(id);if(J.S(data,"selected")==id)data["selected"]="";Directory.CreateDirectory(folder);Files.Atomic(FilePath,J.Text(data));return Public(data);}}
  public async Task<object> Run(object request,string action,System.Threading.CancellationToken cancellationToken=default(System.Threading.CancellationToken)){Enabled();Dictionary<string,object> payload;lock(gate){var current=Read();string expected=J.S(request,"expectedConfiguration");if(expected!=""&&expected!=CacheIdentity(J.Get(J.Get(current,"profiles"),J.S(request,"provider"))))throw new IOException("配置已变化，本次后台刷新已取消。");payload=J.D(Validate(request));payload["key"]=ResolveKey(request,current);}if(action=="test"&&J.S(payload,"model")=="")throw new ArgumentException("请选择或填写要测试的模型。");payload["action"]=action;payload["sessionId"]=J.S(request,"sessionId");if(action=="novel"||action=="stage"){payload["source"]=J.Get(request,"source");payload["units"]=J.Get(request,"units");payload["knownSpeakers"]=J.Get(request,"knownSpeakers");payload["segments"]=J.Get(request,"segments");payload["stageAssets"]=J.Get(request,"stageAssets");payload["maxActors"]=J.Get(request,"maxActors");}
   string runtime=Path.Combine(Files.Root,"ai-runtime"),node=Path.Combine(runtime,"node.exe");if(!File.Exists(node))throw new IOException("AI运行环境缺失，请重新安装组件。");var start=new ProcessStartInfo(node,"--use-system-ca worker.mjs"){WorkingDirectory=runtime,UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8};
   foreach(var name in start.EnvironmentVariables.Keys.Cast<string>().Where(k=>k.EndsWith("_API_KEY",StringComparison.OrdinalIgnoreCase)||k.StartsWith("DSH_",StringComparison.OrdinalIgnoreCase)||k=="NODE_OPTIONS").ToArray())start.EnvironmentVariables.Remove(name);
   using(var shutdown=System.Threading.CancellationTokenSource.CreateLinkedTokenSource(refreshCancellation.Token,cancellationToken))using(var process=Process.Start(start)){var stdout=(action=="novel"||action=="stage")?ReadNovelOutput(process.StandardOutput,J.S(payload,"sessionId")):process.StandardOutput.ReadToEndAsync();var stderr=process.StandardError.ReadToEndAsync();await process.StandardInput.WriteAsync(J.Text(payload));process.StandardInput.Close();var exit=Task.Run(()=>process.WaitForExit());if(await Task.WhenAny(exit,Task.Delay(action=="novel"?3605000:55000,shutdown.Token))!=exit){try{process.Kill();}catch{}throw new IOException("连接超时，请稍后重试。");}await stderr;string output=await stdout;try{if(output.Length>(action=="novel"?16:2)*1024*1024)throw new IOException();var result=J.Parse(output);if(!J.B(result,"ok"))throw new ArgumentException(J.S(result,"error","连接未完成。"));if(action=="models")RememberModels(payload,result);return result;}catch(ArgumentException){throw;}catch{throw new IOException("AI接入层未能完成请求，请检查配置或重新安装组件。");}}
  }
 }
}
