using System;using System.IO;using System.Linq;using System.Text.RegularExpressions;using System.Collections.Generic;
namespace NativeVideo {
 public sealed partial class AiProviderStore {
  IEnumerable<string> StageFiles(string root){if(!Directory.Exists(root))yield break;if((File.GetAttributes(root)&FileAttributes.ReparsePoint)!=0)throw new IOException("素材目录不能是目录链接。");foreach(var path in Directory.EnumerateFileSystemEntries(root).OrderBy(p=>p,StringComparer.OrdinalIgnoreCase)){var attributes=File.GetAttributes(path);if((attributes&FileAttributes.ReparsePoint)!=0)throw new IOException("素材目录含链接，请先检查："+Path.GetFileName(path));if((attributes&FileAttributes.Directory)!=0){foreach(var file in StageFiles(path))yield return file;}else yield return path;}}
  bool FigureEntry(string path){if(path.Replace('\\','/').Split('/').Any(part=>part.Equals(".mtn_exp",StringComparison.OrdinalIgnoreCase)))return false;string ext=Path.GetExtension(path).ToLowerInvariant();if(ext==".jsonl"||ext==".wmdl")return true;if(ext!=".json")return false;try{if(new FileInfo(path).Length>16*1024*1024)return false;var doc=J.Read(path);return J.Get(doc,"FileReferences")!=null||J.Get(doc,"model")!=null&&J.Get(doc,"textures")!=null;}catch{return false;}}
  bool ActorPath(string path,string alias){if(string.IsNullOrWhiteSpace(alias))return false;return Regex.IsMatch(path,@"(?<![a-zA-Z])"+Regex.Escape(alias)+@"(?![a-zA-Z])",RegexOptions.IgnoreCase|RegexOptions.CultureInvariant);}
  object CollectStageAssets(string gamesRoot,string project,object cast){if(string.IsNullOrWhiteSpace(project)||project.IndexOfAny(new[]{'/','\\',':'})>=0||project=="."||project=="..")throw new ArgumentException("游戏目录无效。");string root=Files.Under(gamesRoot,project),figures=Path.Combine(root,"game","figure"),background=Path.Combine(root,"game","background");var paths=StageFiles(figures).Select(p=>p.Substring(figures.Length+1).Replace('\\','/')).ToArray();var backgrounds=StageFiles(background).Select(p=>p.Substring(background.Length+1).Replace('\\','/')).ToArray();var mapping=new CharacterMapStore().Read();if(J.B(mapping,"fatal"))throw new IOException("角色对应表不可用。");var names=J.Get(mapping,"nameToId") as Dictionary<string,string>;if(names==null)throw new IOException("角色别名表类型无效，未继续生成空素材列表。");var actors=new List<object>();var ids=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var name in J.A(cast).Select(Convert.ToString).Distinct()){string id;if(!names.TryGetValue(name.ToLowerInvariant(),out id))id="";if(id=="")id="wvp-actor-"+(actors.Count+1);if(!ids.Add(id))continue;var aliases=names.Where(pair=>Convert.ToString(pair.Value).Equals(id,StringComparison.OrdinalIgnoreCase)).Select(pair=>pair.Key).Concat(new[]{name,id}).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();actors.Add(J.O("key","actor-"+actors.Count,"name",name,"id",id,"aliases",aliases,"figures",paths.Where(p=>aliases.Any(alias=>ActorPath(p,alias))).Where(p=>FigureEntry(Path.Combine(figures,p.Replace('/',Path.DirectorySeparatorChar)))).ToArray()));}return J.O("actors",actors,"backgrounds",backgrounds);}
 }
}
