using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Diagnostics;using System.Reflection;
namespace NativeVideo {
 public sealed class AnogoActionStore {
  readonly string folder,file;readonly object gate=new object();
  public AnogoActionStore(string dataRoot=null){folder=Path.Combine(string.IsNullOrWhiteSpace(dataRoot)?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"WebVideoPlus"):Files.Full(dataRoot),"anogo-actions");file=Path.Combine(folder,"actions.json");bool firstUse=!Directory.Exists(folder);Directory.CreateDirectory(folder);if(firstUse)Files.Atomic(file,Factory());Read();}
  string Factory(){using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("anogo-actions.factory.json")){if(stream==null)throw new IOException("内置出厂表缺失，请重新安装组件");using(var reader=new StreamReader(stream))return reader.ReadToEnd();}}
  object Compile(object raw){
   var doc=raw as Dictionary<string,object>;if(doc==null||J.N(doc,"schemaVersion")!=1||!(J.Get(doc,"rows") is object[]))throw new ArgumentException("JSON 必须包含 schemaVersion: 1 和 rows 数组。");var rows=J.A(J.Get(doc,"rows"));if(rows.Count>10000)throw new ArgumentException("映射表超过 10000 行。");var lookup=J.O();var seen=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);var outputs=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);var warnings=new List<string>();
   for(int i=0;i<rows.Count;i++){var row=rows[i];if(!(J.Get(row,"names") is string)||!(J.Get(row,"motion") is string)||!(J.Get(row,"expression") is string))throw new ArgumentException("第 "+(i+1)+" 行必须包含 names、motion、expression 字符串。");string motion=J.S(row,"motion").Trim(),expression=J.S(row,"expression").Trim();var aliases=J.S(row,"names").Split(';').Select(n=>n.Trim()).ToArray();if(aliases.Any(n=>n.Length==0||n.Length>256||n.Any(char.IsControl))||motion.Length>256||expression.Length>256||motion.Any(char.IsControl)||expression.Any(char.IsControl))throw new ArgumentException("第 "+(i+1)+" 行包含空名字、过长内容或控制字符。");foreach(string name in aliases){int previous;if(seen.TryGetValue(name,out previous))warnings.Add("动作名字“"+name+"”重复：第 "+previous+"、"+(i+1)+" 行，采用下方行。");seen[name]=i+1;lookup[name.ToLowerInvariant()]=J.O("motion",motion,"expression",expression);}string pair=motion+"|"+expression;int prior;if(pair!="|"&&outputs.TryGetValue(pair,out prior))warnings.Add("动作/表情组合重复：第 "+prior+"、"+(i+1)+" 行。");outputs[pair]=i+1;}
   return J.O("fatal",false,"rows",rows,"lookup",lookup,"warnings",warnings);
  }
  public object Read(){lock(gate){string hash="";try{if(!File.Exists(file))throw new IOException("映射表文件不存在，可恢复出厂表。");hash=Files.Hash(file);if(new FileInfo(file).Length>2*1024*1024)throw new IOException("映射表超过 2 MB。");var result=J.D(Compile(J.Read(file)));result["hash"]=hash;result["folder"]=folder;return result;}catch(Exception e){return J.O("fatal",true,"message",e.Message,"hash",hash,"folder",folder,"warnings",new string[0],"lookup",J.O());}}}
  void CheckHash(object request){string actual=File.Exists(file)?Files.Hash(file):"";if(J.S(request,"expectedHash")!=actual)throw new IOException("文件已被外部修改，请重新读取后再保存。");}
  public object Save(object request){lock(gate){CheckHash(request);var doc=J.O("schemaVersion",1,"rows",J.Get(request,"rows"));Compile(doc);J.Write(file,doc);return Read();}}
  public object Reset(object request){lock(gate){CheckHash(request);var text=Factory();Compile(J.Parse(text));if(File.Exists(file))File.Copy(file,Path.Combine(folder,"actions.before-reset-"+DateTime.UtcNow.ToString("yyyyMMdd-HHmmss-fff")+".json"));Files.Atomic(file,text);return Read();}}
  public object Open(){Directory.CreateDirectory(folder);if(File.Exists(file))Process.Start(new ProcessStartInfo("explorer.exe","/select,\""+Path.GetFullPath(file)+"\""){UseShellExecute=true});else Process.Start(new ProcessStartInfo(Path.GetFullPath(folder)){UseShellExecute=true,Verb="open"});return J.O("ok",true,"folder",Path.GetFullPath(folder));}
 }
}
