using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading;
namespace NativeVideo {
 public sealed class AutomaticBackups:IDisposable {
  readonly string gamesRoot,logFile;readonly object gate=new object();readonly Dictionary<string,string> watchers=new Dictionary<string,string>();Timer timer;
  public AutomaticBackups(string games,string state){gamesRoot=games;logFile=Path.Combine(state,"automatic-backup.log");}
  string Project(string game){if(string.IsNullOrWhiteSpace(game)||game=="."||game==".."||game.IndexOfAny(new[]{'/','\\',':'})>=0)throw new ArgumentException("项目名称无效");string root=Files.Under(gamesRoot,game);if(!Directory.Exists(root))throw new DirectoryNotFoundException("项目不存在");return root;}
  IEnumerable<string> Scenes(string root){if(!Directory.Exists(root))yield break;foreach(string file in Directory.GetFiles(root,"*.txt").OrderBy(p=>p)){if((File.GetAttributes(file)&FileAttributes.ReparsePoint)==0)yield return file;}foreach(string dir in Directory.GetDirectories(root).OrderBy(p=>p)){if((File.GetAttributes(dir)&FileAttributes.ReparsePoint)!=0)continue;foreach(string file in Scenes(dir))yield return file;}}
  object Capture(string game,string id,string label){string project=Project(game),scene=Path.Combine(project,"game","scene");var entries=new List<object>();long total=0;foreach(string file in Scenes(scene)){long size=new FileInfo(file).Length;total+=size;if(size>8*1024*1024||total>64*1024*1024||entries.Count>=10000)throw new IOException("故事文本备份超出大小限制");entries.Add(J.O("file",file.Substring(scene.Length+1).Replace('\\','/'),"text",File.ReadAllText(file)));}var backup=J.O("schemaVersion",1,"kind","storySet","id",id,"label",label,"path","games/"+game+"/game/scene","createdAt",DateTime.UtcNow.ToString("o"),"fileCount",entries.Count,"before",J.Text(entries),"after","");J.Write(Path.Combine(project,".webvideo-plus","backups",id+".json"),backup);return backup;}
  public object Watch(object request){string game=J.S(request,"project"),id=J.S(request,"watchId");Guid parsed;if(!Guid.TryParse(id,out parsed))throw new ArgumentException("窗口标识无效");Project(game);lock(gate){if(watchers.ContainsKey(id)&&watchers[id]==game)return J.O("ok",true);watchers[id]=game;try{Capture(game,"automatic-open","打开游戏自动备份");}catch(Exception e){Files.Append(logFile,J.O("at",DateTime.UtcNow.ToString("o"),"project",game,"message",e.Message));}}return J.O("ok",true);}
  public object Unwatch(object request){lock(gate)watchers.Remove(J.S(request,"watchId"));return J.O("ok",true);}
  public void Start(){Schedule();}
  void Schedule(){var now=DateTime.Now;long interval=TimeSpan.FromMinutes(10).Ticks;var next=new DateTime((now.Ticks/interval+1)*interval,now.Kind);timer=new Timer(_=>Tick(),null,next-now,Timeout.InfiniteTimeSpan);}
  void Tick(){try{lock(gate){foreach(string game in watchers.Values.Distinct().ToArray())try{Capture(game,"automatic-ten-minute","整十分钟自动备份");}catch(Exception e){Files.Append(logFile,J.O("at",DateTime.UtcNow.ToString("o"),"project",game,"message",e.Message));}}}finally{lock(gate){if(timer!=null){timer.Dispose();Schedule();}}}}
  public object Restore(object request){lock(gate){string game=J.S(request,"project"),project=Project(game),name=J.S(request,"file");if(Path.GetFileName(name)!=name||!name.EndsWith(".json",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("备份文件名无效");string backupFile=Files.Under(Path.Combine(project,".webvideo-plus","backups"),name);var backup=J.Read(backupFile);if(J.S(backup,"kind")!="storySet"||J.S(backup,"path")!="games/"+game+"/game/scene")throw new ArgumentException("备份不属于当前游戏故事");if(J.S(request,"expectedCreatedAt")!=J.S(backup,"createdAt"))throw new IOException("自动备份已更新，请刷新列表后重新选择");string before=J.S(backup,"before");if(before.Length>64*1024*1024)throw new IOException("故事备份过大");var parsed=J.Parse(before);if(!(parsed is object[]))throw new IOException("故事备份格式无效");var entries=J.A(parsed);if(entries.Count>10000)throw new IOException("备份文件过多");var files=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);string scene=Path.Combine(project,"game","scene");foreach(var item in entries){string relative=J.S(item,"file"),target=Files.Under(scene,relative);if(!relative.EndsWith(".txt",StringComparison.OrdinalIgnoreCase)||!(J.Get(item,"text") is string)||files.ContainsKey(target))throw new IOException("故事备份格式无效");files[target]=J.S(item,"text");}string id=Guid.NewGuid().ToString();Capture(game,id,"回滚前自动备份");foreach(var item in files)Files.Atomic(item.Key,item.Value);return J.O("restored",files.Count,"files",files.Keys.Select(file=>"games/"+game+"/game/scene/"+file.Substring(scene.Length+1).Replace('\\','/')).ToArray());}}
  public void Dispose(){lock(gate){if(timer!=null){timer.Dispose();timer=null;}watchers.Clear();}}
 }
}
