using System;using System.IO;using System.Linq;using System.Text;using System.Drawing;using System.Collections.Generic;using System.Threading.Tasks;using System.Diagnostics;using System.Windows.Forms;using Microsoft.Web.WebView2.Core;using Microsoft.Web.WebView2.WinForms;
namespace NativeVideo {
 sealed class GpuProbeMarker:Control {
  int frame;public GpuProbeMarker(){Size=new Size(64,8);TabStop=false;SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}
  public void SetFrame(int value){frame=value&0xffffff;Invalidate();Update();}
  protected override void OnPaintBackground(PaintEventArgs e){}
  protected override void OnPaint(PaintEventArgs e){uint bits=0xa5u|((uint)frame<<8);for(int i=0;i<32;i++)e.Graphics.FillRectangle((bits&(1u<<i))!=0?Brushes.White:Brushes.Black,i*2,0,2,Height);}
 }
 public sealed class BrowserHost:Form {
  public readonly WebView2 View=new WebView2();public readonly List<string> Errors=new List<string>();public Action<object> Progress;string initId;HttpServer files;readonly int renderWidth,renderHeight;GpuProbeMarker gpuProbeMarker;CoreWebView2Environment environment;public string Runtime;
  protected override bool ShowWithoutActivation{get{return true;}}
  public BrowserHost(int width,int height){renderWidth=width;renderHeight=height;FormBorderStyle=FormBorderStyle.None;ClientSize=new Size(width,height);StartPosition=FormStartPosition.Manual;Location=new Point(-16000,-16000);ShowInTaskbar=false;View.Dock=DockStyle.Fill;Controls.Add(View);}
  public async Task Start(string profile,string gpu="auto",bool visible=false){Directory.CreateDirectory(profile);if(visible){Location=new Point(100,100);ShowInTaskbar=true;}Show();var flags="--autoplay-policy=no-user-gesture-required --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows --force-device-scale-factor=1 --disable-frame-rate-limit --disable-gpu-vsync";if(gpu=="high")flags+=" --force_high_performance_gpu";if(gpu=="low")flags+=" --force_low_power_gpu";environment=await CoreWebView2Environment.CreateAsync(null,profile,new CoreWebView2EnvironmentOptions(flags));await View.EnsureCoreWebView2Async(environment);Runtime=environment.BrowserVersionString;View.ZoomFactor=1;await View.CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDeviceMetricsOverride",J.Text(J.O("mobile",false,"width",renderWidth,"height",renderHeight,"screenWidth",renderWidth,"screenHeight",renderHeight,"deviceScaleFactor",1,"screenOrientation",J.O("angle",0,"type","landscapePrimary"),"dontSetVisibleSize",false)));View.CoreWebView2.Settings.AreDefaultContextMenusEnabled=false;View.CoreWebView2.Settings.IsStatusBarEnabled=false;View.CoreWebView2.Settings.AreDevToolsEnabled=false;View.CoreWebView2.WebMessageReceived+=(s,e)=>{try{var o=J.Parse(e.WebMessageAsJson);if(J.S(o,"type")=="progress"&&Progress!=null)Progress(J.Get(o,"data"));if(J.S(o,"type")=="error")Errors.Add(J.S(o,"message"));}catch{}};View.CoreWebView2.ProcessFailed+=(s,e)=>Errors.Add("WebView2 进程异常："+e.ProcessFailedKind);}
  public async Task InstallClock(bool media,bool deterministic){var source=File.ReadAllText(Path.Combine(Files.Root,"browser/clock-source.js"));var script="(()=>{const module={exports:{}};"+source+";globalThis.__pwClock=module.exports.inject()(globalThis,'chromium');__pwClock.controller.install(Date.now());})();\n";if(deterministic)script+="try{localStorage.clear();sessionStorage.clear();}catch{}let __seed=123456789;Math.random=()=>{__seed=(Math.imul(1664525,__seed)+1013904223)>>>0;return __seed/4294967296;};\n";if(media)script+=File.ReadAllText(Path.Combine(Files.Root,"browser/media.js"))+"\ninstallOfflineMediaClock();\n";script+=File.ReadAllText(Path.Combine(Files.Root,"browser/barrier.js"))+"\ninstallStageAssetBarrier();\n";script+="globalThis.__reportNativePlan=async data=>chrome.webview.postMessage({type:'progress',data});addEventListener('error',e=>chrome.webview.postMessage({type:'error',message:e.message}));addEventListener('unhandledrejection',e=>chrome.webview.postMessage({type:'error',message:String(e.reason?.stack||e.reason)}));";if(initId!=null)View.CoreWebView2.RemoveScriptToExecuteOnDocumentCreated(initId);initId=await View.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(script);}
  public async Task Navigate(string root){Errors.Clear();if(files!=null)files.Dispose();files=SnapshotServer.Start(root);var done=new TaskCompletionSource<bool>();EventHandler<CoreWebView2NavigationCompletedEventArgs> handler=null;handler=(s,e)=>{View.CoreWebView2.NavigationCompleted-=handler;if(e.IsSuccess)done.TrySetResult(true);else done.TrySetException(new IOException("引擎页面加载失败："+e.WebErrorStatus));};View.CoreWebView2.NavigationCompleted+=handler;View.CoreWebView2.Navigate("http://127.0.0.1:"+files.Port+"/index.html");await Timeout(done.Task,30000,"页面加载");await Wait("!!globalThis.__wgProbe?.parseScene&&!!globalThis.__probeCommands&&!!globalThis.__wgProbe.core.gameplay.pixiStage?.currentApp",20000);}
  public async Task<object> Eval(string expression,int timeout=30000){var response=await Timeout(View.CoreWebView2.CallDevToolsProtocolMethodAsync("Runtime.evaluate",J.Text(J.O("expression",expression,"awaitPromise",true,"returnByValue",true))),timeout,"页面脚本");var data=J.Parse(response);var exception=J.Get(data,"exceptionDetails");if(exception!=null)throw new InvalidOperationException(J.S(J.Get(exception,"exception"),"description",J.Text(exception)));return J.Get(J.Get(data,"result"),"value");}
  public async Task Wait(string expression,int ms=20000){var began=Stopwatch.StartNew();while(began.ElapsedMilliseconds<ms){var value=await Eval(expression);if(value is bool&&(bool)value)return;if(Errors.Count>0)throw new InvalidOperationException(string.Join("; ",Errors));await Task.Delay(20);}throw new TimeoutException("等待引擎状态超时："+expression.Substring(0,Math.Min(120,expression.Length)));}
  public async Task RunFile(string name){await Eval(File.ReadAllText(Path.Combine(Files.Root,"browser",name)));}
  public void EnableGpuProbeMarker(){if(gpuProbeMarker!=null)return;gpuProbeMarker=new GpuProbeMarker{Location=Point.Empty};Controls.Add(gpuProbeMarker);gpuProbeMarker.BringToFront();gpuProbeMarker.SetFrame(0);}
  public void SetGpuProbeMarker(int frame){if(gpuProbeMarker!=null)gpuProbeMarker.SetFrame(frame);}
  public async Task<CoreWebView2SharedBuffer> CreateGpuReadbackBuffer(int byteLength){
   if(environment==null||View.CoreWebView2==null)throw new InvalidOperationException("WebView2 尚未初始化");await Eval("globalThis.__gpuSharedReady=false;globalThis.__gpuSharedBytes=null;if(!globalThis.__gpuSharedListenerInstalled){globalThis.__gpuSharedListenerInstalled=true;chrome.webview.addEventListener('sharedbufferreceived',e=>{if(e.additionalData?.kind!=='gpu-readback')return;globalThis.__gpuSharedArrayBuffer=e.getBuffer();globalThis.__gpuSharedBytes=new Uint8Array(globalThis.__gpuSharedArrayBuffer);globalThis.__gpuSharedReady=true;});}");
   var buffer=environment.CreateSharedBuffer((ulong)byteLength);View.CoreWebView2.PostSharedBufferToScript(buffer,CoreWebView2SharedBufferAccess.ReadWrite,J.Text(J.O("kind","gpu-readback","bytes",byteLength)));await Wait("globalThis.__gpuSharedReady===true&&globalThis.__gpuSharedBytes?.byteLength==="+byteLength,10000);return buffer;
  }
  public async Task ReleaseGpuReadbackBuffer(){try{await Eval("if(globalThis.__gpuSharedArrayBuffer){chrome.webview.releaseBuffer(globalThis.__gpuSharedArrayBuffer);globalThis.__gpuSharedArrayBuffer=null;globalThis.__gpuSharedBytes=null;globalThis.__gpuSharedReady=false;}");}catch{}}
  public async Task<string> CaptureDomOverlayPngBase64(string mode="normal"){
   await Eval("__gpuDomBeginCapture("+J.Text(mode)+")");string data="";Exception failure=null;
   try{
    await View.CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDefaultBackgroundColorOverride",J.Text(J.O("color",J.O("r",0,"g",0,"b",0,"a",0))));
    var response=await Timeout(View.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.captureScreenshot",J.Text(J.O("format","png","fromSurface",true,"captureBeyondViewport",false,"optimizeForSpeed",true))),30000,"DOM overlay capture");
    data=J.S(J.Parse(response),"data");
   }catch(Exception e){failure=e;}
   try{await View.CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDefaultBackgroundColorOverride","{}");}catch{}
   try{await Eval("__gpuDomEndCapture()");}catch{}
   if(failure!=null)throw failure;return data;
  }
  public async Task<byte[]> CaptureFrame(string format="jpeg"){using(var stream=new MemoryStream()){await View.CoreWebView2.CapturePreviewAsync(format=="png"?CoreWebView2CapturePreviewImageFormat.Png:CoreWebView2CapturePreviewImageFormat.Jpeg,stream);return stream.ToArray();}}
  public static async Task<T> Timeout<T>(Task<T> task,int ms,string what){if(await Task.WhenAny(task,Task.Delay(ms))!=task)throw new TimeoutException(what+"超时");return await task;}
  protected override void Dispose(bool disposing){if(disposing){View.Dispose();if(files!=null)files.Dispose();}base.Dispose(disposing);}
 }
}
