using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;
namespace NativeVideo {
 public sealed class FilterStore {
  readonly object gate=new object();readonly string file;
  public FilterStore(string dataRoot=null){file=Path.Combine(string.IsNullOrWhiteSpace(dataRoot)?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"WebVideoPlus"):Files.Full(dataRoot),"filters","filters.json");}
  static readonly HashSet<string> fields=new HashSet<string>(new[]{"rotation","alpha","blur","brightness","contrast","saturation","gamma","colorRed","colorGreen","colorBlue","bloom","bloomBrightness","bloomBlur","bloomThreshold","bevel","bevelThickness","bevelRotation","bevelSoftness","bevelRed","bevelGreen","bevelBlue","oldFilm","dotFilm","reflectionFilm","glitchFilm","rgbFilm","godrayFilm","shockwaveFilter","radiusAlphaFilter"});
  static object Number(object value){if(value==null||value is bool||value is string||value is System.Collections.IDictionary||value is System.Collections.IEnumerable)throw new ArgumentException("效果参数必须是数字。");double number=Convert.ToDouble(value);if(double.IsNaN(number)||double.IsInfinity(number))throw new ArgumentException("效果参数不是有效数字。");return value;}
  static object Effects(object value){if(!(value is object[]))throw new ArgumentException("滤镜效果必须是数组。");var effects=J.A(value);if(effects.Count==0||effects.Count>100)throw new ArgumentException("请输入 1 到 100 段效果。");var output=new List<object>();foreach(var effect in effects){if(!(effect is Dictionary<string,object>))throw new ArgumentException("效果片段必须是对象。");var clean=J.O();foreach(var kv in J.D(effect)){if(fields.Contains(kv.Key))clean[kv.Key]=Number(kv.Value);else if(kv.Key=="position"||kv.Key=="scale"){var vector=J.O();foreach(var axis in new[]{"x","y"})if(J.D(kv.Value).ContainsKey(axis))vector[axis]=Number(J.Get(kv.Value,axis));if(vector.Count>0)clean[kv.Key]=vector;}}if(clean.Count==0)throw new ArgumentException("片段中没有可用的效果参数。");output.Add(clean);}return output;}
  object[] Saved(){if(!File.Exists(file))return new object[0];if(new FileInfo(file).Length>4*1024*1024)throw new IOException("滤镜库文件过大。");var doc=J.Read(file);if(J.N(doc,"schemaVersion")!=1||!(J.Get(doc,"filters") is object[]))throw new IOException("保存的滤镜库格式错误，未覆盖原文件。");return J.A(J.Get(doc,"filters")).ToArray();}
  object[] Presets(){using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("filter-presets.factory.json")){if(stream==null)return new object[0];using(var reader=new StreamReader(stream)){var doc=J.Parse(reader.ReadToEnd());return J.A(J.Get(doc,"filters")).ToArray();}}}
  public object List(){lock(gate){return J.O("presets",Presets(),"saved",Saved());}}
  public object Save(object request){lock(gate){var effects=Effects(J.Get(request,"effects"));var name=J.S(request,"name").Trim();if(name.Length==0||name.Length>8192)throw new ArgumentException("滤镜名称为空或过长。");var saved=Saved().ToList();string signature=J.Text(effects);var existing=saved.FirstOrDefault(item=>J.S(item,"name")==name&&J.Text(J.Get(item,"effects"))==signature);if(existing!=null)return J.O("filter",existing,"presets",Presets(),"saved",saved);if(saved.Count>=2000)throw new IOException("保存的滤镜已达到 2000 条。");var entry=J.O("id",Guid.NewGuid().ToString(),"name",name,"effects",effects,"createdAt",DateTime.UtcNow.ToString("o"));saved.Add(entry);Directory.CreateDirectory(Path.GetDirectoryName(file));J.Write(file,J.O("schemaVersion",1,"filters",saved));return J.O("filter",entry,"presets",Presets(),"saved",saved);}}
 }
}
