using System;using System.IO;using System.Text;using System.Linq;using System.Net;using System.Net.Sockets;using System.Collections.Generic;using System.Threading.Tasks;
namespace NativeVideo {
 public sealed class HttpRequest {public string Method,Path;public Dictionary<string,string> Headers=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);public byte[] Body;public object Json{get{return Body.Length==0?J.O():J.Parse(Encoding.UTF8.GetString(Body));}}}
 public sealed class HttpResponse {public int Status=200;public object Json;public byte[] Bytes;public string FilePath;public long Offset,Length=-1;public string ContentType="application/json; charset=utf-8";public Dictionary<string,string> Headers=new Dictionary<string,string>();public static HttpResponse Data(object value,int code=200){return new HttpResponse{Json=value,Status=code};}}
 public sealed class HttpServer:IDisposable {
  readonly TcpListener listener;readonly Func<HttpRequest,Task<HttpResponse>> handler;bool stopping;public readonly int Port;
  public HttpServer(Func<HttpRequest,Task<HttpResponse>> handler,int port=0){this.handler=handler;listener=new TcpListener(IPAddress.Loopback,port);listener.Start();Port=((IPEndPoint)listener.LocalEndpoint).Port;Accept();}
  async void Accept(){while(!stopping)try{var client=await listener.AcceptTcpClientAsync().ConfigureAwait(false);Task.Run(()=>Handle(client));}catch{if(!stopping)System.Threading.Thread.Sleep(100);}}
  async Task Handle(TcpClient client){using(client){try{client.NoDelay=true;client.ReceiveTimeout=30000;client.SendTimeout=30000;var stream=client.GetStream();var header=new MemoryStream();int state=0;while(state<4){int b=stream.ReadByte();if(b<0)return;header.WriteByte((byte)b);state=b==(state==0||state==2?13:10)?state+1:b==13?1:0;if(header.Length>32768)throw new IOException("请求头过长");}var lines=Encoding.ASCII.GetString(header.ToArray()).Split(new[]{"\r\n"},StringSplitOptions.None);var first=lines[0].Split(' ');var request=new HttpRequest{Method=first[0],Path=new Uri("http://localhost"+first[1]).AbsolutePath};foreach(var line in lines.Skip(1)){int n=line.IndexOf(':');if(n>0)request.Headers[line.Substring(0,n).Trim()]=line.Substring(n+1).Trim();}int length=0;if(request.Headers.ContainsKey("Content-Length")&&!int.TryParse(request.Headers["Content-Length"],out length))throw new IOException("请求长度无效");if(length<0||length>190*1024*1024)throw new IOException("请求体过大");request.Body=new byte[length];for(int n=0;n<length;){int got=await stream.ReadAsync(request.Body,n,length-n).ConfigureAwait(false);if(got<=0)throw new EndOfStreamException();n+=got;}HttpResponse response;try{response=await handler(request).ConfigureAwait(false);}catch(Exception e){response=HttpResponse.Data(J.O("error",e.Message),400);}var bytes=response.FilePath==null?(response.Bytes??Encoding.UTF8.GetBytes(J.Text(response.Json))):null;long contentLength=response.FilePath==null?bytes.Length:response.Length;var text="HTTP/1.1 "+response.Status+" "+(response.Status==200?"OK":response.Status==204?"No Content":"Error")+"\r\nContent-Type: "+response.ContentType+"\r\nContent-Length: "+contentLength+"\r\nConnection: close\r\nCache-Control: no-store\r\n"+string.Concat(response.Headers.Select(h=>h.Key+": "+h.Value+"\r\n"))+"\r\n";var head=Encoding.ASCII.GetBytes(text);await stream.WriteAsync(head,0,head.Length).ConfigureAwait(false);if(request.Method!="HEAD"){if(response.FilePath==null)await stream.WriteAsync(bytes,0,bytes.Length).ConfigureAwait(false);else using(var file=File.OpenRead(response.FilePath)){file.Seek(response.Offset,SeekOrigin.Begin);var buffer=new byte[65536];long left=contentLength;while(left>0){int n=await file.ReadAsync(buffer,0,(int)Math.Min(left,buffer.Length)).ConfigureAwait(false);if(n==0)break;await stream.WriteAsync(buffer,0,n).ConfigureAwait(false);left-=n;}}}}catch{}}}
  public void Dispose(){stopping=true;listener.Stop();}
 }
}
