using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Diagnostics;using System.Threading.Tasks;
namespace NativeVideo {
 public static class Lifecycle {
  public static async Task Run(){string configFile=Files.Full(App.Arg("--config")),backend=Files.Full(App.Arg("--backend"));var config=J.D(J.Read(configFile));string terre=Path.GetDirectoryName(backend),state=J.S(config,"stateDir");Directory.CreateDirectory(state);config["terreDir"]=terre;config["sourcePackageRoot"]=Files.Root;Commands.RuntimePath=J.S(config,"runtimePath");string environmentPort=Environment.GetEnvironmentVariable("WEBGAL_PORT");int portValue;if(int.TryParse(environmentPort,out portValue)){var address=new UriBuilder(J.S(config,"terreUrl")){Port=portValue+1};config["terreUrl"]=address.Uri.ToString();var alt=new UriBuilder(address.Uri){Host=address.Host=="localhost"?"127.0.0.1":"localhost"};config["allowedOrigins"]=new[]{address.Uri.GetLeftPart(UriPartial.Authority),alt.Uri.GetLeftPart(UriPartial.Authority)};}string lockFile=Path.Combine(state,"lifecycle.lock"),control=Path.Combine(state,"lifecycle-control.json"),logFile=Path.Combine(state,"lifecycle.log"),session=Path.Combine(state,"runtime-session.json");Action<object> log=o=>Files.Append(logFile,o);var old=J.TryRead(lockFile);if(Commands.Alive((int)J.N(old,"pid"))){NativeDialogs.Open(J.S(config,"terreUrl"));return;}if(File.Exists(lockFile))File.Delete(lockFile);using(var f=new FileStream(lockFile,FileMode.CreateNew,FileAccess.Write,FileShare.Read)){var bytes=Files.Utf8.GetBytes(J.Text(J.O("pid",Process.GetCurrentProcess().Id)));f.Write(bytes,0,bytes.Length);}if(File.Exists(control))File.Delete(control);J.Write(session,config);Process backendProcess=null,service=null;int backendPid=0,restarts=0;bool stopBackend=false;
   try{bool attach=false;try{var identity=await Integration.LocalGet(new Uri(new Uri(J.S(config,"terreUrl")),"/assets/video-export-instance.json").ToString());attach=J.S(identity,"id")==J.S(config,"instanceId");}catch{}if(attach){int port=new Uri(J.S(config,"terreUrl")).Port;var net=(await Commands.Run("netstat",new[]{"-ano","-p","tcp"},null,10000)).Text;foreach(var line in net.Split('\n')){var p=System.Text.RegularExpressions.Regex.Split(line.Trim(),@"\s+");if(p.Length>=5&&p[0]=="TCP"&&p[1].EndsWith(":"+port)&&p[3]=="LISTENING"){backendPid=int.Parse(p[4]);break;}}if(backendPid==0)throw new IOException("无法确认这份 Terre 的监听进程");}else{int at=Array.IndexOf(App.Args,"--");var args=at<0?new string[0]:App.Args.Skip(at+1).ToArray();backendProcess=Process.Start(new ProcessStartInfo(backend,string.Join(" ",args.Select(Commands.Quote))){WorkingDirectory=terre,UseShellExecute=false,CreateNoWindow=J.B(config,"hideBackendWindow")});backendPid=backendProcess.Id;}log(J.O("at",DateTime.UtcNow.ToString("o"),"phase",attach?"attached":"backend-started","backendPid",backendPid));
    while(Commands.Alive(backendPid)){if(J.S(J.TryRead(control),"action")=="stop"){stopBackend=true;break;}if(service==null||service.HasExited){if(service!=null){service.Dispose();if(restarts++>=3)throw new IOException("导出服务连续启动失败，请重新安装组件");}service=Commands.Start(Files.Exe,new[]{"service","--config",session,"--error-log",Path.Combine(state,"service-error.log")});service.OutputDataReceived+=(s,e)=>{if(e.Data!=null)Files.Append(Path.Combine(state,"service.log"),J.O("message",e.Data));};service.ErrorDataReceived+=(s,e)=>{if(e.Data!=null)Files.Append(Path.Combine(state,"service.log"),J.O("error",e.Data));};service.BeginOutputReadLine();service.BeginErrorReadLine();log(J.O("at",DateTime.UtcNow.ToString("o"),"phase","service-started","pid",service.Id));}J.Write(Path.Combine(state,"lifecycle.json"),J.O("pid",Process.GetCurrentProcess().Id,"wrapperPid",int.Parse(App.Arg("--wrapper-pid","0")),"backendPid",backendPid,"servicePid",service.Id,"terreDir",terre,"terreUrl",J.S(config,"terreUrl"),"version","0.3.14-internal","updatedAt",DateTime.UtcNow.ToString("o")));await Task.Delay(500);}
   }catch(Exception e){log(J.O("phase","failed","message",e.Message));throw;}finally{if(service!=null){if(!service.HasExited)service.Kill();service.Dispose();}if(stopBackend&&Commands.Alive(backendPid)){using(var p=Process.Start(new ProcessStartInfo("taskkill.exe","/PID "+backendPid+" /T /F"){UseShellExecute=false,CreateNoWindow=true})){p.WaitForExit(5000);}}if(backendProcess!=null)backendProcess.Dispose();if(File.Exists(lockFile)&&J.N(J.TryRead(lockFile),"pid")==Process.GetCurrentProcess().Id)File.Delete(lockFile);log(J.O("at",DateTime.UtcNow.ToString("o"),"phase","stopped"));}
  }
 }
}
