using System;using System.IO;using System.Linq;using System.Threading;using System.Threading.Tasks;using System.Windows.Forms;using System.Runtime.InteropServices;
namespace NativeVideo {
 public static partial class App {
  public static string[] Args;public static string Arg(string key,string fallback=""){int i=Array.IndexOf(Args,key);return i>=0&&i+1<Args.Length?Args[i+1]:fallback;}
  [DllImport("user32.dll")]static extern bool SetProcessDPIAware();
  [STAThread]public static int Main(string[] args){Args=args;AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling",false);AppContext.SetSwitch("Switch.System.IO.BlockLongPaths",false);SetProcessDPIAware();Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);SynchronizationContext.SetSynchronizationContext(new WindowsFormsSynchronizationContext());UI=SynchronizationContext.Current;var context=new ApplicationContext();var timer=new System.Windows.Forms.Timer{Interval=10};int code=0;timer.Tick+=async(s,e)=>{timer.Stop();try{await Dispatch();}catch(Exception error){code=1;try{Console.Error.WriteLine(error.ToString());var log=Arg("--error-log");if(log!="")Files.Atomic(log,error.ToString());else if((Args.FirstOrDefault()??"")=="export"&&(Arg("--gpu-benchmark")!=""||Arg("--gpu-readback-benchmark")!="")){var output=Arg("--out");if(output!="")Files.Atomic(Files.Full(output)+".native-work\\benchmark-error.txt",error.ToString());}}catch{}}finally{context.ExitThread();}};timer.Start();Application.Run(context);timer.Dispose();return code;}
  static async Task Dispatch(){string command=Args.FirstOrDefault()??"help";if(command=="export"){await ExportCli.Run();return;}if(command=="help"){Console.WriteLine("WebGAL.Video.exe export --project DIR --scene start.txt --out video.mp4 --workers 1..32 --mode auto|manual|bgm\nGPU benchmark: --gpu-benchmark 300 for WGC, or --gpu-readback-benchmark 300 for WebGL readPixels -> SharedBuffer");return;}if(command=="install"){await Integration.Install();return;}if(command=="uninstall"){await Integration.Uninstall();return;}if(command=="launch"){await Integration.Launch();return;}if(command=="lifecycle"){await Lifecycle.Run();return;}if(command=="check-runtime"){Console.WriteLine(J.Text(J.O("webview2",Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString(null))));return;}if(command=="service"){await new QueueService(J.Read(Arg("--config"))).Run();return;}if(command=="render"){await Renderer.Run(J.Read(Arg("--request")));return;}if(command=="job"){await new JobRunner(J.Read(Arg("--request"))).Run();return;}if(command=="plan"){var request=J.Read(Arg("--request"));string folder=J.S(request,"jobDir");await Planner.Create(request,o=>Files.Append(Path.Combine(folder,"progress.jsonl"),o));return;}if(command=="smoke"){string folder=Files.Full(Arg("--work","smoke"));Directory.CreateDirectory(folder);using(var browser=new BrowserHost(1280,720)){await browser.Start(Path.Combine(folder,"profile"));await browser.InstallClock(true,true);await browser.Navigate(Files.Full(Arg("--web")));await browser.Eval("__pwClock.controller.runFor(500)");var data=await browser.Eval("({engine:!!__wgProbe,clock:!!__pwClock,media:!!__exportMedia,parser:typeof __wgProbe.parseScene})");J.Write(Path.Combine(folder,"result.json"),J.O("passed",browser.Errors.Count==0,"runtime",browser.Runtime,"data",data,"errors",browser.Errors));}return;}if(command=="validate-settings"){var s=Settings.Validate(J.Parse(Arg("--json","{}")));Console.WriteLine(J.Text(s));return;}throw new ArgumentException("未知命令："+command);}
 }
}
