using System;using System.IO;using System.Diagnostics;using System.Runtime.InteropServices;using System.Threading;using System.Threading.Tasks;
namespace NativeVideo {
 public static class NativeDialogs {
  [ComImport,Guid("42f85136-db7e-439c-85f1-e4075d135fc8"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]interface IFileDialog {
   [PreserveSig]int Show(IntPtr parent);void SetFileTypes(uint count,IntPtr specs);void SetFileTypeIndex(uint index);void GetFileTypeIndex(out uint index);void Advise(IntPtr events,out uint cookie);void Unadvise(uint cookie);void SetOptions(uint options);void GetOptions(out uint options);void SetDefaultFolder(IShellItem folder);void SetFolder(IShellItem folder);void GetFolder(out IShellItem folder);void GetCurrentSelection(out IShellItem item);void SetFileName([MarshalAs(UnmanagedType.LPWStr)]string name);void GetFileName(out IntPtr name);void SetTitle([MarshalAs(UnmanagedType.LPWStr)]string title);void SetOkButtonLabel([MarshalAs(UnmanagedType.LPWStr)]string text);void SetFileNameLabel([MarshalAs(UnmanagedType.LPWStr)]string label);void GetResult(out IShellItem item);void AddPlace(IShellItem item,int alignment);void SetDefaultExtension([MarshalAs(UnmanagedType.LPWStr)]string extension);void Close(int result);void SetClientGuid(ref Guid guid);void ClearClientData();void SetFilter(IntPtr filter);
  }
  [ComImport,Guid("43826d1e-e718-42ee-bc55-a1e261c37bfe"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]interface IShellItem {void BindToHandler(IntPtr context,ref Guid handler,ref Guid iid,out IntPtr item);void GetParent(out IShellItem parent);void GetDisplayName(uint format,out IntPtr name);void GetAttributes(uint mask,out uint attributes);void Compare(IShellItem item,uint hint,out int order);}
  [DllImport("shell32.dll",CharSet=CharSet.Unicode,PreserveSig=false)]static extern void SHCreateItemFromParsingName(string path,IntPtr context,ref Guid iid,[MarshalAs(UnmanagedType.Interface)]out IShellItem item);
  public static object SelectFolder(string initial){object com=Activator.CreateInstance(Type.GetTypeFromCLSID(new Guid("dc1c5a9c-e88a-4dde-a5a1-60f82a20aef7")));try{var dialog=(IFileDialog)com;uint flags;dialog.GetOptions(out flags);dialog.SetOptions(flags|0x20|0x40|0x800);dialog.SetTitle("选择视频输出文件夹");dialog.SetOkButtonLabel("选择文件夹");if(Directory.Exists(initial)){IShellItem folder;Guid iid=typeof(IShellItem).GUID;SHCreateItemFromParsingName(initial,IntPtr.Zero,ref iid,out folder);try{dialog.SetFolder(folder);}finally{Marshal.ReleaseComObject(folder);}}int result=dialog.Show(IntPtr.Zero);if(result==unchecked((int)0x800704C7))return J.O("canceled",true);Marshal.ThrowExceptionForHR(result);IShellItem selected;dialog.GetResult(out selected);try{IntPtr value;selected.GetDisplayName(0x80058000,out value);try{return J.O("canceled",false,"path",Marshal.PtrToStringUni(value));}finally{Marshal.FreeCoTaskMem(value);}}finally{Marshal.ReleaseComObject(selected);}}finally{Marshal.FinalReleaseComObject(com);}}
  public static object SelectSubtitle(string initial){using(var dialog=new System.Windows.Forms.OpenFileDialog{Title="选择字幕文件",Filter="字幕文件 (*.srt;*.ass;*.ssa)|*.srt;*.ass;*.ssa|所有文件 (*.*)|*.*",CheckFileExists=true,Multiselect=false,RestoreDirectory=true}){if(File.Exists(initial)){dialog.InitialDirectory=Path.GetDirectoryName(initial);dialog.FileName=Path.GetFileName(initial);}else if(Directory.Exists(initial))dialog.InitialDirectory=initial;var result=dialog.ShowDialog();if(result!=System.Windows.Forms.DialogResult.OK)return J.O("canceled",true);return J.O("canceled",false,"path",Files.Full(dialog.FileName),"name",Path.GetFileName(dialog.FileName));}}
  public static void Open(string path){if(!File.Exists(path)&&!Directory.Exists(path)&&!Uri.IsWellFormedUriString(path,UriKind.Absolute))throw new IOException("文件或文件夹不存在");Process.Start(new ProcessStartInfo(path){UseShellExecute=true});}
  public static void OpenLog(string path){if(!File.Exists(path))Files.Atomic(path,"暂无日志。");Process.Start(new ProcessStartInfo("notepad.exe",Commands.Quote(path)){UseShellExecute=true});}
 }
 public static partial class App {
  public static SynchronizationContext UI;
  public static Task<T> OnUI<T>(Func<T> action){var done=new TaskCompletionSource<T>();UI.Post(s=>{try{done.SetResult(action());}catch(Exception e){done.SetException(e);}},null);return done.Task;}
 }
}
