using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using System.Diagnostics;
namespace NativeVideo {
 public static class Planner {

  public static async Task<object> Create(object request,Action<object> log){string dir=J.S(request,"jobDir"),folder=Path.Combine(dir,"planning"),root=Path.Combine(folder,"prepared/web"),project=J.S(request,"project"),scene=J.S(request,"scene","start.txt");Directory.CreateDirectory(folder);var settings=Settings.Validate(J.Get(request,"settings"));string input=J.S(request,"sourceSnapshot",Path.Combine(project,"game/scene",scene)),originalScript=File.ReadAllText(input),script=originalScript;var adapter=EngineAdapter.Select(request);var assets=new ProjectAssets(project,root,adapter.IsMygo?adapter.Source:J.S(request,"engineRoot",J.S(J.Get(request,"settings"),"engineRoot")),script,log,adapter);assets.Skeleton();object timing,plan;var profile=Path.Combine(folder,"profile");
   using(var browser=new BrowserHost(960,540)){
    await browser.Start(profile,J.S(settings,"gpu"));await browser.InstallClock(false,false);await browser.Navigate(root);await browser.RunFile("settings.js");await browser.Eval("__lockExportSettings("+J.Text(settings)+")");var requestedRange=J.Get(request,"range");if(requestedRange!=null){var completeParse=await browser.Eval("__wgProbe.parseScene("+J.Text(originalScript)+",'full-source',"+J.Text("./game/scene/"+scene.Replace('\\','/'))+")");var sourceStatements=J.A(J.Get(completeParse,"sentenceList"));for(int index=0;index<sourceStatements.Count;index++){var statement=sourceStatements[index];if(J.B(statement,"isLineBreakHolder"))continue;int a=(int)J.N(statement,"startLine",index)+1,b=(int)J.N(statement,"endLine",index)+1;if(a<J.N(requestedRange,"startLine")&&b>=J.N(requestedRange,"startLine")||a<=J.N(requestedRange,"endLine")&&b>J.N(requestedRange,"endLine"))throw new ArgumentException("选区边界位于多行语句内部，请重新选择完整语句");}}string snapshotRoot=J.S(request,"sceneSnapshotRoot",Path.Combine(project,"game/scene"));var chain=await SceneChain.BuildTimeline(scene,snapshotRoot,(text,name)=>browser.Eval("__wgProbe.parseScene("+J.Text(text)+","+J.Text(name)+","+J.Text("./game/scene/"+name.Replace('\\','/'))+")"));J.Write(Path.Combine(folder,"scene-chain.json"),chain);script=assets.Script=J.S(chain,"script");var parsed=await browser.Eval("__wgProbe.parseScene("+J.Text(script)+",'export-input','./game/scene/start.txt')");if(J.B(request,"analysisOnly")&&J.B(request,"linearTimeline")){var linear=VideoWorkflow.LinearTimelineSource(script,parsed);script=assets.Script=J.S(linear,"script");J.Write(Path.Combine(folder,"linear-timeline.json"),linear);parsed=await browser.Eval("__wgProbe.parseScene("+J.Text(script)+",'linear-timeline','./game/scene/start.txt')");}var scan=assets.Scan(parsed);var report=new Dictionary<string,object>(J.D(scan));report.Remove("sanitizedScript");SceneChain.AnnotateReport(report,chain);J.Write(Path.Combine(folder,"scan-report.json"),report);Files.Atomic(Path.Combine(folder,"continue-source.txt"),J.S(scan,"sanitizedScript"));if(J.A(J.Get(scan,"issues")).Count>0){if(!J.B(scan,"canContinue")||J.S(request,"approvedScanDigest")!=J.S(scan,"digest"))throw new ScanException(report);script=assets.Script=J.S(scan,"sanitizedScript");parsed=await browser.Eval("__wgProbe.parseScene("+J.Text(script)+",'export-input','./game/scene/start.txt')");assets.Parsed=parsed;}
    await assets.Snapshot();Files.Atomic(Path.Combine(folder,"prepared/input.txt"),script);await browser.Navigate(root);await browser.RunFile("settings.js");await browser.Eval("__lockExportSettings("+J.Text(settings)+")");await browser.Wait("!!__wgProbe.nativeAuto");await browser.RunFile("audio.js");await browser.RunFile("workload.js");await browser.Eval("globalThis.__nativeAggregateCounts="+J.Text(assets.AggregateCounts));var data=J.O("script",script,"parsed",parsed,"media",assets.Media,"animations",assets.Animations,"timing",null,"root",root,"project",project,"sceneName",scene,"fps",J.N(settings,"fps"));var pre=await browser.Eval("__buildNativeWorkload("+J.Text(data)+")");var durations=assets.Media.ToDictionary(k=>k.Key,k=>J.Get(k.Value,"durationMs"));var policy=J.O("renderDuringPlan",false,"mode",J.S(settings,"mode")=="auto"||(J.S(settings,"mode")=="bgm"&&J.S(settings,"bgmBaseMode")=="auto")?"auto":"manual","holdMs",J.N(settings,"holdSeconds")*1000,"textSpeed",J.N(settings,"textSpeed"),"autoSpeed",J.N(settings,"autoSpeed"),"durations",durations,"fps",J.N(settings,"fps"));await browser.RunFile("render.js");await browser.RunFile("timeline.js");var last=Stopwatch.StartNew();browser.Progress=o=>{last.Restart();log(J.O("phase","planning-progress","line",J.Get(o,"line"),"totalLines",J.Get(o,"totalLines"),"videoSeconds",J.Get(o,"videoSeconds")));};log(J.O("phase","timeline-start"));var pending=browser.Eval("__createNativeTimeline("+J.Text(J.O("script",script,"policy",policy))+")",7200000);while(!pending.IsCompleted){if(last.ElapsedMilliseconds>120000)throw new TimeoutException("时序引擎连续两分钟未取得进展");await Task.WhenAny(pending,Task.Delay(1000));}var result=await pending;if(browser.Errors.Count>0)throw new IOException("时序预演发生错误："+string.Join("; ",browser.Errors));
    var playlist=new List<object>();foreach(var f in J.A(J.Get(request,"bgmFiles"))){string file=Files.Full(Convert.ToString(f));log(J.O("phase","music-info","current",playlist.Count,"total",J.A(J.Get(request,"bgmFiles")).Count));playlist.Add(J.O("file",file,"durationMs",await Commands.Duration(file)));}timing=await browser.Eval("__finishNativeTimeline("+J.Text(J.O("result",result,"pre",pre,"settings",settings,"playlist",playlist,"range",null))+")");data["timing"]=timing;plan=await browser.Eval("__buildNativeWorkload("+J.Text(data)+")");SceneChain.AttachTimeline(timing,chain,scene);J.D(plan)["domWorkload"]=J.Get(result,"domWorkload")??new object[0];J.D(plan)["presentation"]=assets.Presentation;J.D(plan)["root"]=root;J.D(plan)["runtime"]=browser.Runtime;J.D(plan)["engine"]=adapter.Describe();J.D(plan)["storyTimeline"]=J.Get(timing,"storyTimeline");VideoWorkflow.AddMusic(plan,request,timing);var audioArgs=await browser.Eval("audioMixArguments("+J.Text(J.Get(plan,"audio"))+","+J.Num(J.N(timing,"durationSeconds"))+","+J.Text(J.Get(plan,"muteWindows"))+")");J.Write(Path.Combine(folder,"audio-args.json"),audioArgs);
   }
   if(J.B(request,"analysisOnly")&&J.B(request,"linearTimeline")){var linear=J.Read(Path.Combine(folder,"linear-timeline.json"));J.D(timing)["linearTimeline"]=true;J.D(timing)["ignoredLines"]=J.Get(linear,"ignoredLines");}
   J.Write(Path.Combine(folder,"timing-plan.json"),timing);J.Write(Path.Combine(folder,"prepared/plan.json"),plan);if(J.B(request,"analysisOnly")){log(J.O("phase","planned","durationSeconds",J.N(timing,"durationSeconds")));return J.O("timing",timing,"plan",plan);}var envelopes=new List<object>();foreach(var a in J.A(J.Get(plan,"audio")).Where(x=>J.S(x,"kind")=="voice")){var bytes=(await Commands.Run("ffmpeg",new[]{"-v","error","-i",J.S(a,"path"),"-f","f32le","-ac","1","-ar","16000","pipe:1"},null,60000,default(System.Threading.CancellationToken),true)).Bytes;var values=new List<double>();int samples=bytes.Length/4;for(int n=0;n<samples;n+=320){double sum=0;for(int k=n;k<Math.Min(n+320,samples);k++){double f=BitConverter.ToSingle(bytes,k*4);sum+=f*f;}values.Add(Math.Sqrt(sum/320));}var sorted=values.OrderBy(x=>x).ToArray();var env=new Dictionary<string,object>(J.D(a));env["values"]=values;env["peak"]=sorted.Length>0&&sorted[(int)Math.Floor(sorted.Length*.9)]>0?sorted[(int)Math.Floor(sorted.Length*.9)]:.1;envelopes.Add(env);}J.Write(Path.Combine(folder,"envelopes.json"),envelopes);log(J.O("phase","planned","durationSeconds",J.N(timing,"durationSeconds"),"events",J.A(J.Get(plan,"events")).Count,"mode",J.S(settings,"mode")));return J.O("timing",timing,"plan",plan);
  }
 }
}
