using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Text.RegularExpressions;using System.Threading.Tasks;
namespace NativeVideo {
 public sealed class ScanException:Exception {public object Report;public ScanException(object report):base("完整扫描发现 "+J.A(J.Get(report,"issues")).Count+" 项问题"){Report=report;}}
 public sealed class ProjectAssets {
  public readonly string Project,Root,Engine;public string Script;public object Parsed,Presentation;public readonly Dictionary<string,object> Media=new Dictionary<string,object>(),Animations=new Dictionary<string,object>();public Action<object> Log;public readonly EngineAdapter Adapter;public readonly Dictionary<string,object> AggregateCounts=new Dictionary<string,object>();readonly Dictionary<string,string> copies=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);readonly Dictionary<string,object> issues=new Dictionary<string,object>();readonly List<object> actions=new List<object>();readonly HashSet<string> checkedFiles=new HashSet<string>(StringComparer.OrdinalIgnoreCase);readonly HashSet<string> visits=new HashSet<string>();readonly List<object> libraries=new List<object>();
  static readonly Regex Resource=new Regex(@"\.(jsonl|wmdl|json|moc3?|mtn|png|jpe?g|webp|gif|mp3|wav|ogg|m4a|aac|flac|mp4|webm|mov|mkv|ttf|woff2?)([?#].*)?$",RegexOptions.IgnoreCase);
  public ProjectAssets(string project,string root,string engine,string script,Action<object> log,EngineAdapter adapter){Adapter=adapter;Project=Files.Full(project);Root=Files.Full(root);Engine=string.IsNullOrWhiteSpace(engine)?Project:Files.Full(engine);Script=script.TrimStart('\uFEFF');Log=log;if(Files.Within(Project,Root,true))throw new IOException("工作目录必须位于原工程之外");}
  void Report(object value){if(Log!=null)Log(value);}
  public void Skeleton(){Adapter.Prepare(Root);var initialTemplate=Directory.Exists(Path.Combine(Project,"game/template"))?Path.Combine(Project,"game/template"):Path.Combine(Engine,"game/template");if(Directory.Exists(initialTemplate))Files.CopyTree(initialTemplate,Path.Combine(Root,"game/template"));Directory.CreateDirectory(Path.Combine(Root,"game/scene"));Files.Atomic(Path.Combine(Root,"game/scene/start.txt"),":;\n");Directory.CreateDirectory(Path.Combine(Root,"lib"));foreach(var name in new[]{"live2d.min.js","live2dcubismcore.min.js"}){var source=(Adapter.IsMygo?new[]{Engine,Project}:new[]{Project,Engine}).Select(p=>Path.Combine(p,"lib",name)).FirstOrDefault(File.Exists);libraries.Add(J.O("name",name,"found",source!=null));if(source!=null)Files.CopyFile(source,Path.Combine(Root,"lib",name));else Files.Atomic(Path.Combine(Root,"lib",name),"");}var config=Path.Combine(Project,"game/config.txt");Files.Atomic(Path.Combine(Root,"game/config.txt"),File.Exists(config)?File.ReadAllText(config):"Game_name:WebGAL;\nDefault_Language:zh_CN;\nStage_Width:1920;\nStage_Height:1080;\n");Files.Atomic(Path.Combine(Root,"game/userStyleSheet.css"),"");Files.Atomic(Path.Combine(Root,"game/animation/animationTable.json"),"[]");}
  public string Resolve(string kind,string name){name=PhysicalName(Clean(kind,name));foreach(var root in new[]{Project,Engine}.Distinct(StringComparer.OrdinalIgnoreCase)){string p;try{p=Files.Under(Path.Combine(root,"game"),kind+"/"+name);}catch{return null;}if(File.Exists(p))return p;}return null;}
  public static string Clean(string kind,string name){return Regex.Replace(name??"","^\\.?/?game/"+kind+"/","");}
  bool Allowed(string file){return Files.Within(Project,file)||Files.Within(Engine,file);}
  void Add(string kind,int line,string file,string message,object action=null){var key=J.Text(new[]{kind,file,message});object o;if(!issues.TryGetValue(key,out o)){o=J.O("kind",kind,"file",file,"message",message,"lines",new List<object>());issues[key]=o;}var lines=(List<object>)J.Get(o,"lines");if(line>0&&!lines.Contains(line))lines.Add(line);if(action!=null)actions.Add(action);}
  void JsonChildren(object obj,string key,List<string> values){if(obj is string){if(Resource.IsMatch((string)obj)&&!key.Equals("name",StringComparison.OrdinalIgnoreCase))values.Add((string)obj);}else if(obj is Dictionary<string,object>){foreach(var kv in J.D(obj))JsonChildren(kv.Value,kv.Key,values);}else foreach(var v in J.A(obj))JsonChildren(v,key,values);}
  void Inspect(string file,int line,string label,object action,string destination,HashSet<string> ancestry=null){if(file==null||!File.Exists(file)){Add("missing",line,label,"找不到资源文件",action);return;}if(!Allowed(file)){Add("unsupported",line,label,"资源引用超出工程目录，请先导入工程");return;}checkedFiles.Add(file);var key=file+"|"+line+"|"+J.Text(action);if(visits.Contains(key)||(ancestry!=null&&ancestry.Contains(file)))return;visits.Add(key);if(destination!=null){if(!Files.Within(Root,destination))throw new IOException("资源副本路径无效");copies[destination]=file;}var extension=Path.GetExtension(file).ToLowerInvariant();if(!new[]{".json",".jsonl",".wmdl"}.Contains(extension))return;var children=new List<string>();try{ReadModelDependencies(file,destination,extension,children);}catch(Exception e){Add("syntax",line,label,"模型或 JSON 无法解析："+e.Message);return;}var next=ancestry==null?new HashSet<string>(StringComparer.OrdinalIgnoreCase):new HashSet<string>(ancestry,StringComparer.OrdinalIgnoreCase);next.Add(file);foreach(var value in children){if(Regex.IsMatch(value,@"^(https?:|data:)",RegexOptions.IgnoreCase)){if(!value.StartsWith("data:"))Add("unsupported",line,value,"当前离线导出不自动下载外链素材");continue;}string child,target;try{var clean=PhysicalName(value);bool gameRelative=extension==".jsonl"&&clean.StartsWith("game/",StringComparison.OrdinalIgnoreCase);string sourceRoot=Files.Within(Project,file)?Project:Engine;child=Files.Full(Path.Combine(gameRelative?sourceRoot:Path.GetDirectoryName(file),clean));target=destination==null?null:Files.Full(Path.Combine(gameRelative?Root:Path.GetDirectoryName(destination),clean));if(target!=null&&!Files.Within(Root,target))throw new IOException("资源路径超出工程目录");}catch(Exception e){Add("unsupported",line,value,e.Message);continue;}Inspect(child,line,value,action,target,next);}}
  static string PhysicalName(string name){return Uri.UnescapeDataString(Regex.Split(name??"","[?#]")[0]).Replace('\\','/');}
  void ReadModelDependencies(string file,string destination,string extension,List<string> children){
   if(extension==".json"){JsonChildren(J.Read(file),"",children);return;}
   if(!Adapter.IsMygo)throw new IOException("聚合模型需要 MyGO 引擎");
   int count=0;
   if(extension==".jsonl"){
    foreach(var line in File.ReadLines(file)){
     if(string.IsNullOrWhiteSpace(line))continue;
     var row=J.Parse(line);
     if(J.Get(row,"motions")!=null||J.Get(row,"expressions")!=null)continue;
     string path=J.S(row,"path");if(path=="")continue;
     children.Add(path);count++;
    }
   }else{
    var model=J.Read(file);var rows=new[]{model}.Concat(J.A(J.Get(model,"subModels")));
    foreach(var row in rows){string path=J.S(row,"modelRelativePath");if(path!=""){children.Add(path);count++;}}
   }
   if(count==0)throw new IOException("聚合模型没有有效的子模型路径");
   if(destination!=null)AggregateCounts["/"+destination.Substring(Root.Length+1).Replace('\\','/')]=count;
  }
  void Ref(string kind,string name,int line,object action){if(string.IsNullOrEmpty(name)||name=="none")return;name=PhysicalName(Clean(kind,name));string target;try{target=Files.Under(Path.Combine(Root,"game"),kind+"/"+name);}catch{Add("unsupported",line,name,"资源路径超出工程目录");return;}Inspect(Resolve(kind,name),line,kind+"/"+name,action,target);}
  public static Dictionary<string,object> Params(object sentence){var p=new Dictionary<string,object>();foreach(var arg in J.A(J.Get(sentence,"args")))p[J.S(arg,"key")]=J.Get(arg,"value");return p;}
  public static bool SingleLineHint(string command,object sentence,Dictionary<string,object> args){if(command!="choose"||J.N(args,"defaultChoose",-1)!=1||J.B(args,"next"))return false;double ms=J.N(args,"wvpHint",-1);if(ms<100||ms>60000)return false;var options=Regex.Split(J.S(sentence,"content"),@"(?<!\\)\|");if(options.Length!=1)return false;var nodes=Regex.Split(options[0],@"(?<!\\):");return nodes.Length==2&&Regex.IsMatch(nodes[1].Trim(),@"^__wvp_hint_[A-Za-z0-9_]+$");}
  public static bool ConvertibleSingleChoose(string command,object sentence,Dictionary<string,object> args){if(command!="choose"||args.ContainsKey("wvpHint")||J.B(args,"next")||args.Keys.Any(key=>key!="defaultChoose"))return false;var options=Regex.Split(J.S(sentence,"content"),@"(?<!\\)\|");if(options.Length!=1||options[0].Contains("->"))return false;var nodes=Regex.Split(options[0],@"(?<!\\):");return nodes.Length==2&&!string.IsNullOrWhiteSpace(nodes[0])&&!string.IsNullOrWhiteSpace(nodes[1]);}
  void CheckJson(object text,bool array,int line,string label){try{object value=text is string?J.Parse((string)text):text;if(array?!(value is object[]):!(value is Dictionary<string,object>))throw new Exception(array?"应为动画帧数组":"应为对象");}catch(Exception e){Add("syntax",line,label,"参数无法解析："+e.Message);}}
  public object Scan(object parsed){Parsed=parsed;var lines=Regex.Split(Script,"\r?\n");var sentences=J.A(J.Get(parsed,"sentenceList"));var forbidden=new HashSet<string>(new[]{"changeScene","callScene","return","choose","chooseLabel","jumpLabel","getUserInput","if","setVar","showVars"});var mapping=new Dictionary<string,string>{{"changeBg","background"},{"changeFigure","figure"},{"miniAvatar","figure"},{"bgm","bgm"},{"playEffect","vocal"},{"playVideo","video"}};var args=new Dictionary<string,string>{{"vocal","vocal"},{"backgroundImage","background"},{"mouthOpen","figure"},{"mouthClose","figure"},{"mouthHalfOpen","figure"},{"eyesOpen","figure"},{"eyesClose","figure"}};
   for(int i=0;i<lines.Length;i++){int line=i+1;if(string.IsNullOrWhiteSpace(lines[i])||lines[i].TrimStart().StartsWith(";"))continue;if(i>=sentences.Count){Add("syntax",line,"场景","此行未能解析");continue;}var s=sentences[i];string cmd=J.N(s,"command",-1)==0?"say":J.S(s,"commandRaw");var p=Params(s);bool singleLineHint=SingleLineHint(cmd,s,p),convertibleSingleChoose=ConvertibleSingleChoose(cmd,s,p);var skip=J.O("line",line,"kind","skip-line");if((forbidden.Contains(cmd)&&!singleLineHint)||J.B(p,"userForward")||p.ContainsKey("when"))Add("unsupported",line,cmd,convertibleSingleChoose?"普通单选分支会等待玩家操作；可转为单行提示后导出":"含跨场景、分支、变量或需要玩家操作的命令");if(cmd=="setTransform"||cmd=="setTempAnimation")CheckJson(J.Get(s,"content"),cmd=="setTempAnimation",line,cmd);if(p.ContainsKey("transform"))CheckJson(p["transform"],false,line,"transform");double wait;if(cmd=="wait"&&(!double.TryParse(J.S(s,"content"),out wait)||wait<0))Add("syntax",line,"wait","等待时长需要是非负毫秒数");if(mapping.ContainsKey(cmd))Ref(mapping[cmd],J.S(s,"content"),line,skip);if(cmd=="changeFigure"){var content=J.S(s,"content");if(Regex.IsMatch(content,@"\.(skel|mkv)([?#].*)?$",RegexOptions.IgnoreCase)||content.Contains("type=spine"))Add("unsupported",line,content,"当前不支持此立绘格式");else if(!Adapter.IsMygo&&(Regex.IsMatch(content,@"\.(webm|mp4|mov|jsonl|wmdl)([?#].*)?$",RegexOptions.IgnoreCase)||content.Contains("type=video")))Add("unsupported",line,content,"此立绘需要选择已安装的 MyGO 3.2.1 引擎");}foreach(var a in args)if(p.ContainsKey(a.Key))Ref(a.Value,J.S(p,a.Key),line,J.O("line",line,"kind","remove-argument","key",a.Key));if(cmd=="setAnimation")Ref("animation",J.S(s,"content")+".json",line,skip);if(new[]{"setTransition","changeBg","changeFigure"}.Contains(cmd))foreach(var key in new[]{"enter","exit"})if(p.ContainsKey(key))Ref("animation",J.S(p,key)+".json",line,J.O("line",line,"kind","remove-argument","key",key));if(i%10==0)Report(J.O("phase","scanning","scannedLines",line,"totalLines",lines.Length,"checkedFiles",checkedFiles.Count));}
   foreach(var lib in libraries)if(!J.B(lib,"found"))Add("environment",0,J.S(lib,"name"),"未找到引擎运行库，请检查工程或安装配置");var template=Path.Combine(Project,"game/template");if(Directory.Exists(template))foreach(var file in Directory.GetFiles(template,"*",SearchOption.AllDirectories)){checkedFiles.Add(file);if(Path.GetFileName(file)=="template.json")try{J.Read(file);}catch(Exception e){Add("syntax",0,"template.json","模板 JSON 无法解析："+e.Message);}if(Regex.IsMatch(file,@"\.(css|scss)$",RegexOptions.IgnoreCase))foreach(Match m in Regex.Matches(File.ReadAllText(file),"url\\(\\s*[\"']?([^\"')]+)[\"']?\\s*\\)")){string name=m.Groups[1].Value.Trim();if(Regex.IsMatch(name,@"^(data:|https?:|#|/assets/)",RegexOptions.IgnoreCase))continue;var clean=Regex.Split(name,"[?#]")[0];var child=Regex.IsMatch(clean,@"^\.?/?game/")?Files.Full(Path.Combine(Project,Regex.Replace(clean,@"^\.?/",""))):Files.Full(Path.Combine(Path.GetDirectoryName(file),clean));if(Allowed(child))Inspect(child,0,name,J.O("kind","font-fallback"),null);}}
   var table=Path.Combine(Project,"game/animation/animationTable.json");if(File.Exists(table))try{var names=J.Read(table);if(!(names is object[])||J.A(names).Any(x=>!(x is string)))throw new Exception("应为动画名称数组");foreach(var name in J.A(names))Ref("animation",name+".json",0,J.O("kind","animation-table","name",name));}catch(Exception e){Add("syntax",0,"animationTable.json","动画表无法解析："+e.Message);}var list=issues.Values.ToArray();var unique=actions.GroupBy(J.Text).Select(g=>g.First()).ToArray();var sanitized=(string[])lines.Clone();foreach(var a in unique){int n=(int)J.N(a,"line")-1;if(n<0||n>=sanitized.Length)continue;if(J.S(a,"kind")=="skip-line")sanitized[n]="; 导出副本：跳过缺少资源的语句";if(J.S(a,"kind")=="remove-argument"&&!sanitized[n].StartsWith(";"))sanitized[n]=StripArgument(sanitized[n],J.S(a,"key"));}return J.O("schemaVersion",1,"complete",true,"totalLines",lines.Length,"checkedFiles",checkedFiles.Count,"issues",list,"actions",unique,"canContinue",list.Length>0&&list.All(x=>J.S(x,"kind")=="missing"),"digest",Files.HashText(J.Text(J.O("script",Script,"issues",list))),"sanitizedScript",string.Join("\n",sanitized));
  }
  static string StripArgument(string line,string key){var starts=new List<KeyValuePair<int,string>>();char quote='\0';bool escape=false;int depth=0;for(int i=0;i<line.Length;i++){char c=line[i];if(escape){escape=false;continue;}if(c=='\\'){escape=true;continue;}if(quote!='\0'){if(c==quote)quote='\0';continue;}if(c=='"'||c=='\''){quote=c;continue;}if(c=='{'||c=='[')depth++;if(c=='}'||c==']')depth--;if(depth==0&&char.IsWhiteSpace(c)&&i+1<line.Length&&line[i+1]=='-'){var m=Regex.Match(line.Substring(i+1),@"^-([A-Za-z]\w*)");if(m.Success)starts.Add(new KeyValuePair<int,string>(i,m.Groups[1].Value));}}int at=starts.FindIndex(x=>x.Value==key);if(at<0)return line;int end=at+1<starts.Count?starts[at+1].Key:line.LastIndexOf(';')>=0?line.LastIndexOf(';'):line.Length;return line.Substring(0,starts[at].Key)+line.Substring(end);}
  public async Task Snapshot(){long bytes=0;int count=0;foreach(var item in copies){Files.CopyFile(item.Value,item.Key);bytes+=new FileInfo(item.Value).Length;if(++count%50==0){Report(J.O("phase","copying","copiedFiles",count,"copiedBytes",bytes));await Task.Yield();}}foreach(var name in new[]{"template","animation"}){var from=Path.Combine(Project,"game",name);if(!Directory.Exists(from)&&name=="template")from=Path.Combine(Engine,"game",name);if(Directory.Exists(from))Files.CopyTree(from,Path.Combine(Root,"game",name));}var css=Path.Combine(Project,"game/userStyleSheet.css");if(File.Exists(css))Files.CopyFile(css,Path.Combine(Root,"game/userStyleSheet.css"));var table=Path.Combine(Root,"game/animation/animationTable.json");var names=J.A(J.TryRead(table)).Where(n=>File.Exists(Path.Combine(Root,"game/animation",n+".json"))).ToArray();J.Write(table,names);var fontRoot=Directory.Exists(Path.Combine(Project,"game/template"))?Project:Engine;var fonts=new FontSnapshot(fontRoot,Root).Run();Presentation=J.O("fonts",fonts,"animationNames",names,"aggregateCounts",AggregateCounts);foreach(var file in Directory.GetFiles(Path.Combine(Root,"game/animation"),"*.json")){if(Path.GetFileName(file)=="animationTable.json")continue;Animations[Path.GetFileNameWithoutExtension(file)]=J.Read(file);}var mediaFiles=copies.Keys.Where(x=>Regex.IsMatch(x,@"\.(mp3|wav|ogg|m4a|aac|flac|mp4|webm|mov|mkv)$",RegexOptions.IgnoreCase)).ToArray();for(int i=0;i<mediaFiles.Length;i++){var file=mediaFiles[i];Report(J.O("phase","media-info","current",i,"total",mediaFiles.Length));var probe=await Commands.Probe(file);double duration=J.N(J.Get(probe,"format"),"duration")*1000;if(duration<=0)throw new IOException("媒体时长无效："+Path.GetFileName(file));var url="/"+file.Substring(Root.Length+1).Replace('\\','/');Media[url]=J.O("durationMs",duration,"hasAudio",J.A(J.Get(probe,"streams")).Any(s=>J.S(s,"codec_type")=="audio"));}Report(J.O("phase","copying","copiedFiles",count,"copiedBytes",bytes));}
 }
 public sealed class FontSnapshot {
  readonly string project,target;readonly List<object> declared=new List<object>();readonly HashSet<string> visited=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
  public FontSnapshot(string project,string root){this.project=project;target=Path.Combine(root,"game/template");Directory.CreateDirectory(target);}
  string Resolve(string from,string url){if(Regex.IsMatch(url,@"^(https?:|//)",RegexOptions.IgnoreCase))throw new IOException("工程字体需要外网："+url);if(url.StartsWith("data:"))return url;var clean=Uri.UnescapeDataString(Regex.Split(url,"[?#]")[0]);var file=Files.Full(Path.Combine(clean.StartsWith("/")?project:from,clean.TrimStart('/')));if(!Files.Within(project,file)||!File.Exists(file))throw new IOException("工程字体不存在或位于工程目录以外："+url);return file;}
  void Add(Dictionary<string,object> font,string file){if(declared.Any(f=>J.S(f,"font-family")==J.S(font,"font-family")&&J.S(f,"weight")==J.S(font,"weight")&&J.S(f,"style")==J.S(font,"style")))return;string url=file;if(!file.StartsWith("data:")){url="fonts/"+Files.Hash(file)+Path.GetExtension(file);Files.CopyFile(file,Path.Combine(target,url));}font["url"]=url;font["display"]="block";declared.Add(font);}
  void Css(string file){if(visited.Contains(file)||!File.Exists(file))return;visited.Add(file);var text=Regex.Replace(File.ReadAllText(file),@"/\*[\s\S]*?\*/","");foreach(Match m in Regex.Matches(text,"@import\\s+(?:url\\()?['\"]([^'\"]+)['\"]"))Css(Resolve(Path.GetDirectoryName(file),m.Groups[1].Value));foreach(Match m in Regex.Matches(text,@"@font-face\s*\{([^}]+)\}")){string block=m.Groups[1].Value;var family=Regex.Match(block,@"font-family\s*:\s*([^;]+)",RegexOptions.IgnoreCase);var url=Regex.Match(block,"url\\(\\s*['\"]?([^'\"\\)]+)['\"]?\\s*\\)",RegexOptions.IgnoreCase);if(!family.Success||!url.Success)continue;var format=Regex.Match(block,"format\\(['\"]([^'\"]+)['\"]\\)",RegexOptions.IgnoreCase);var ext=Path.GetExtension(url.Groups[1].Value);var f=J.O("font-family",family.Groups[1].Value.Trim().Trim('\'', '"'),"type",format.Success?format.Groups[1].Value:ext==".woff2"?"woff2":ext==".woff"?"woff":ext==".otf"?"opentype":"truetype");foreach(var k in new[]{"weight","style"}){var v=Regex.Match(block,"font-"+k+@"\s*:\s*([^;]+)",RegexOptions.IgnoreCase);if(v.Success)f[k]=v.Groups[1].Value.Trim();}Add(f,Resolve(Path.GetDirectoryName(file),url.Groups[1].Value));}}
  public List<object> Run(){var original=Path.Combine(project,"game/template/template.json");var source=J.TryRead(original)??new Dictionary<string,object>();var fonts=J.A(J.Get(source,"fonts"));if(fonts.Count>0)foreach(var f in fonts){if(J.S(f,"url")=="")throw new IOException("字体缺少资源路径");Add(new Dictionary<string,object>(J.D(f)),Resolve(Path.GetDirectoryName(original),Regex.Replace(J.S(f,"url"),@"^[./]+","")));}else if(!J.B(source,"_exportFontsProcessed")){var html=Path.Combine(project,"index.html");if(File.Exists(html))foreach(Match m in Regex.Matches(File.ReadAllText(html),"<link\\b[^>]*href=['\"]([^'\"]+\\.css(?:\\?[^'\"]*)?)['\"][^>]*>",RegexOptions.IgnoreCase))Css(Resolve(project,m.Groups[1].Value));}var file=Path.Combine(target,"template.json");var data=J.D(J.TryRead(file)??J.O("name","Export font snapshot","webgal-version","4.6.4"));data["_exportFontsProcessed"]=true;data["fonts"]=declared;J.Write(file,data);return declared;}
 }
}
